-- Lean seed — TODO.
--
-- The in-place seed is frozen at `supabase/_legacy/seed-inplace.sql` (it seeds the
-- pre-lean schema and references cut tables, so it is NOT used by the lean baseline).
-- A lean seed for the 58-table baseline (tenant + branches + positions/roles + menu
-- + system_settings, etc.) is pending.
--
-- Kept as an (empty) placeholder so `supabase/config.toml` [db.seed] sql_paths
-- resolves and `supabase db reset` does not fail.
