-- D093: central-only GRN + branch stock requests + fulfill→DC
-- Decision: docs/plan/decisions.md D093; ops: docs/ref/inventory-role-ops.md

-- ── 1) Ingredient default fulfill site ──────────────────────────────────────

ALTER TABLE public.ingredients
  ADD COLUMN IF NOT EXISTS default_fulfill_site_kind text;

ALTER TABLE public.ingredients
  DROP CONSTRAINT IF EXISTS ingredients_default_fulfill_site_kind_check;

ALTER TABLE public.ingredients
  ADD CONSTRAINT ingredients_default_fulfill_site_kind_check
  CHECK (
    default_fulfill_site_kind IS NULL
    OR default_fulfill_site_kind = ANY (
      ARRAY['central_supply'::text, 'central_kitchen'::text]
    )
  );

COMMENT ON COLUMN public.ingredients.default_fulfill_site_kind IS
  'D093: which central site fulfills branch stock-request lines for this ingredient.';

-- ── 2) Doc number kind stock_request ────────────────────────────────────────

ALTER TABLE public.tenant_inventory_doc_counters
  DROP CONSTRAINT IF EXISTS tenant_inventory_doc_counters_kind_check;

ALTER TABLE public.tenant_inventory_doc_counters
  ADD CONSTRAINT tenant_inventory_doc_counters_kind_check CHECK (
    doc_kind = ANY (ARRAY[
      'grn'::text,
      'transfer'::text,
      'issue'::text,
      'waste'::text,
      'production'::text,
      'stocktake'::text,
      'count_slip'::text,
      'stock_request'::text
    ])
  );

CREATE OR REPLACE FUNCTION public.next_inventory_doc_number(
  p_tenant_id bigint,
  p_doc_kind text
) RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_year smallint;
  v_seq bigint;
  v_prefix text;
  v_kind text :=
    pg_catalog.lower(pg_catalog.btrim(COALESCE(p_doc_kind, '')));
BEGIN
  IF p_tenant_id IS NULL OR p_tenant_id <= 0 THEN
    RAISE EXCEPTION 'next_inventory_doc_number: invalid tenant_id'
      USING ERRCODE = 'invalid_parameter_value';
  END IF;
  IF auth.role() IS DISTINCT FROM 'service_role'
     AND (
       public.auth_tenant_id() IS NULL
       OR public.auth_tenant_id() <> p_tenant_id
     ) THEN
    RAISE EXCEPTION 'next_inventory_doc_number: tenant scope mismatch'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  v_prefix := CASE v_kind
    WHEN 'grn' THEN 'GRN'
    WHEN 'transfer' THEN 'DC'
    WHEN 'issue' THEN 'PXK'
    WHEN 'waste' THEN 'HH'
    WHEN 'production' THEN 'LSX'
    WHEN 'stocktake' THEN 'KK'
    WHEN 'count_slip' THEN 'PD'
    WHEN 'stock_request' THEN 'YC'
    ELSE NULL
  END;

  IF v_prefix IS NULL THEN
    RAISE EXCEPTION 'next_inventory_doc_number: invalid doc_kind'
      USING ERRCODE = 'invalid_parameter_value';
  END IF;

  v_year := EXTRACT(
    year FROM (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')
  )::smallint;

  INSERT INTO public.tenant_inventory_doc_counters (
    tenant_id, doc_kind, year, next_seq, updated_at
  )
  VALUES (p_tenant_id, v_kind, v_year, 2, now())
  ON CONFLICT (tenant_id, doc_kind, year) DO UPDATE
  SET next_seq =
        public.tenant_inventory_doc_counters.next_seq + 1,
      updated_at = now()
  RETURNING public.tenant_inventory_doc_counters.next_seq - 1
  INTO v_seq;

  RETURN v_prefix
    || '-'
    || v_year::text
    || '-'
    || pg_catalog.lpad(v_seq::text, 4, '0');
END;
$$;

-- ── 3) Permission keys ──────────────────────────────────────────────────────

INSERT INTO public.permission_keys (
  key, module, description, scope, is_delegable_to_staff
)
VALUES
  (
    'inventory:request_create',
    'inventory',
    'Create branch stock request drafts',
    'branch',
    TRUE
  ),
  (
    'inventory:request_submit',
    'inventory',
    'Submit branch stock requests',
    'branch',
    TRUE
  ),
  (
    'inventory:request_cancel',
    'inventory',
    'Cancel branch stock requests',
    'branch',
    TRUE
  ),
  (
    'inventory:request_fulfill',
    'inventory',
    'Fulfill stock-request lines into transfers',
    'branch',
    TRUE
  )
ON CONFLICT (key) DO UPDATE
SET description = EXCLUDED.description,
    module = EXCLUDED.module,
    scope = EXCLUDED.scope,
    is_delegable_to_staff = EXCLUDED.is_delegable_to_staff;

-- ── 4) stock_requests tables ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.stock_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES public.tenants(id),
  branch_id bigint NOT NULL REFERENCES public.branches(id),
  request_number text NOT NULL,
  status text NOT NULL DEFAULT 'draft',
  notes text,
  created_by uuid REFERENCES auth.users(id),
  submitted_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stock_requests_status_check CHECK (
    status = ANY (ARRAY[
      'draft'::text,
      'submitted'::text,
      'partially_fulfilled'::text,
      'fulfilled'::text,
      'cancelled'::text
    ])
  ),
  CONSTRAINT stock_requests_tenant_number_unique
    UNIQUE (tenant_id, request_number)
);

CREATE TABLE IF NOT EXISTS public.stock_request_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES public.tenants(id),
  request_id bigint NOT NULL
    REFERENCES public.stock_requests(id) ON DELETE CASCADE,
  ingredient_id bigint NOT NULL REFERENCES public.ingredients(id),
  entry_unit_id bigint NOT NULL REFERENCES public.units(id),
  quantity numeric(15, 3) NOT NULL,
  fulfill_site_kind text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  transfer_id bigint REFERENCES public.stock_transfers(id),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stock_request_items_qty_check CHECK (quantity > 0),
  CONSTRAINT stock_request_items_fulfill_kind_check CHECK (
    fulfill_site_kind = ANY (
      ARRAY['central_supply'::text, 'central_kitchen'::text]
    )
  ),
  CONSTRAINT stock_request_items_status_check CHECK (
    status = ANY (ARRAY[
      'pending'::text,
      'allocated'::text,
      'shipped'::text,
      'received'::text,
      'rejected'::text,
      'cancelled'::text
    ])
  )
);

CREATE INDEX IF NOT EXISTS stock_requests_branch_status_idx
  ON public.stock_requests (tenant_id, branch_id, status);

CREATE INDEX IF NOT EXISTS stock_request_items_fulfill_pending_idx
  ON public.stock_request_items (tenant_id, fulfill_site_kind, status)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS stock_request_items_request_idx
  ON public.stock_request_items (request_id);

ALTER TABLE public.stock_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_request_items ENABLE ROW LEVEL SECURITY;

-- ── 5) RLS helpers / policies ───────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.stock_request_actor_can_read(
  p_branch_id bigint
) RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT public.auth_is_owner(auth.uid())
    OR public.has_permission(p_branch_id, 'inventory:read')
    OR public.has_permission_any('inventory:request_fulfill')
    OR public.has_permission(p_branch_id, 'inventory:request_create');
$$;

DROP POLICY IF EXISTS stock_requests_select ON public.stock_requests;
CREATE POLICY stock_requests_select
  ON public.stock_requests
  FOR SELECT
  TO authenticated
  USING (
    tenant_id = public.auth_tenant_id()
    AND public.stock_request_actor_can_read(branch_id)
  );

DROP POLICY IF EXISTS stock_request_items_select ON public.stock_request_items;
CREATE POLICY stock_request_items_select
  ON public.stock_request_items
  FOR SELECT
  TO authenticated
  USING (
    tenant_id = public.auth_tenant_id()
    AND EXISTS (
      SELECT 1
      FROM public.stock_requests AS req
      WHERE req.id = stock_request_items.request_id
        AND req.tenant_id = stock_request_items.tenant_id
        AND public.stock_request_actor_can_read(req.branch_id)
    )
  );

-- Mutations go through SECURITY DEFINER RPCs only.
DROP POLICY IF EXISTS stock_requests_no_direct_write ON public.stock_requests;
CREATE POLICY stock_requests_no_direct_write
  ON public.stock_requests
  FOR ALL
  TO authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS stock_request_items_no_direct_write
  ON public.stock_request_items;
CREATE POLICY stock_request_items_no_direct_write
  ON public.stock_request_items
  FOR ALL
  TO authenticated
  USING (false)
  WITH CHECK (false);

GRANT SELECT ON public.stock_requests TO authenticated;
GRANT SELECT ON public.stock_request_items TO authenticated;
GRANT ALL ON public.stock_requests TO service_role;
GRANT ALL ON public.stock_request_items TO service_role;

-- ── 6) GRN central-site-only guard ──────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.enforce_grn_central_site_only()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_kind text;
BEGIN
  SELECT branch.branch_kind
  INTO v_kind
  FROM public.branches AS branch
  WHERE branch.id = NEW.branch_id
    AND branch.tenant_id = NEW.tenant_id;

  IF v_kind IS DISTINCT FROM 'central_supply'
     AND v_kind IS DISTINCT FROM 'central_kitchen' THEN
    RAISE EXCEPTION 'grn_central_site_only'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_grn_central_site_only
  ON public.goods_received_notes;
CREATE TRIGGER trg_grn_central_site_only
  BEFORE INSERT OR UPDATE OF branch_id
  ON public.goods_received_notes
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_grn_central_site_only();

-- ── 7) Transfer create: permission (not owner-only) ─────────────────────────

CREATE OR REPLACE FUNCTION public.create_stock_transfer_draft(
  p_from_branch_id bigint,
  p_to_branch_id bigint,
  p_transfer_number text,
  p_notes text DEFAULT NULL,
  p_vehicle_info text DEFAULT NULL,
  p_lines jsonb DEFAULT '[]',
  p_from_location_id bigint DEFAULT NULL,
  p_to_location_id bigint DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_transfer_id bigint;
  v_from_kind text;
  v_to_kind text;
  v_line jsonb;
  v_ingredient_id bigint;
  v_entry_unit_id bigint;
  v_entry_quantity numeric(15,3);
  v_transfer_number text;
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  IF p_from_branch_id = p_to_branch_id THEN
    RAISE EXCEPTION 'transfer_requires_distinct_branches'
      USING ERRCODE = '22023';
  END IF;
  IF p_from_location_id IS NULL OR p_to_location_id IS NULL THEN
    RAISE EXCEPTION 'transfer_warehouse_locations_required'
      USING ERRCODE = 'not_null_violation';
  END IF;

  PERFORM branch.id
  FROM public.branches AS branch
  WHERE branch.id = ANY(ARRAY[
    p_from_branch_id,
    p_to_branch_id
  ]::bigint[])
  ORDER BY branch.id
  FOR UPDATE OF branch;

  SELECT branch.branch_kind
  INTO v_from_kind
  FROM public.branches AS branch
  WHERE branch.id = p_from_branch_id
    AND branch.tenant_id = v_tenant
    AND branch.is_active IS TRUE
    AND branch.branch_kind IN (
      'branch',
      'central_supply',
      'central_kitchen'
    );

  SELECT branch.branch_kind
  INTO v_to_kind
  FROM public.branches AS branch
  WHERE branch.id = p_to_branch_id
    AND branch.tenant_id = v_tenant
    AND branch.is_active IS TRUE
    AND branch.branch_kind IN (
      'branch',
      'central_supply',
      'central_kitchen'
    );

  IF v_from_kind IS NULL OR v_to_kind IS NULL THEN
    RAISE EXCEPTION 'transfer_branch_invalid'
      USING ERRCODE = 'check_violation';
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM public.inventory_locations AS location
    WHERE location.id = p_from_location_id
      AND location.tenant_id = v_tenant
      AND location.branch_id = p_from_branch_id
      AND location.location_kind = 'warehouse'
      AND location.is_active IS TRUE
  ) OR NOT EXISTS (
    SELECT 1
    FROM public.inventory_locations AS location
    WHERE location.id = p_to_location_id
      AND location.tenant_id = v_tenant
      AND location.branch_id = p_to_branch_id
      AND location.location_kind = 'warehouse'
      AND location.is_active IS TRUE
  ) THEN
    RAISE EXCEPTION 'transfer_warehouse_location_invalid'
      USING ERRCODE = 'check_violation';
  END IF;

  -- D093: transfer_create on from-site (owner + central ops), not owner-only role.
  IF NOT public.auth_is_owner(auth.uid())
     AND NOT public.has_permission(
       p_from_branch_id,
       'inventory:transfer_create'
     ) THEN
    RAISE EXCEPTION 'forbidden_transfer_create'
      USING ERRCODE = '42501';
  END IF;

  IF p_lines IS NULL
     OR jsonb_typeof(p_lines) <> 'array'
     OR jsonb_array_length(p_lines) = 0 THEN
    RAISE EXCEPTION 'transfer_lines_invalid' USING ERRCODE = '22023';
  END IF;

  v_transfer_number := public.next_inventory_doc_number(
    v_tenant,
    'transfer'
  );

  INSERT INTO public.stock_transfers (
    tenant_id,
    from_branch_id,
    to_branch_id,
    from_location_id,
    to_location_id,
    transfer_number,
    status,
    notes,
    vehicle_info,
    created_by
  )
  VALUES (
    v_tenant,
    p_from_branch_id,
    p_to_branch_id,
    p_from_location_id,
    p_to_location_id,
    v_transfer_number,
    'draft',
    p_notes,
    p_vehicle_info,
    v_uid
  )
  RETURNING id INTO v_transfer_id;

  FOR v_line IN
    SELECT value
    FROM jsonb_array_elements(p_lines) AS line(value)
  LOOP
    v_ingredient_id := NULLIF(
      coalesce(
        v_line ->> 'ingredientId',
        v_line ->> 'ingredient_id'
      ),
      ''
    )::bigint;
    v_entry_quantity := NULLIF(
      v_line ->> 'quantity',
      ''
    )::numeric(15,3);
    v_entry_unit_id := NULLIF(
      coalesce(
        v_line ->> 'entryUnitId',
        v_line ->> 'entry_unit_id'
      ),
      ''
    )::bigint;

    IF v_ingredient_id IS NULL
       OR v_entry_quantity IS NULL
       OR v_entry_quantity <= 0
       OR v_entry_quantity = 'NaN'::numeric
       OR v_entry_quantity = 'Infinity'::numeric
       OR v_entry_quantity = '-Infinity'::numeric THEN
      RAISE EXCEPTION 'transfer_lines_invalid'
        USING ERRCODE = '22023';
    END IF;
    IF NOT EXISTS (
      SELECT 1
      FROM public.ingredients AS ingredient
      WHERE ingredient.id = v_ingredient_id
        AND ingredient.tenant_id = v_tenant
        AND ingredient.is_active IS TRUE
    ) THEN
      RAISE EXCEPTION 'transfer_ingredient_invalid:%',
        v_ingredient_id
        USING ERRCODE = 'check_violation';
    END IF;

    IF v_entry_unit_id IS NULL THEN
      SELECT ingredient_unit.unit_id
      INTO v_entry_unit_id
      FROM public.ingredient_units AS ingredient_unit
      JOIN public.units AS unit
        ON unit.id = ingredient_unit.unit_id
       AND unit.tenant_id = ingredient_unit.tenant_id
       AND unit.is_active IS TRUE
      WHERE ingredient_unit.tenant_id = v_tenant
        AND ingredient_unit.ingredient_id = v_ingredient_id
        AND ingredient_unit.is_base IS TRUE
        AND ingredient_unit.is_active IS TRUE
      ORDER BY ingredient_unit.sort_order, ingredient_unit.id
      LIMIT 1;
    ELSIF NOT EXISTS (
      SELECT 1
      FROM public.ingredient_units AS ingredient_unit
      JOIN public.units AS unit
        ON unit.id = ingredient_unit.unit_id
       AND unit.tenant_id = ingredient_unit.tenant_id
       AND unit.is_active IS TRUE
      WHERE ingredient_unit.tenant_id = v_tenant
        AND ingredient_unit.ingredient_id = v_ingredient_id
        AND ingredient_unit.unit_id = v_entry_unit_id
        AND ingredient_unit.is_active IS TRUE
    ) THEN
      RAISE EXCEPTION 'entry_unit_not_found:%',
        v_ingredient_id
        USING ERRCODE = 'foreign_key_violation';
    END IF;
    IF v_entry_unit_id IS NULL THEN
      RAISE EXCEPTION 'entry_unit_not_found:%',
        v_ingredient_id
        USING ERRCODE = 'foreign_key_violation';
    END IF;

    INSERT INTO public.stock_transfer_items (
      tenant_id,
      transfer_id,
      ingredient_id,
      quantity,
      entry_unit_id,
      unit_cost_at_ship
    )
    VALUES (
      v_tenant,
      v_transfer_id,
      v_ingredient_id,
      v_entry_quantity,
      v_entry_unit_id,
      (
        SELECT stock.avg_unit_cost
        FROM public.stock_levels AS stock
        WHERE stock.tenant_id = v_tenant
          AND stock.branch_id = p_from_branch_id
          AND stock.location_id = p_from_location_id
          AND stock.ingredient_id = v_ingredient_id
        LIMIT 1
      )
    )
    ON CONFLICT (transfer_id, ingredient_id, tenant_id)
    DO UPDATE SET
      quantity = EXCLUDED.quantity,
      entry_unit_id = EXCLUDED.entry_unit_id,
      unit_cost_at_ship = EXCLUDED.unit_cost_at_ship;
  END LOOP;

  RETURN jsonb_build_object(
    'id', v_transfer_id,
    'status', 'draft',
    'transfer_number', v_transfer_number
  );
END;
$$;


-- ── 8) Production operator: drop branch_manager ─────────────────────────────

CREATE OR REPLACE FUNCTION public.is_inventory_production_operator()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT public.auth_is_owner(auth.uid())
    OR public.auth_role() = 'central_kitchen_lead';
$$;

-- ── 9) Stock request RPCs ───────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.create_stock_request_draft(
  p_branch_id bigint,
  p_notes text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_kind text;
  v_id bigint;
  v_number text;
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT branch.branch_kind INTO v_kind
  FROM public.branches AS branch
  WHERE branch.id = p_branch_id
    AND branch.tenant_id = v_tenant
    AND branch.is_active IS TRUE;

  IF v_kind IS DISTINCT FROM 'branch' THEN
    RAISE EXCEPTION 'stock_request_branch_site_only'
      USING ERRCODE = 'check_violation';
  END IF;

  IF NOT public.auth_is_owner(auth.uid())
     AND NOT public.has_permission(p_branch_id, 'inventory:request_create')
  THEN
    RAISE EXCEPTION 'forbidden_request_create' USING ERRCODE = '42501';
  END IF;

  v_number := public.next_inventory_doc_number(v_tenant, 'stock_request');

  INSERT INTO public.stock_requests (
    tenant_id, branch_id, request_number, status, notes, created_by
  )
  VALUES (
    v_tenant, p_branch_id, v_number, 'draft', p_notes, v_uid
  )
  RETURNING id INTO v_id;

  RETURN jsonb_build_object(
    'request_id', v_id,
    'request_number', v_number
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.add_stock_request_line(
  p_request_id bigint,
  p_ingredient_id bigint,
  p_entry_unit_id bigint,
  p_quantity numeric
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_req public.stock_requests%ROWTYPE;
  v_fulfill text;
  v_item_id bigint;
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_req
  FROM public.stock_requests AS req
  WHERE req.id = p_request_id
    AND req.tenant_id = v_tenant
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'stock_request_not_found' USING ERRCODE = 'no_data_found';
  END IF;
  IF v_req.status IS DISTINCT FROM 'draft' THEN
    RAISE EXCEPTION 'stock_request_not_draft' USING ERRCODE = '22023';
  END IF;
  IF NOT public.auth_is_owner(auth.uid())
     AND NOT public.has_permission(
       v_req.branch_id,
       'inventory:request_create'
     )
  THEN
    RAISE EXCEPTION 'forbidden_request_create' USING ERRCODE = '42501';
  END IF;

  SELECT ingredient.default_fulfill_site_kind
  INTO v_fulfill
  FROM public.ingredients AS ingredient
  WHERE ingredient.id = p_ingredient_id
    AND ingredient.tenant_id = v_tenant
    AND ingredient.is_active IS TRUE;

  IF v_fulfill IS NULL THEN
    RAISE EXCEPTION 'ingredient_fulfill_site_required'
      USING ERRCODE = 'check_violation';
  END IF;
  IF p_quantity IS NULL OR p_quantity <= 0 THEN
    RAISE EXCEPTION 'stock_request_qty_invalid' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.stock_request_items (
    tenant_id,
    request_id,
    ingredient_id,
    entry_unit_id,
    quantity,
    fulfill_site_kind,
    status
  )
  VALUES (
    v_tenant,
    p_request_id,
    p_ingredient_id,
    p_entry_unit_id,
    p_quantity,
    v_fulfill,
    'pending'
  )
  RETURNING id INTO v_item_id;

  RETURN jsonb_build_object(
    'item_id', v_item_id,
    'fulfill_site_kind', v_fulfill
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_stock_request(
  p_request_id bigint
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_tenant bigint := public.auth_tenant_id();
  v_req public.stock_requests%ROWTYPE;
  v_line_count int;
BEGIN
  IF auth.uid() IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_req
  FROM public.stock_requests AS req
  WHERE req.id = p_request_id AND req.tenant_id = v_tenant
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'stock_request_not_found' USING ERRCODE = 'no_data_found';
  END IF;
  IF v_req.status IS DISTINCT FROM 'draft' THEN
    RAISE EXCEPTION 'stock_request_not_draft' USING ERRCODE = '22023';
  END IF;
  IF NOT public.auth_is_owner(auth.uid())
     AND NOT public.has_permission(
       v_req.branch_id,
       'inventory:request_submit'
     )
  THEN
    RAISE EXCEPTION 'forbidden_request_submit' USING ERRCODE = '42501';
  END IF;

  SELECT count(*)::int INTO v_line_count
  FROM public.stock_request_items AS item
  WHERE item.request_id = p_request_id
    AND item.tenant_id = v_tenant;

  IF v_line_count < 1 THEN
    RAISE EXCEPTION 'stock_request_empty' USING ERRCODE = '22023';
  END IF;

  UPDATE public.stock_requests
  SET status = 'submitted',
      submitted_at = now(),
      updated_at = now()
  WHERE id = p_request_id;

  RETURN jsonb_build_object('request_id', p_request_id, 'status', 'submitted');
END;
$$;

CREATE OR REPLACE FUNCTION public.cancel_stock_request(
  p_request_id bigint
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_tenant bigint := public.auth_tenant_id();
  v_req public.stock_requests%ROWTYPE;
BEGIN
  IF auth.uid() IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_req
  FROM public.stock_requests AS req
  WHERE req.id = p_request_id AND req.tenant_id = v_tenant
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'stock_request_not_found' USING ERRCODE = 'no_data_found';
  END IF;
  IF v_req.status NOT IN ('draft', 'submitted') THEN
    RAISE EXCEPTION 'stock_request_not_cancellable' USING ERRCODE = '22023';
  END IF;
  IF NOT public.auth_is_owner(auth.uid())
     AND NOT public.has_permission(
       v_req.branch_id,
       'inventory:request_cancel'
     )
  THEN
    RAISE EXCEPTION 'forbidden_request_cancel' USING ERRCODE = '42501';
  END IF;

  UPDATE public.stock_request_items
  SET status = 'cancelled', updated_at = now()
  WHERE request_id = p_request_id
    AND tenant_id = v_tenant
    AND status = 'pending';

  UPDATE public.stock_requests
  SET status = 'cancelled',
      cancelled_at = now(),
      updated_at = now()
  WHERE id = p_request_id;

  RETURN jsonb_build_object('request_id', p_request_id, 'status', 'cancelled');
END;
$$;

CREATE OR REPLACE FUNCTION public.fulfill_stock_request_lines(
  p_request_id bigint,
  p_fulfill_site_kind text,
  p_from_branch_id bigint,
  p_from_location_id bigint,
  p_item_ids bigint[]
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_req public.stock_requests%ROWTYPE;
  v_from_kind text;
  v_to_location_id bigint;
  v_lines jsonb := '[]'::jsonb;
  v_item public.stock_request_items%ROWTYPE;
  v_result jsonb;
  v_transfer_id bigint;
  v_pending int;
  v_done int;
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  IF p_fulfill_site_kind IS DISTINCT FROM 'central_supply'
     AND p_fulfill_site_kind IS DISTINCT FROM 'central_kitchen' THEN
    RAISE EXCEPTION 'fulfill_site_kind_invalid' USING ERRCODE = '22023';
  END IF;

  IF NOT public.auth_is_owner(auth.uid())
     AND NOT public.has_permission_any('inventory:request_fulfill')
  THEN
    RAISE EXCEPTION 'forbidden_request_fulfill' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO v_req
  FROM public.stock_requests AS req
  WHERE req.id = p_request_id AND req.tenant_id = v_tenant
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'stock_request_not_found' USING ERRCODE = 'no_data_found';
  END IF;
  IF v_req.status NOT IN ('submitted', 'partially_fulfilled') THEN
    RAISE EXCEPTION 'stock_request_not_fulfillable' USING ERRCODE = '22023';
  END IF;

  SELECT branch.branch_kind INTO v_from_kind
  FROM public.branches AS branch
  WHERE branch.id = p_from_branch_id
    AND branch.tenant_id = v_tenant
    AND branch.is_active IS TRUE;

  IF v_from_kind IS DISTINCT FROM p_fulfill_site_kind THEN
    RAISE EXCEPTION 'fulfill_from_site_mismatch'
      USING ERRCODE = 'check_violation';
  END IF;

  IF NOT public.auth_is_owner(auth.uid())
     AND public.auth_branch_id() IS DISTINCT FROM p_from_branch_id
     AND public.auth_role() IN (
       'central_supply_ops',
       'central_kitchen_lead'
     )
  THEN
    RAISE EXCEPTION 'forbidden_request_fulfill_scope'
      USING ERRCODE = '42501';
  END IF;

  SELECT location.id INTO v_to_location_id
  FROM public.inventory_locations AS location
  WHERE location.tenant_id = v_tenant
    AND location.branch_id = v_req.branch_id
    AND location.location_kind = 'warehouse'
    AND location.is_active IS TRUE
  LIMIT 1;

  IF v_to_location_id IS NULL THEN
    RAISE EXCEPTION 'stock_request_destination_warehouse_missing'
      USING ERRCODE = 'check_violation';
  END IF;

  FOR v_item IN
    SELECT *
    FROM public.stock_request_items AS item
    WHERE item.request_id = p_request_id
      AND item.tenant_id = v_tenant
      AND item.id = ANY (p_item_ids)
      AND item.fulfill_site_kind = p_fulfill_site_kind
      AND item.status = 'pending'
    FOR UPDATE
  LOOP
    v_lines := v_lines || jsonb_build_array(
      jsonb_build_object(
        'ingredient_id', v_item.ingredient_id,
        'entry_unit_id', v_item.entry_unit_id,
        'quantity', v_item.quantity
      )
    );
  END LOOP;

  IF jsonb_array_length(v_lines) = 0 THEN
    RAISE EXCEPTION 'stock_request_fulfill_empty' USING ERRCODE = '22023';
  END IF;

  v_result := public.create_stock_transfer_draft(
    p_from_branch_id,
    v_req.branch_id,
    '',
    'Fulfill stock request ' || v_req.request_number,
    NULL,
    v_lines,
    p_from_location_id,
    v_to_location_id
  );

  v_transfer_id := coalesce(
    (v_result ->> 'id')::bigint,
    (v_result ->> 'transfer_id')::bigint
  );

  UPDATE public.stock_request_items
  SET status = 'allocated',
      transfer_id = v_transfer_id,
      updated_at = now()
  WHERE request_id = p_request_id
    AND tenant_id = v_tenant
    AND id = ANY (p_item_ids)
    AND fulfill_site_kind = p_fulfill_site_kind
    AND status = 'pending';

  SELECT
    count(*) FILTER (WHERE status = 'pending')::int,
    count(*) FILTER (
      WHERE status IN ('allocated', 'shipped', 'received')
    )::int
  INTO v_pending, v_done
  FROM public.stock_request_items
  WHERE request_id = p_request_id
    AND tenant_id = v_tenant
    AND status <> 'cancelled';

  UPDATE public.stock_requests
  SET status = CASE
        WHEN v_pending = 0 THEN 'fulfilled'
        WHEN v_done > 0 THEN 'partially_fulfilled'
        ELSE status
      END,
      updated_at = now()
  WHERE id = p_request_id;

  RETURN jsonb_build_object(
    'request_id', p_request_id,
    'transfer_id', v_transfer_id,
    'transfer_number', v_result ->> 'transfer_number'
  );
END;
$$;

REVOKE ALL ON FUNCTION public.create_stock_request_draft(bigint, text)
  FROM PUBLIC;
REVOKE ALL ON FUNCTION public.add_stock_request_line(
  bigint, bigint, bigint, numeric
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.submit_stock_request(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cancel_stock_request(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.fulfill_stock_request_lines(
  bigint, text, bigint, bigint, bigint[]
) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.create_stock_request_draft(bigint, text)
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.add_stock_request_line(
  bigint, bigint, bigint, numeric
) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.submit_stock_request(bigint)
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.cancel_stock_request(bigint)
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fulfill_stock_request_lines(
  bigint, text, bigint, bigint, bigint[]
) TO authenticated, service_role;

-- ── 10) Role template grants (D093) ─────────────────────────────────────────

-- branch_manager: drop grn + production; add request_*
UPDATE public.role_templates AS template
SET permission_keys = (
  SELECT coalesce(array_agg(DISTINCT k ORDER BY k), ARRAY[]::text[])
  FROM unnest(
    array_remove(
      array_remove(
        array_remove(
          array_remove(template.permission_keys, 'procurement:grn_create'),
          'procurement:grn_confirm'
        ),
        'inventory:production_create'
      ),
      'inventory:production_confirm'
    )
    || ARRAY[
      'inventory:request_create',
      'inventory:request_submit',
      'inventory:request_cancel'
    ]::text[]
  ) AS k
),
updated_at = now()
WHERE template.position_code = 'branch_manager';

-- central roles: transfer_create + request_fulfill
UPDATE public.role_templates AS template
SET permission_keys = (
  SELECT coalesce(array_agg(DISTINCT k ORDER BY k), ARRAY[]::text[])
  FROM unnest(
    template.permission_keys
    || ARRAY[
      'inventory:transfer_create',
      'inventory:request_fulfill'
    ]::text[]
  ) AS k
),
updated_at = now()
WHERE template.position_code IN (
  'central_supply_ops',
  'central_kitchen_lead'
);

-- owner: all request keys (via full catalog sync if system owner template is full)
UPDATE public.role_templates AS template
SET permission_keys = (
  SELECT coalesce(array_agg(DISTINCT k ORDER BY k), ARRAY[]::text[])
  FROM unnest(
    template.permission_keys
    || ARRAY[
      'inventory:request_create',
      'inventory:request_submit',
      'inventory:request_cancel',
      'inventory:request_fulfill'
    ]::text[]
  ) AS k
),
updated_at = now()
WHERE template.position_code = 'owner';

-- Strip live staff_permissions mirroring removed BM keys
DELETE FROM public.staff_permissions AS permission
USING public.profiles AS profile,
      public.positions AS position
WHERE profile.id = permission.user_id
  AND profile.tenant_id = permission.tenant_id
  AND position.id = profile.position_id
  AND position.tenant_id = profile.tenant_id
  AND position.code = 'branch_manager'
  AND permission.permission_key IN (
    'procurement:grn_create',
    'procurement:grn_confirm',
    'inventory:production_create',
    'inventory:production_confirm'
  );
