BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA extensions;

CREATE TABLE public.companies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT companies_code_format_check
    CHECK (code ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$'),
  CONSTRAINT companies_name_nonempty_check
    CHECK (btrim(name) <> '')
);

ALTER TABLE public.tenants
  ADD COLUMN company_id bigint;

ALTER TABLE public.tenants
  ADD CONSTRAINT tenants_company_id_fkey
  FOREIGN KEY (company_id)
  REFERENCES public.companies(id)
  ON DELETE RESTRICT;

ALTER TABLE public.tenants
  ADD CONSTRAINT tenants_id_company_id_key
  UNIQUE (id, company_id);

CREATE TABLE public.operational_sites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL,
  tenant_id bigint NOT NULL,
  kind text NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT operational_sites_tenant_lineage_fkey
    FOREIGN KEY (tenant_id, company_id)
    REFERENCES public.tenants(id, company_id)
    ON DELETE RESTRICT,
  CONSTRAINT operational_sites_kind_check
    CHECK (kind IN ('central_warehouse', 'central_kitchen', 'branch')),
  CONSTRAINT operational_sites_code_format_check
    CHECK (code ~ '^[A-Z0-9]+(?:_[A-Z0-9]+)*$'),
  CONSTRAINT operational_sites_name_nonempty_check
    CHECK (btrim(name) <> ''),
  CONSTRAINT operational_sites_id_tenant_company_key
    UNIQUE (id, tenant_id, company_id),
  CONSTRAINT operational_sites_company_code_key
    UNIQUE (company_id, code)
);

ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operational_sites ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.companies FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.operational_sites FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.companies TO service_role;
GRANT SELECT ON TABLE public.operational_sites TO service_role;

CREATE TABLE private.identity_provisioning_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  idempotency_key uuid NOT NULL UNIQUE,
  request_hash text NOT NULL,
  state text NOT NULL DEFAULT 'pending',
  auth_user_id uuid REFERENCES auth.users(id) ON DELETE RESTRICT,
  company_id bigint REFERENCES public.companies(id) ON DELETE RESTRICT,
  requested_by uuid REFERENCES auth.users(id) ON DELETE RESTRICT,
  failure_category text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT identity_provisioning_request_hash_nonempty_check
    CHECK (btrim(request_hash) <> ''),
  CONSTRAINT identity_provisioning_state_check
    CHECK (state IN ('pending', 'auth_created', 'completed', 'failed')),
  CONSTRAINT identity_provisioning_failure_shape_check
    CHECK (
      (state = 'failed' AND failure_category IS NOT NULL AND btrim(failure_category) <> '')
      OR (state <> 'failed' AND failure_category IS NULL)
    )
);

CREATE TABLE private.company_memberships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  company_id bigint NOT NULL REFERENCES public.companies(id) ON DELETE RESTRICT,
  subject_kind text NOT NULL DEFAULT 'human',
  status text NOT NULL DEFAULT 'active',
  valid_from timestamptz NOT NULL DEFAULT now(),
  valid_until timestamptz,
  ended_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT company_memberships_subject_kind_check
    CHECK (subject_kind IN ('human', 'machine')),
  CONSTRAINT company_memberships_status_check
    CHECK (status IN ('active', 'suspended', 'ended')),
  CONSTRAINT company_memberships_validity_check
    CHECK (valid_until IS NULL OR valid_until > valid_from),
  CONSTRAINT company_memberships_end_shape_check
    CHECK (
      (status = 'active' AND ended_at IS NULL)
      OR (status <> 'active' AND ended_at IS NOT NULL)
    ),
  CONSTRAINT company_memberships_identity_scope_key
    UNIQUE (id, auth_user_id, company_id)
);

CREATE UNIQUE INDEX company_memberships_one_active_idx
  ON private.company_memberships (auth_user_id, company_id)
  WHERE status = 'active' AND ended_at IS NULL;

CREATE TABLE private.tenant_memberships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_membership_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  company_id bigint NOT NULL,
  tenant_id bigint NOT NULL,
  status text NOT NULL DEFAULT 'active',
  valid_from timestamptz NOT NULL DEFAULT now(),
  valid_until timestamptz,
  ended_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tenant_memberships_company_membership_fkey
    FOREIGN KEY (company_membership_id, auth_user_id, company_id)
    REFERENCES private.company_memberships(id, auth_user_id, company_id)
    ON DELETE RESTRICT,
  CONSTRAINT tenant_memberships_tenant_lineage_fkey
    FOREIGN KEY (tenant_id, company_id)
    REFERENCES public.tenants(id, company_id)
    ON DELETE RESTRICT,
  CONSTRAINT tenant_memberships_status_check
    CHECK (status IN ('active', 'suspended', 'ended')),
  CONSTRAINT tenant_memberships_validity_check
    CHECK (valid_until IS NULL OR valid_until > valid_from),
  CONSTRAINT tenant_memberships_end_shape_check
    CHECK (
      (status = 'active' AND ended_at IS NULL)
      OR (status <> 'active' AND ended_at IS NOT NULL)
    ),
  CONSTRAINT tenant_memberships_identity_scope_key
    UNIQUE (id, auth_user_id, company_id, tenant_id)
);

CREATE UNIQUE INDEX tenant_memberships_one_active_idx
  ON private.tenant_memberships (auth_user_id, tenant_id)
  WHERE status = 'active' AND ended_at IS NULL;

CREATE TABLE private.site_assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_membership_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  company_id bigint NOT NULL,
  tenant_id bigint NOT NULL,
  site_id bigint NOT NULL,
  status text NOT NULL DEFAULT 'active',
  valid_from timestamptz NOT NULL DEFAULT now(),
  valid_until timestamptz,
  ended_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT site_assignments_tenant_membership_fkey
    FOREIGN KEY (tenant_membership_id, auth_user_id, company_id, tenant_id)
    REFERENCES private.tenant_memberships(id, auth_user_id, company_id, tenant_id)
    ON DELETE RESTRICT,
  CONSTRAINT site_assignments_site_lineage_fkey
    FOREIGN KEY (site_id, tenant_id, company_id)
    REFERENCES public.operational_sites(id, tenant_id, company_id)
    ON DELETE RESTRICT,
  CONSTRAINT site_assignments_status_check
    CHECK (status IN ('active', 'suspended', 'ended')),
  CONSTRAINT site_assignments_validity_check
    CHECK (valid_until IS NULL OR valid_until > valid_from),
  CONSTRAINT site_assignments_end_shape_check
    CHECK (
      (status = 'active' AND ended_at IS NULL)
      OR (status <> 'active' AND ended_at IS NOT NULL)
    ),
  CONSTRAINT site_assignments_identity_scope_key
    UNIQUE (id, auth_user_id, company_id, tenant_id, site_id)
);

CREATE UNIQUE INDEX site_assignments_one_active_idx
  ON private.site_assignments (auth_user_id, site_id)
  WHERE status = 'active' AND ended_at IS NULL;

CREATE TABLE private.capabilities (
  key text PRIMARY KEY,
  description text NOT NULL,
  required_aal text NOT NULL DEFAULT 'aal1',
  subject_kind text NOT NULL DEFAULT 'human',
  minimum_assignment_class text NOT NULL DEFAULT 'standard',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT capabilities_key_format_check
    CHECK (key ~ '^[a-z][a-z0-9_]*:[a-z][a-z0-9_]*$'),
  CONSTRAINT capabilities_description_nonempty_check
    CHECK (btrim(description) <> ''),
  CONSTRAINT capabilities_required_aal_check
    CHECK (required_aal IN ('aal1', 'aal2')),
  CONSTRAINT capabilities_subject_kind_check
    CHECK (subject_kind IN ('human', 'machine', 'both')),
  CONSTRAINT capabilities_assignment_class_check
    CHECK (minimum_assignment_class IN ('standard', 'privileged', 'machine_only'))
);

CREATE TABLE private.capability_scopes (
  capability_key text NOT NULL,
  scope_kind text NOT NULL,
  PRIMARY KEY (capability_key, scope_kind),
  CONSTRAINT capability_scopes_capability_fkey
    FOREIGN KEY (capability_key)
    REFERENCES private.capabilities(key)
    ON DELETE RESTRICT,
  CONSTRAINT capability_scopes_scope_kind_check
    CHECK (scope_kind IN ('company', 'tenant', 'site'))
);

CREATE TABLE private.access_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL UNIQUE,
  label text NOT NULL,
  scope_kind text NOT NULL,
  assignment_class text NOT NULL DEFAULT 'standard',
  subject_kind text NOT NULL DEFAULT 'human',
  requires_expiry boolean NOT NULL DEFAULT false,
  max_binding_duration interval,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT access_roles_key_format_check
    CHECK (key ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT access_roles_label_nonempty_check
    CHECK (btrim(label) <> ''),
  CONSTRAINT access_roles_scope_kind_check
    CHECK (scope_kind IN ('company', 'tenant', 'site')),
  CONSTRAINT access_roles_assignment_class_check
    CHECK (assignment_class IN ('standard', 'privileged', 'machine_only')),
  CONSTRAINT access_roles_subject_kind_check
    CHECK (subject_kind IN ('human', 'machine')),
  CONSTRAINT access_roles_duration_check
    CHECK (max_binding_duration IS NULL OR max_binding_duration > interval '0 seconds'),
  CONSTRAINT access_roles_expiry_shape_check
    CHECK (NOT requires_expiry OR max_binding_duration IS NOT NULL),
  CONSTRAINT access_roles_id_scope_key
    UNIQUE (id, scope_kind)
);

CREATE TABLE private.access_role_capabilities (
  role_id bigint NOT NULL,
  role_scope_kind text NOT NULL,
  capability_key text NOT NULL,
  capability_scope_kind text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (role_id, capability_key, capability_scope_kind),
  CONSTRAINT access_role_capabilities_role_fkey
    FOREIGN KEY (role_id, role_scope_kind)
    REFERENCES private.access_roles(id, scope_kind)
    ON DELETE RESTRICT,
  CONSTRAINT access_role_capabilities_capability_scope_fkey
    FOREIGN KEY (capability_key, capability_scope_kind)
    REFERENCES private.capability_scopes(capability_key, scope_kind)
    ON DELETE RESTRICT,
  CONSTRAINT access_role_capabilities_scope_match_check
    CHECK (role_scope_kind = capability_scope_kind)
);

CREATE TABLE private.access_bindings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  role_id bigint NOT NULL,
  scope_kind text NOT NULL,
  company_membership_id uuid,
  tenant_membership_id uuid,
  site_assignment_id uuid,
  company_id bigint NOT NULL,
  tenant_id bigint,
  site_id bigint,
  valid_from timestamptz NOT NULL DEFAULT now(),
  valid_until timestamptz,
  revoked_at timestamptz,
  revoked_by uuid REFERENCES auth.users(id) ON DELETE RESTRICT,
  revoke_reason text,
  created_by uuid REFERENCES auth.users(id) ON DELETE RESTRICT,
  create_reason text NOT NULL,
  idempotency_key uuid NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  lifecycle_id uuid GENERATED ALWAYS AS (
    COALESCE(company_membership_id, tenant_membership_id, site_assignment_id)
  ) STORED,
  CONSTRAINT access_bindings_role_scope_fkey
    FOREIGN KEY (role_id, scope_kind)
    REFERENCES private.access_roles(id, scope_kind)
    ON DELETE RESTRICT,
  CONSTRAINT access_bindings_company_membership_fkey
    FOREIGN KEY (company_membership_id, auth_user_id, company_id)
    REFERENCES private.company_memberships(id, auth_user_id, company_id)
    ON DELETE RESTRICT,
  CONSTRAINT access_bindings_tenant_membership_fkey
    FOREIGN KEY (tenant_membership_id, auth_user_id, company_id, tenant_id)
    REFERENCES private.tenant_memberships(id, auth_user_id, company_id, tenant_id)
    ON DELETE RESTRICT,
  CONSTRAINT access_bindings_site_assignment_fkey
    FOREIGN KEY (site_assignment_id, auth_user_id, company_id, tenant_id, site_id)
    REFERENCES private.site_assignments(id, auth_user_id, company_id, tenant_id, site_id)
    ON DELETE RESTRICT,
  CONSTRAINT access_bindings_scope_shape_check
    CHECK (
      (
        scope_kind = 'company'
        AND company_membership_id IS NOT NULL
        AND tenant_membership_id IS NULL
        AND site_assignment_id IS NULL
        AND tenant_id IS NULL
        AND site_id IS NULL
      )
      OR (
        scope_kind = 'tenant'
        AND company_membership_id IS NULL
        AND tenant_membership_id IS NOT NULL
        AND site_assignment_id IS NULL
        AND tenant_id IS NOT NULL
        AND site_id IS NULL
      )
      OR (
        scope_kind = 'site'
        AND company_membership_id IS NULL
        AND tenant_membership_id IS NULL
        AND site_assignment_id IS NOT NULL
        AND tenant_id IS NOT NULL
        AND site_id IS NOT NULL
      )
    ),
  CONSTRAINT access_bindings_validity_check
    CHECK (valid_until IS NULL OR valid_until > valid_from),
  CONSTRAINT access_bindings_create_reason_check
    CHECK (btrim(create_reason) <> ''),
  CONSTRAINT access_bindings_revoke_shape_check
    CHECK (
      (
        revoked_at IS NULL
        AND revoked_by IS NULL
        AND revoke_reason IS NULL
      )
      OR (
        revoked_at IS NOT NULL
        AND revoke_reason IS NOT NULL
        AND btrim(revoke_reason) <> ''
      )
    ),
  CONSTRAINT access_bindings_no_self_grant_check
    CHECK (created_by IS NULL OR created_by <> auth_user_id)
);

ALTER TABLE private.access_bindings
  ADD CONSTRAINT access_bindings_no_overlapping_role
  EXCLUDE USING gist (
    role_id WITH =,
    lifecycle_id WITH =,
    tstzrange(valid_from, COALESCE(valid_until, 'infinity'::timestamptz), '[)') WITH &&
  )
  WHERE (revoked_at IS NULL);

CREATE INDEX access_bindings_company_decision_idx
  ON private.access_bindings (auth_user_id, company_id, role_id)
  WHERE revoked_at IS NULL AND scope_kind = 'company';

CREATE INDEX access_bindings_tenant_decision_idx
  ON private.access_bindings (auth_user_id, tenant_id, role_id)
  WHERE revoked_at IS NULL AND scope_kind = 'tenant';

CREATE INDEX access_bindings_site_decision_idx
  ON private.access_bindings (auth_user_id, site_id, role_id)
  WHERE revoked_at IS NULL AND scope_kind = 'site';

CREATE TABLE private.access_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE RESTRICT,
  target_user_id uuid REFERENCES auth.users(id) ON DELETE RESTRICT,
  event_type text NOT NULL,
  outcome text NOT NULL,
  binding_id uuid REFERENCES private.access_bindings(id) ON DELETE RESTRICT,
  company_id bigint REFERENCES public.companies(id) ON DELETE RESTRICT,
  tenant_id bigint,
  site_id bigint,
  reason text NOT NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT access_audit_event_type_nonempty_check
    CHECK (btrim(event_type) <> ''),
  CONSTRAINT access_audit_outcome_check
    CHECK (outcome IN ('allowed', 'denied', 'noop')),
  CONSTRAINT access_audit_reason_nonempty_check
    CHECK (btrim(reason) <> ''),
  CONSTRAINT access_audit_request_event_key
    UNIQUE (request_id, event_type)
);

CREATE TABLE private.access_bootstrap_state (
  company_id bigint PRIMARY KEY REFERENCES public.companies(id) ON DELETE RESTRICT,
  completed_at timestamptz NOT NULL,
  completed_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  audit_id bigint NOT NULL UNIQUE REFERENCES private.access_audit_log(id) ON DELETE RESTRICT
);

CREATE OR REPLACE FUNCTION private.assignment_class_rank(p_class text)
RETURNS integer
LANGUAGE sql
IMMUTABLE
STRICT
SET search_path = ''
AS $$
  SELECT CASE p_class
    WHEN 'standard' THEN 1
    WHEN 'privileged' THEN 2
    WHEN 'machine_only' THEN 3
    ELSE 0
  END;
$$;

CREATE OR REPLACE FUNCTION private.validate_access_role_capability()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_role private.access_roles%ROWTYPE;
  v_capability private.capabilities%ROWTYPE;
BEGIN
  SELECT *
  INTO STRICT v_role
  FROM private.access_roles
  WHERE id = NEW.role_id;

  SELECT *
  INTO STRICT v_capability
  FROM private.capabilities
  WHERE key = NEW.capability_key;

  IF v_role.subject_kind <> v_capability.subject_kind
     AND v_capability.subject_kind <> 'both' THEN
    RAISE EXCEPTION 'role subject kind does not match capability subject kind'
      USING ERRCODE = '23514';
  END IF;

  IF v_role.assignment_class = 'machine_only'
     AND v_capability.minimum_assignment_class <> 'machine_only' THEN
    RAISE EXCEPTION 'machine-only roles may contain only machine capabilities'
      USING ERRCODE = '23514';
  END IF;

  IF v_role.assignment_class <> 'machine_only'
     AND v_capability.minimum_assignment_class = 'machine_only' THEN
    RAISE EXCEPTION 'human roles may not contain machine capabilities'
      USING ERRCODE = '23514';
  END IF;

  IF v_role.assignment_class <> 'machine_only'
     AND private.assignment_class_rank(v_role.assignment_class)
       < private.assignment_class_rank(v_capability.minimum_assignment_class) THEN
    RAISE EXCEPTION 'role assignment class is below capability minimum'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER access_role_capabilities_validate
BEFORE INSERT OR UPDATE ON private.access_role_capabilities
FOR EACH ROW EXECUTE FUNCTION private.validate_access_role_capability();

CREATE OR REPLACE FUNCTION private.validate_access_binding()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_role private.access_roles%ROWTYPE;
  v_subject_kind text;
BEGIN
  SELECT *
  INTO STRICT v_role
  FROM private.access_roles
  WHERE id = NEW.role_id
    AND scope_kind = NEW.scope_kind
    AND is_active;

  IF v_role.requires_expiry AND NEW.valid_until IS NULL THEN
    RAISE EXCEPTION 'role binding requires an expiry'
      USING ERRCODE = '23514';
  END IF;

  IF v_role.max_binding_duration IS NOT NULL
     AND (
       NEW.valid_until IS NULL
       OR NEW.valid_until - NEW.valid_from > v_role.max_binding_duration
     ) THEN
    RAISE EXCEPTION 'role binding exceeds maximum duration'
      USING ERRCODE = '23514';
  END IF;

  SELECT subject_kind
  INTO STRICT v_subject_kind
  FROM private.company_memberships
  WHERE auth_user_id = NEW.auth_user_id
    AND company_id = NEW.company_id
    AND (
      id = NEW.company_membership_id
      OR id = (
        SELECT company_membership_id
        FROM private.tenant_memberships
        WHERE id = NEW.tenant_membership_id
      )
      OR id = (
        SELECT tm.company_membership_id
        FROM private.site_assignments sa
        JOIN private.tenant_memberships tm
          ON tm.id = sa.tenant_membership_id
        WHERE sa.id = NEW.site_assignment_id
      )
    );

  IF v_subject_kind <> v_role.subject_kind THEN
    RAISE EXCEPTION 'role subject kind does not match membership subject kind'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER access_bindings_validate
BEFORE INSERT OR UPDATE OF
  role_id,
  scope_kind,
  company_membership_id,
  tenant_membership_id,
  site_assignment_id,
  company_id,
  tenant_id,
  site_id,
  valid_from,
  valid_until
ON private.access_bindings
FOR EACH ROW EXECUTE FUNCTION private.validate_access_binding();

CREATE OR REPLACE FUNCTION private.guard_lifecycle_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  IF OLD.status <> 'active' THEN
    RAISE EXCEPTION 'closed lifecycle rows are immutable'
      USING ERRCODE = '23514';
  END IF;

  IF NEW.status = 'active' OR NEW.ended_at IS NULL THEN
    RAISE EXCEPTION 'lifecycle rows may only transition out of active'
      USING ERRCODE = '23514';
  END IF;

  IF (to_jsonb(NEW) - ARRAY['status', 'ended_at', 'updated_at'])
     IS DISTINCT FROM
     (to_jsonb(OLD) - ARRAY['status', 'ended_at', 'updated_at']) THEN
    RAISE EXCEPTION 'lifecycle identity and scope are immutable'
      USING ERRCODE = '23514';
  END IF;

  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER company_memberships_guard_update
BEFORE UPDATE ON private.company_memberships
FOR EACH ROW EXECUTE FUNCTION private.guard_lifecycle_update();

CREATE TRIGGER tenant_memberships_guard_update
BEFORE UPDATE ON private.tenant_memberships
FOR EACH ROW EXECUTE FUNCTION private.guard_lifecycle_update();

CREATE TRIGGER site_assignments_guard_update
BEFORE UPDATE ON private.site_assignments
FOR EACH ROW EXECUTE FUNCTION private.guard_lifecycle_update();

CREATE OR REPLACE FUNCTION private.guard_access_binding_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  IF OLD.revoked_at IS NOT NULL THEN
    RAISE EXCEPTION 'revoked bindings are immutable'
      USING ERRCODE = '23514';
  END IF;

  IF (to_jsonb(NEW) - ARRAY[
        'valid_until',
        'revoked_at',
        'revoked_by',
        'revoke_reason',
        'updated_at'
      ])
     IS DISTINCT FROM
     (to_jsonb(OLD) - ARRAY[
        'valid_until',
        'revoked_at',
        'revoked_by',
        'revoke_reason',
        'updated_at'
      ]) THEN
    RAISE EXCEPTION 'binding identity, role, and scope are immutable'
      USING ERRCODE = '23514';
  END IF;

  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER access_bindings_guard_update
BEFORE UPDATE ON private.access_bindings
FOR EACH ROW EXECUTE FUNCTION private.guard_access_binding_update();

CREATE OR REPLACE FUNCTION private.prevent_access_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  RAISE EXCEPTION 'access audit rows are append-only'
    USING ERRCODE = '23514';
END;
$$;

CREATE TRIGGER access_audit_log_append_only
BEFORE UPDATE OR DELETE ON private.access_audit_log
FOR EACH ROW EXECUTE FUNCTION private.prevent_access_audit_mutation();

INSERT INTO private.capabilities (
  key,
  description,
  required_aal,
  subject_kind,
  minimum_assignment_class
)
VALUES
  ('access:manage_bindings', 'Manage human access bindings', 'aal2', 'human', 'privileged'),
  ('branch:workspace_enter', 'Enter an assigned Branch workspace', 'aal1', 'human', 'standard'),
  ('catalog:read', 'Read the Tenant catalog', 'aal1', 'human', 'standard'),
  ('company:dashboard_view', 'View the Company control room', 'aal1', 'human', 'standard'),
  ('finance:consolidated_read', 'Read consolidated Tenant finance', 'aal2', 'human', 'privileged'),
  ('sites:oversee', 'Oversee operational sites in a Tenant', 'aal1', 'human', 'privileged'),
  ('workforce:assign_site', 'Create or end site assignments', 'aal2', 'human', 'privileged'),
  ('workforce:read', 'Read Company workforce records', 'aal1', 'human', 'standard'),
  ('workforce:self_read', 'Read the caller workforce record', 'aal1', 'human', 'standard');

INSERT INTO private.capability_scopes (capability_key, scope_kind)
VALUES
  ('access:manage_bindings', 'company'),
  ('branch:workspace_enter', 'site'),
  ('catalog:read', 'tenant'),
  ('company:dashboard_view', 'company'),
  ('finance:consolidated_read', 'tenant'),
  ('sites:oversee', 'tenant'),
  ('workforce:assign_site', 'company'),
  ('workforce:read', 'company'),
  ('workforce:self_read', 'company');

INSERT INTO private.access_roles (
  key,
  label,
  scope_kind,
  assignment_class,
  subject_kind,
  requires_expiry,
  max_binding_duration
)
VALUES
  ('branch_operator', 'Branch Operator', 'site', 'standard', 'human', false, NULL),
  ('company_admin', 'Company Admin', 'company', 'privileged', 'human', false, NULL),
  ('office_member', 'Office Member', 'company', 'standard', 'human', false, NULL),
  ('security_admin', 'Security Admin', 'company', 'privileged', 'human', false, NULL),
  ('tenant_observer', 'Tenant Observer', 'tenant', 'standard', 'human', false, NULL);

INSERT INTO private.access_role_capabilities (
  role_id,
  role_scope_kind,
  capability_key,
  capability_scope_kind
)
SELECT
  role.id,
  role.scope_kind,
  mapping.capability_key,
  mapping.scope_kind
FROM (
  VALUES
    ('branch_operator', 'branch:workspace_enter', 'site'),
    ('company_admin', 'company:dashboard_view', 'company'),
    ('company_admin', 'workforce:assign_site', 'company'),
    ('company_admin', 'workforce:read', 'company'),
    ('company_admin', 'workforce:self_read', 'company'),
    ('office_member', 'company:dashboard_view', 'company'),
    ('office_member', 'workforce:self_read', 'company'),
    ('security_admin', 'access:manage_bindings', 'company'),
    ('security_admin', 'company:dashboard_view', 'company'),
    ('security_admin', 'workforce:self_read', 'company'),
    ('tenant_observer', 'catalog:read', 'tenant')
) AS mapping(role_key, capability_key, scope_kind)
JOIN private.access_roles role
  ON role.key = mapping.role_key;

CREATE OR REPLACE FUNCTION private.can_company(
  p_capability text,
  p_company_id bigint
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.companies company
    JOIN private.company_memberships membership
      ON membership.company_id = company.id
    JOIN private.access_bindings binding
      ON binding.company_membership_id = membership.id
     AND binding.auth_user_id = membership.auth_user_id
     AND binding.company_id = membership.company_id
     AND binding.scope_kind = 'company'
    JOIN private.access_roles role
      ON role.id = binding.role_id
     AND role.scope_kind = binding.scope_kind
     AND role.subject_kind = membership.subject_kind
    JOIN private.access_role_capabilities role_capability
      ON role_capability.role_id = role.id
     AND role_capability.role_scope_kind = role.scope_kind
    JOIN private.capabilities capability
      ON capability.key = role_capability.capability_key
    WHERE company.id = p_company_id
      AND company.is_active
      AND membership.auth_user_id = auth.uid()
      AND membership.status = 'active'
      AND membership.valid_from <= now()
      AND (membership.valid_until IS NULL OR membership.valid_until > now())
      AND binding.revoked_at IS NULL
      AND binding.valid_from <= now()
      AND (binding.valid_until IS NULL OR binding.valid_until > now())
      AND role.is_active
      AND capability.key = p_capability
      AND capability.is_active
      AND role_capability.capability_scope_kind = 'company'
      AND (
        capability.required_aal = 'aal1'
        OR auth.jwt() ->> 'aal' = 'aal2'
      )
  );
$$;

CREATE OR REPLACE FUNCTION private.can_tenant(
  p_capability text,
  p_tenant_id bigint
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.tenants tenant
    JOIN public.companies company
      ON company.id = tenant.company_id
    JOIN private.company_memberships company_membership
      ON company_membership.company_id = company.id
    JOIN private.tenant_memberships tenant_membership
      ON tenant_membership.company_membership_id = company_membership.id
     AND tenant_membership.auth_user_id = company_membership.auth_user_id
     AND tenant_membership.company_id = company_membership.company_id
     AND tenant_membership.tenant_id = tenant.id
    JOIN private.access_bindings binding
      ON binding.tenant_membership_id = tenant_membership.id
     AND binding.auth_user_id = tenant_membership.auth_user_id
     AND binding.company_id = tenant_membership.company_id
     AND binding.tenant_id = tenant_membership.tenant_id
     AND binding.scope_kind = 'tenant'
    JOIN private.access_roles role
      ON role.id = binding.role_id
     AND role.scope_kind = binding.scope_kind
     AND role.subject_kind = company_membership.subject_kind
    JOIN private.access_role_capabilities role_capability
      ON role_capability.role_id = role.id
     AND role_capability.role_scope_kind = role.scope_kind
    JOIN private.capabilities capability
      ON capability.key = role_capability.capability_key
    WHERE tenant.id = p_tenant_id
      AND company.is_active
      AND company_membership.auth_user_id = auth.uid()
      AND company_membership.status = 'active'
      AND company_membership.valid_from <= now()
      AND (
        company_membership.valid_until IS NULL
        OR company_membership.valid_until > now()
      )
      AND tenant_membership.status = 'active'
      AND tenant_membership.valid_from <= now()
      AND (
        tenant_membership.valid_until IS NULL
        OR tenant_membership.valid_until > now()
      )
      AND binding.revoked_at IS NULL
      AND binding.valid_from <= now()
      AND (binding.valid_until IS NULL OR binding.valid_until > now())
      AND role.is_active
      AND capability.key = p_capability
      AND capability.is_active
      AND role_capability.capability_scope_kind = 'tenant'
      AND (
        capability.required_aal = 'aal1'
        OR auth.jwt() ->> 'aal' = 'aal2'
      )
  );
$$;

CREATE OR REPLACE FUNCTION private.can_site(
  p_capability text,
  p_site_id bigint
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.operational_sites site
    JOIN public.tenants tenant
      ON tenant.id = site.tenant_id
     AND tenant.company_id = site.company_id
    JOIN public.companies company
      ON company.id = site.company_id
    JOIN private.company_memberships company_membership
      ON company_membership.company_id = company.id
    JOIN private.tenant_memberships tenant_membership
      ON tenant_membership.company_membership_id = company_membership.id
     AND tenant_membership.auth_user_id = company_membership.auth_user_id
     AND tenant_membership.company_id = company_membership.company_id
     AND tenant_membership.tenant_id = tenant.id
    JOIN private.site_assignments site_assignment
      ON site_assignment.tenant_membership_id = tenant_membership.id
     AND site_assignment.auth_user_id = tenant_membership.auth_user_id
     AND site_assignment.company_id = tenant_membership.company_id
     AND site_assignment.tenant_id = tenant_membership.tenant_id
     AND site_assignment.site_id = site.id
    JOIN private.access_bindings binding
      ON binding.site_assignment_id = site_assignment.id
     AND binding.auth_user_id = site_assignment.auth_user_id
     AND binding.company_id = site_assignment.company_id
     AND binding.tenant_id = site_assignment.tenant_id
     AND binding.site_id = site_assignment.site_id
     AND binding.scope_kind = 'site'
    JOIN private.access_roles role
      ON role.id = binding.role_id
     AND role.scope_kind = binding.scope_kind
     AND role.subject_kind = company_membership.subject_kind
    JOIN private.access_role_capabilities role_capability
      ON role_capability.role_id = role.id
     AND role_capability.role_scope_kind = role.scope_kind
    JOIN private.capabilities capability
      ON capability.key = role_capability.capability_key
    WHERE site.id = p_site_id
      AND site.is_active
      AND company.is_active
      AND company_membership.auth_user_id = auth.uid()
      AND company_membership.status = 'active'
      AND company_membership.valid_from <= now()
      AND (
        company_membership.valid_until IS NULL
        OR company_membership.valid_until > now()
      )
      AND tenant_membership.status = 'active'
      AND tenant_membership.valid_from <= now()
      AND (
        tenant_membership.valid_until IS NULL
        OR tenant_membership.valid_until > now()
      )
      AND site_assignment.status = 'active'
      AND site_assignment.valid_from <= now()
      AND (
        site_assignment.valid_until IS NULL
        OR site_assignment.valid_until > now()
      )
      AND binding.revoked_at IS NULL
      AND binding.valid_from <= now()
      AND (binding.valid_until IS NULL OR binding.valid_until > now())
      AND role.is_active
      AND capability.key = p_capability
      AND capability.is_active
      AND role_capability.capability_scope_kind = 'site'
      AND (
        capability.required_aal = 'aal1'
        OR auth.jwt() ->> 'aal' = 'aal2'
      )
  );
$$;

ALTER TABLE private.identity_provisioning_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.company_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.tenant_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.site_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.capabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.capability_scopes ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.access_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.access_role_capabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.access_bindings ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.access_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.access_bootstrap_state ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA private TO authenticated, service_role;

REVOKE ALL ON TABLE private.identity_provisioning_requests FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.company_memberships FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.tenant_memberships FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.site_assignments FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.capabilities FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.capability_scopes FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.access_roles FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.access_role_capabilities FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.access_bindings FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.access_audit_log FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.access_bootstrap_state FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE private.identity_provisioning_requests TO service_role;
GRANT SELECT ON TABLE private.company_memberships TO service_role;
GRANT SELECT ON TABLE private.tenant_memberships TO service_role;
GRANT SELECT ON TABLE private.site_assignments TO service_role;
GRANT SELECT ON TABLE private.capabilities TO service_role;
GRANT SELECT ON TABLE private.capability_scopes TO service_role;
GRANT SELECT ON TABLE private.access_roles TO service_role;
GRANT SELECT ON TABLE private.access_role_capabilities TO service_role;
GRANT SELECT ON TABLE private.access_bindings TO service_role;
GRANT SELECT ON TABLE private.access_audit_log TO service_role;
GRANT SELECT ON TABLE private.access_bootstrap_state TO service_role;

REVOKE ALL ON FUNCTION private.assignment_class_rank(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.validate_access_role_capability() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.validate_access_binding() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.guard_lifecycle_update() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.guard_access_binding_update() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.prevent_access_audit_mutation() FROM PUBLIC, anon, authenticated;

REVOKE ALL ON FUNCTION private.can_company(text, bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION private.can_tenant(text, bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION private.can_site(text, bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION private.can_company(text, bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION private.can_tenant(text, bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION private.can_site(text, bigint) TO authenticated, service_role;

COMMIT;
