REVOKE ALL ON FUNCTION public.get_inventory_valuation_reconciliation(integer, integer, bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_inventory_valuation_reconciliation(integer, integer, bigint) TO authenticated, service_role;
CREATE INDEX IF NOT EXISTS inventory_cost_close_snapshots_closed_by_idx ON public.inventory_cost_close_snapshots (closed_by);
CREATE INDEX IF NOT EXISTS inventory_cost_origins_grn_item_idx ON public.inventory_cost_origins (grn_item_id) WHERE grn_item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_cost_origins_ingredient_tenant_idx ON public.inventory_cost_origins (ingredient_id, tenant_id);
CREATE INDEX IF NOT EXISTS inventory_origin_balances_origin_tenant_idx ON public.inventory_origin_balances (origin_id, tenant_id);
CREATE INDEX IF NOT EXISTS inventory_origin_balances_account_tenant_idx ON public.inventory_origin_balances (valuation_account_id, tenant_id) WHERE valuation_account_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_valuation_accounts_branch_tenant_idx ON public.inventory_valuation_accounts (branch_id, tenant_id);
CREATE INDEX IF NOT EXISTS inventory_valuation_accounts_location_tenant_idx ON public.inventory_valuation_accounts (location_id, tenant_id);
CREATE INDEX IF NOT EXISTS inventory_valuation_accounts_ingredient_tenant_idx ON public.inventory_valuation_accounts (ingredient_id, tenant_id);
CREATE INDEX IF NOT EXISTS inventory_valuation_cutovers_prepared_by_idx ON public.inventory_valuation_cutovers (prepared_by) WHERE prepared_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_valuation_cutovers_activated_by_idx ON public.inventory_valuation_cutovers (activated_by) WHERE activated_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_valuation_events_created_by_idx ON public.inventory_valuation_events (created_by) WHERE created_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_valuation_events_from_account_tenant_idx ON public.inventory_valuation_events (from_account_id, tenant_id) WHERE from_account_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_valuation_events_to_account_tenant_idx ON public.inventory_valuation_events (to_account_id, tenant_id) WHERE to_account_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_valuation_events_grn_item_idx ON public.inventory_valuation_events (grn_item_id) WHERE grn_item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_valuation_events_ingredient_tenant_idx ON public.inventory_valuation_events (ingredient_id, tenant_id);
CREATE INDEX IF NOT EXISTS inventory_valuation_events_reversal_idx ON public.inventory_valuation_events (reversal_of_event_id) WHERE reversal_of_event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_valuation_events_invoice_idx ON public.inventory_valuation_events (source_invoice_id) WHERE source_invoice_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_valuation_events_invoice_line_idx ON public.inventory_valuation_events (source_invoice_line_id) WHERE source_invoice_line_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_valuation_events_movement_idx ON public.inventory_valuation_events (stock_movement_id) WHERE stock_movement_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_value_allocations_event_tenant_idx ON public.inventory_value_allocations (valuation_event_id, tenant_id);
CREATE INDEX IF NOT EXISTS inventory_value_allocations_source_origin_tenant_idx ON public.inventory_value_allocations (source_origin_id, tenant_id);
CREATE INDEX IF NOT EXISTS inventory_value_allocations_derived_origin_tenant_idx ON public.inventory_value_allocations (derived_origin_id, tenant_id) WHERE derived_origin_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_value_allocations_from_balance_tenant_idx ON public.inventory_value_allocations (from_balance_id, tenant_id) WHERE from_balance_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_value_allocations_to_balance_tenant_idx ON public.inventory_value_allocations (to_balance_id, tenant_id) WHERE to_balance_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS supplier_invoice_receipt_allocations_valuation_event_idx ON public.supplier_invoice_receipt_allocations (valuation_event_id) WHERE valuation_event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS stock_movements_grn_item_idx ON public.stock_movements (grn_item_id) WHERE grn_item_id IS NOT NULL;
