// Regenerates src/fonts-data.ts from assets/fonts/*.ttf. Embedding makes the
// package self-contained for esbuild bundles (print-agent) and Next.js server
// actions (no file tracing of font assets needed).
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const font = (name) =>
  readFileSync(path.join(root, "assets/fonts", name)).toString("base64");

const out = `// Generated by scripts/embed-fonts.mjs — do not edit by hand.
// Source TTFs live in assets/fonts/.
export const ROBOTO_MONO_REGULAR_B64 =
  "${font("RobotoMono-Regular.ttf")}";
export const ROBOTO_MONO_BOLD_B64 =
  "${font("RobotoMono-Bold.ttf")}";
`;

writeFileSync(path.join(root, "src/fonts-data.ts"), out);
console.log("fonts-data.ts regenerated");
