-- =========================================================================
-- feedback module — Slice 1: core tables + category validator function
--
-- Tables:
--   feedback_qr_codes    — QR tokens linked to branch/table
--   feedbacks            — customer feedback submissions
--   telegram_destinations — Telegram chat targets for alerts
--   telegram_outbox       — outbound alert queue (status machine)
--
-- Function:
--   feedback_validate_categories(text[]) — IMMUTABLE category taxonomy check
--
-- RLS + GRANT/REVOKE live in 20260511010000_feedback_rls_policies.sql
-- Masked phone view lives in  20260511020000_feedback_masked_phone_view.sql
-- submit_feedback RPC lives in 20260511030000_submit_feedback_rpc.sql
-- Permission keys seeded in   20260511040000_feedback_permission_keys.sql
-- =========================================================================

-- ─── 1. feedback_validate_categories ────────────────────────────────────
--
-- Validates that every element in the supplied array belongs to the
-- fixed taxonomy. Used as a CHECK constraint on feedbacks.ai_categories.
-- IMMUTABLE so Postgres can inline/cache the check cheaply.

CREATE OR REPLACE FUNCTION public.feedback_validate_categories(p_cats TEXT[])
RETURNS BOOLEAN
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  valid_cats CONSTANT TEXT[] := ARRAY[
    'food.quality.cold',
    'food.quality.raw',
    'food.quality.spoiled',
    'food.quality.taste',
    'food.quality.portion',
    'service.slow',
    'service.attitude',
    'service.wrong_order',
    'service.missing_item',
    'hygiene.dirty_table',
    'hygiene.bug',
    'hygiene.smell',
    'hygiene.toilet',
    'pricing.overcharged',
    'pricing.unclear',
    'ambience.noise',
    'ambience.crowded',
    'ambience.aircon',
    'ambience.parking',
    'praise.food',
    'praise.service',
    'praise.value',
    'suggestion.menu',
    'suggestion.facility',
    'other'
  ];
  v_cat TEXT;
BEGIN
  IF p_cats IS NULL THEN
    RETURN TRUE;
  END IF;
  FOREACH v_cat IN ARRAY p_cats LOOP
    IF NOT (v_cat = ANY(valid_cats)) THEN
      RETURN FALSE;
    END IF;
  END LOOP;
  RETURN TRUE;
END;
$$;

COMMENT ON FUNCTION public.feedback_validate_categories(TEXT[]) IS
  'Returns TRUE iff every element is a member of the fixed feedback category taxonomy. Used in feedbacks.ai_categories CHECK constraint.';

-- ─── 2. feedback_qr_codes ───────────────────────────────────────────────
--
-- One row per QR code token. table_id = NULL means a branch-wide QR
-- (e.g. printed at entrance). token is exactly 14 chars (URL-safe random).
-- label auto-generated by app layer (e.g. "Bàn 5 - CN Q1", "Cổng vào").

CREATE TABLE public.feedback_qr_codes (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id   BIGINT NOT NULL,
  branch_id   BIGINT NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
  table_id    BIGINT NULL REFERENCES public.tables(id) ON DELETE SET NULL,
  token       TEXT NOT NULL UNIQUE,
  label       TEXT NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_by  BIGINT NULL,   -- profiles numeric id who created (audit trail)
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  rotated_at  TIMESTAMPTZ NULL,

  CONSTRAINT feedback_qr_codes_token_chk CHECK (length(token) = 14),
  CONSTRAINT feedback_qr_codes_label_chk CHECK (length(label) BETWEEN 1 AND 200)
);

CREATE INDEX idx_fqr_tenant_branch_active
  ON public.feedback_qr_codes (tenant_id, branch_id, is_active);

CREATE INDEX idx_fqr_tenant_branch_table
  ON public.feedback_qr_codes (tenant_id, branch_id, table_id);

COMMENT ON TABLE public.feedback_qr_codes IS
  'QR code tokens for customer feedback. table_id NULL = branch-wide QR. token must be exactly 14 chars.';

-- ─── 3. feedbacks ───────────────────────────────────────────────────────
--
-- Core feedback row. Insert is RPC-only (submit_feedback SECURITY DEFINER).
-- Direct INSERT from authenticated is revoked in the RLS migration.
-- AI columns are NULL in Slice 1 and filled by Slice 2 background processor.
-- phone stored raw (never logged); SELECT via feedbacks_with_masked_phone view.

CREATE TABLE public.feedbacks (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id   BIGINT NOT NULL,
  branch_id   BIGINT NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
  table_id    BIGINT NULL REFERENCES public.tables(id) ON DELETE SET NULL,
  qr_code_id  BIGINT NOT NULL REFERENCES public.feedback_qr_codes(id),

  -- core review
  rating      SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     TEXT     NOT NULL CHECK (length(comment) >= 10 AND length(comment) <= 2000),
  photo_paths TEXT[]   NOT NULL DEFAULT '{}',
  phone       TEXT     NULL CHECK (phone IS NULL OR phone ~ '^\+?\d{8,15}$'),
  channel     TEXT     NOT NULL DEFAULT 'qr_scan'
                CHECK (channel IN ('qr_scan', 'manual')),

  -- best-effort order context snapshot (no FK enforcement — orders may be closed/deleted)
  order_id_snapshot      BIGINT         NULL REFERENCES public.orders(id) ON DELETE SET NULL,
  order_total_snapshot   NUMERIC(15,2)  NULL,
  dish_names_snapshot    TEXT[]         NULL,
  -- orders.created_by is UUID; we store the numeric profile id for display convenience
  server_user_id_snapshot BIGINT        NULL,

  -- submission metadata
  submit_ip_hash      TEXT NULL,
  user_agent_short    TEXT NULL CHECK (user_agent_short IS NULL OR length(user_agent_short) <= 200),
  is_suspect          BOOLEAN NOT NULL DEFAULT FALSE,
  alert_sent_telegram_at TIMESTAMPTZ NULL,
  alert_priority      SMALLINT NOT NULL DEFAULT 0,  -- 0=normal, 10=critical (Slice 2)

  -- AI enrichment — all NULL in Slice 1, populated by Slice 2 background job
  ai_processed_at     TIMESTAMPTZ NULL,
  ai_categories       TEXT[]      NULL CHECK (ai_categories IS NULL OR public.feedback_validate_categories(ai_categories)),
  ai_severity         TEXT        NULL CHECK (ai_severity IS NULL OR ai_severity IN ('low','medium','high','critical')),
  ai_summary_vi       TEXT        NULL CHECK (ai_summary_vi IS NULL OR length(ai_summary_vi) <= 1000),
  ai_sentiment_score  NUMERIC(3,2) NULL CHECK (ai_sentiment_score IS NULL OR ai_sentiment_score BETWEEN -1 AND 1),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_feedbacks_tenant_branch_created
  ON public.feedbacks (tenant_id, branch_id, created_at DESC);

-- Partial index — only rows with AI severity processed
CREATE INDEX idx_feedbacks_branch_severity
  ON public.feedbacks (branch_id, ai_severity)
  WHERE ai_severity IS NOT NULL;

CREATE INDEX idx_feedbacks_qr_code
  ON public.feedbacks (qr_code_id);

COMMENT ON TABLE public.feedbacks IS
  'Customer feedback submissions. INSERT is RPC-only via submit_feedback(). Direct authenticated INSERT is revoked. AI columns populated by Slice 2 processor.';
COMMENT ON COLUMN public.feedbacks.phone IS
  'Raw phone number — NEVER expose directly. Always query via feedbacks_with_masked_phone view.';
COMMENT ON COLUMN public.feedbacks.submit_ip_hash IS
  'SHA-256 hash of submitter IP. Raw IP is never stored per privacy policy.';
COMMENT ON COLUMN public.feedbacks.alert_priority IS
  '0=normal, 10=critical. Slice 2 sets 10 when rating=1 + critical ai_severity.';

-- ─── 4. telegram_destinations ───────────────────────────────────────────
--
-- Telegram chat targets for negative-feedback alerts.
-- branch_id NULL = HQ-level destination (receives all branch alerts for tenant).
-- Uniqueness: one chat_id per (tenant, branch_or_hq) combination.
-- Using partial unique indexes instead of COALESCE in UNIQUE constraint
-- because some Postgres versions handle COALESCE in UNIQUE inconsistently.

CREATE TABLE public.telegram_destinations (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id   BIGINT NOT NULL,
  branch_id   BIGINT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
  chat_id     TEXT NOT NULL CHECK (length(chat_id) BETWEEN 1 AND 64),
  label       TEXT NOT NULL CHECK (length(label) BETWEEN 1 AND 100),
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_by  BIGINT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique: one chat_id per branch (branch-level destinations)
CREATE UNIQUE INDEX uidx_telegram_dest_branch
  ON public.telegram_destinations (tenant_id, branch_id, chat_id)
  WHERE branch_id IS NOT NULL;

-- Unique: one chat_id per tenant HQ (branch_id IS NULL)
CREATE UNIQUE INDEX uidx_telegram_dest_hq
  ON public.telegram_destinations (tenant_id, chat_id)
  WHERE branch_id IS NULL;

COMMENT ON TABLE public.telegram_destinations IS
  'Telegram chat targets for feedback alerts. branch_id NULL = HQ-level (receives all branch alerts).';

-- ─── 5. telegram_outbox ─────────────────────────────────────────────────
--
-- Outbound alert queue. One row per feedback (UNIQUE feedback_id prevents
-- double-queue races). Status machine: pending → sent | failed → dead.
-- Worker reads (status='pending' AND next_retry_at <= NOW()), increments
-- attempts, sends Telegram, updates status.

CREATE TABLE public.telegram_outbox (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  feedback_id   BIGINT NOT NULL UNIQUE REFERENCES public.feedbacks(id) ON DELETE CASCADE,
  status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'sent', 'failed', 'dead')),
  attempts      SMALLINT NOT NULL DEFAULT 0
                  CHECK (attempts >= 0 AND attempts <= 10),
  last_error    TEXT NULL,
  next_retry_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at       TIMESTAMPTZ NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Partial index for the worker hot-path query
CREATE INDEX idx_telegram_outbox_work_queue
  ON public.telegram_outbox (status, next_retry_at)
  WHERE status IN ('pending', 'failed');

CREATE INDEX idx_telegram_outbox_feedback
  ON public.telegram_outbox (feedback_id);

COMMENT ON TABLE public.telegram_outbox IS
  'Outbound Telegram alert queue. INSERT is RPC-only (submit_feedback inserts when rating <= 3). Worker polls (status IN (pending,failed) AND next_retry_at <= now()).';
