export type { ModuleLabelKey, SiteKind } from "./vi";
export { LEGAL_FIXED_VI, RECEIPT_INVARIANT_VI } from "./legal-fixed";
export type { LegalFixedString, ReceiptInvariantString } from "./legal-fixed";
export {
  APP_COPY_VI,
  ACTIVE_STATE_LABELS_VI,
  INVENTORY_SITE_KIND_LABELS_VI,
  MODULE_LABELS_VI,
  NAV_GROUP_LABELS_VI,
  SITE_KIND_LABELS_VI,
  getModuleLabelVi,
  getInventorySiteKindLabelVi,
  getInventorySiteLabelVi,
  getSiteKindLabelVi,
  getSiteLabelVi,
  resolveSiteKind,
  // Inventory redesign vocab (S10-S15 UI wiring)
  VARIANCE_TIER_LABELS_VI,
  VARIANCE_TIER_HINT_VI,
  BASELINE_SOURCE_LABELS_VI,
  WASTE_TIER_LABELS_VI,
  WASTE_REASON_LABELS_VI,
  APPROVAL_STATUS_LABELS_VI,
  STOCKTAKE_MODE_LABELS_VI,
  STOCKTAKE_STATUS_LABELS_VI,
  SHIFT_SEGMENT_LABELS_VI,
  ABC_CLASS_LABELS_VI,
  CONFLICT_RESOLUTION_LABELS_VI,
  CONFLICT_TYPE_LABELS_VI,
  HARDBLOCK_REASON_LABELS_VI,
  AUTO_APPROVE_CONDITION_LABELS_VI,
  AUTO_APPROVE_FAIL_REASON_VI,
  INVENTORY_ERROR_LABELS_VI,
  getVarianceTierLabelVi,
  getWasteReasonLabelVi,
  getStocktakeModeLabelVi,
  PAYMENT_METHOD_LABELS_VI,
  PAYMENT_METHOD_LABELS_FULL_VI,
  getPaymentMethodLabelVi,
} from "./vi";
