// ================================================================
// MOCK DATA — Cơm Tấm Má Tư · Inventory Demo
// ================================================================

export const branches = [
  { id: 1, name: "Trụ sở chính", short: "HQ", isHQ: true },
  { id: 2, name: "Chi nhánh Quận 1", short: "Q1", isHQ: false },
  { id: 3, name: "Chi nhánh Quận 3", short: "Q3", isHQ: false },
  { id: 4, name: "Chi nhánh Bình Thạnh", short: "BT", isHQ: false },
  { id: 5, name: "Chi nhánh Thủ Đức", short: "TĐ", isHQ: false },
] as const;

export type IngredientStatus = "normal" | "low" | "out" | "over";
export type DocumentStatus =
  | "draft"
  | "confirmed"
  | "sent"
  | "in_transit"
  | "received"
  | "completed"
  | "cancelled"
  | "pending"
  | "in_progress"
  | "matched"
  | "discrepancy"
  | "approved"
  | "overdue";

export const ingredients = [
  {
    id: 1,
    name: "Gạo tấm Đặc biệt",
    sku: "GRA-001",
    unit: "Kg",
    category: "Gạo",
    qty: 120.5,
    cost: 28_000,
    min: 50,
    max: 300,
    reorder: 80,
    status: "normal" as IngredientStatus,
    lastCount: "08/04/2026",
    temp: null,
  },
  {
    id: 2,
    name: "Sườn non heo",
    sku: "MEAT-001",
    unit: "Kg",
    category: "Thịt",
    qty: 5.0,
    cost: 185_000,
    min: 10,
    max: 80,
    reorder: 15,
    status: "low" as IngredientStatus,
    lastCount: "06/04/2026",
    temp: "0-4°C",
  },
  {
    id: 3,
    name: "Thịt cốt lết tươi",
    sku: "MEAT-002",
    unit: "Kg",
    category: "Thịt",
    qty: 12.5,
    cost: 145_000,
    min: 8,
    max: 60,
    reorder: 12,
    status: "normal" as IngredientStatus,
    lastCount: "06/04/2026",
    temp: "0-4°C",
  },
  {
    id: 4,
    name: "Bì heo trộn thính",
    sku: "MEAT-003",
    unit: "Kg",
    category: "Thịt",
    qty: 3.2,
    cost: 95_000,
    min: 5,
    max: 30,
    reorder: 8,
    status: "low" as IngredientStatus,
    lastCount: "07/04/2026",
    temp: "0-4°C",
  },
  {
    id: 5,
    name: "Chả trứng hấp",
    sku: "PREP-001",
    unit: "Kg",
    category: "Chế biến",
    qty: 8.0,
    cost: 110_000,
    min: 5,
    max: 25,
    reorder: 8,
    status: "normal" as IngredientStatus,
    lastCount: "07/04/2026",
    temp: "0-4°C",
  },
  {
    id: 6,
    name: "Trứng vịt",
    sku: "EGG-001",
    unit: "Quả",
    category: "Trứng",
    qty: 200,
    cost: 3_500,
    min: 100,
    max: 500,
    reorder: 150,
    status: "normal" as IngredientStatus,
    lastCount: "08/04/2026",
    temp: null,
  },
  {
    id: 7,
    name: "Nước mắm Phan Thiết",
    sku: "SAU-001",
    unit: "Lít",
    category: "Gia vị",
    qty: 15.0,
    cost: 85_000,
    min: 5,
    max: 40,
    reorder: 10,
    status: "normal" as IngredientStatus,
    lastCount: "05/04/2026",
    temp: null,
  },
  {
    id: 8,
    name: "Đồ chua (cà rốt, củ cải)",
    sku: "VEG-001",
    unit: "Kg",
    category: "Rau củ",
    qty: 6.0,
    cost: 32_000,
    min: 4,
    max: 20,
    reorder: 6,
    status: "normal" as IngredientStatus,
    lastCount: "08/04/2026",
    temp: "2-6°C",
  },
  {
    id: 9,
    name: "Mỡ hành",
    sku: "SAU-002",
    unit: "Lít",
    category: "Gia vị",
    qty: 4.5,
    cost: 45_000,
    min: 3,
    max: 15,
    reorder: 5,
    status: "normal" as IngredientStatus,
    lastCount: "07/04/2026",
    temp: null,
  },
  {
    id: 10,
    name: "Hành phi",
    sku: "SAU-003",
    unit: "Kg",
    category: "Gia vị",
    qty: 2.0,
    cost: 220_000,
    min: 1,
    max: 8,
    reorder: 2,
    status: "normal" as IngredientStatus,
    lastCount: "06/04/2026",
    temp: null,
  },
  {
    id: 11,
    name: "Dầu ăn Simply 5L",
    sku: "OIL-001",
    unit: "Chai",
    category: "Dầu",
    qty: 8,
    cost: 135_000,
    min: 4,
    max: 20,
    reorder: 6,
    status: "normal" as IngredientStatus,
    lastCount: "05/04/2026",
    temp: null,
  },
  {
    id: 12,
    name: "Tiêu xay",
    sku: "SPI-001",
    unit: "Kg",
    category: "Gia vị",
    qty: 0.8,
    cost: 320_000,
    min: 0.5,
    max: 3,
    reorder: 1,
    status: "normal" as IngredientStatus,
    lastCount: "05/04/2026",
    temp: null,
  },
];

export const suppliers = [
  {
    id: 1,
    name: "C.P. Việt Nam",
    taxId: "0301234567",
    code: "NCC-001",
    phone: "028 7300 6100",
    address: "123 Phan Đăng Lưu, Q.PN",
    status: "active",
    category: "Thịt",
  },
  {
    id: 2,
    name: "Gạo Sạch Mỹ Tho",
    taxId: "0312067814",
    code: "NCC-002",
    phone: "0273 344 1568",
    address: "45 Nguyễn Trãi, Mỹ Tho",
    status: "active",
    category: "Gạo",
  },
  {
    id: 3,
    name: "Gia vị Cholimex",
    taxId: "0300112233",
    code: "NCC-003",
    phone: "028 3750 8899",
    address: "Lô C40-43I, KCN VL",
    status: "active",
    category: "Gia vị",
  },
  {
    id: 4,
    name: "Rau Củ Đà Lạt Fresh",
    taxId: "5801098765",
    code: "NCC-004",
    phone: "0263 382 5511",
    address: "12 Trần Phú, Đà Lạt",
    status: "active",
    category: "Rau củ",
  },
  {
    id: 5,
    name: "Thịt Sạch FreshFood",
    taxId: "0309876543",
    code: "NCC-005",
    phone: "028 5412 3000",
    address: "789 Quốc lộ 1A, Q.12",
    status: "active",
    category: "Thịt",
  },
  {
    id: 6,
    name: "Vinasan Food CA",
    taxId: "3700234561",
    code: "NCC-006",
    phone: "0254 384 6200",
    address: "KCN Phú Mỹ, BR-VT",
    status: "suspended",
    category: "Hải sản",
  },
];

export const purchaseOrders = [
  {
    id: 1,
    code: "PO-2604-001",
    supplierId: 1,
    supplierName: "C.P. Việt Nam",
    date: "01/04/2026",
    expectedDelivery: "03/04/2026",
    total: 12_450_000,
    status: "received" as DocumentStatus,
    createdBy: "Minh Trần",
    items: 3,
  },
  {
    id: 2,
    code: "PO-2604-002",
    supplierId: 2,
    supplierName: "Gạo Sạch Mỹ Tho",
    date: "02/04/2026",
    expectedDelivery: null,
    total: 4_200_000,
    status: "draft" as DocumentStatus,
    createdBy: "Má Tư",
    items: 2,
  },
  {
    id: 3,
    code: "PO-2604-003",
    supplierId: 4,
    supplierName: "Rau Củ Đà Lạt Fresh",
    date: "03/04/2026",
    expectedDelivery: "05/04/2026",
    total: 3_850_000,
    status: "received" as DocumentStatus,
    createdBy: "Hạnh Nguyễn",
    items: 4,
  },
  {
    id: 4,
    code: "PO-2604-004",
    supplierId: 3,
    supplierName: "Gia vị Cholimex",
    date: "05/04/2026",
    expectedDelivery: null,
    total: 1_200_000,
    status: "cancelled" as DocumentStatus,
    createdBy: "Minh Trần",
    items: 2,
  },
  {
    id: 5,
    code: "PO-2604-005",
    supplierId: 1,
    supplierName: "C.P. Việt Nam",
    date: "07/04/2026",
    expectedDelivery: "09/04/2026",
    total: 18_750_000,
    status: "sent" as DocumentStatus,
    createdBy: "Minh Trần",
    items: 4,
  },
  {
    id: 6,
    code: "PO-2604-006",
    supplierId: 5,
    supplierName: "Thịt Sạch FreshFood",
    date: "08/04/2026",
    expectedDelivery: "10/04/2026",
    total: 8_900_000,
    status: "sent" as DocumentStatus,
    createdBy: "Má Tư",
    items: 3,
  },
];

export const grns = [
  {
    id: 1,
    code: "GRN-2604-001",
    poCode: "PO-2604-001",
    supplierName: "C.P. Việt Nam",
    date: "03/04/2026",
    total: 12_200_000,
    status: "confirmed" as DocumentStatus,
    items: 3,
    qcPassed: 3,
    qcWarning: 0,
  },
  {
    id: 2,
    code: "GRN-2604-002",
    poCode: "PO-2604-003",
    supplierName: "Rau Củ Đà Lạt Fresh",
    date: "05/04/2026",
    total: 3_680_000,
    status: "confirmed" as DocumentStatus,
    items: 4,
    qcPassed: 3,
    qcWarning: 1,
  },
  {
    id: 3,
    code: "GRN-2604-003",
    poCode: "PO-2604-005",
    supplierName: "C.P. Việt Nam",
    date: "09/04/2026",
    total: 18_500_000,
    status: "pending" as DocumentStatus,
    items: 4,
    qcPassed: 0,
    qcWarning: 0,
  },
];

export const stockIssues = [
  {
    id: 1,
    code: "PXK-2604-001",
    type: "kitchen_use",
    typeName: "Tiêu hao bếp",
    branchName: "Trụ sở chính",
    date: "08/04/2026 08:30",
    createdBy: "Minh Tú",
    status: "confirmed" as DocumentStatus,
    total: 4_350_000,
    items: 5,
  },
  {
    id: 2,
    code: "PXK-2604-002",
    type: "write_off",
    typeName: "Hỏng / Hết hạn",
    branchName: "CN Quận 1",
    date: "07/04/2026 10:15",
    createdBy: "Hoàng Anh",
    status: "draft" as DocumentStatus,
    total: 890_000,
    items: 2,
  },
  {
    id: 3,
    code: "PXK-2604-003",
    type: "consumption",
    typeName: "Tiêu hao theo đơn",
    branchName: "CN Quận 3",
    date: "06/04/2026 16:45",
    createdBy: "Khánh Vy",
    status: "cancelled" as DocumentStatus,
    total: 2_100_000,
    items: 8,
  },
  {
    id: 4,
    code: "PXK-2604-004",
    type: "kitchen_use",
    typeName: "Tiêu hao bếp",
    branchName: "Trụ sở chính",
    date: "05/04/2026 11:20",
    createdBy: "Minh Tú",
    status: "confirmed" as DocumentStatus,
    total: 3_780_000,
    items: 6,
  },
  {
    id: 5,
    code: "PXK-2604-005",
    type: "write_off",
    typeName: "Hỏng / Hết hạn",
    branchName: "CN Bình Thạnh",
    date: "04/04/2026 09:00",
    createdBy: "Lan Phương",
    status: "confirmed" as DocumentStatus,
    total: 450_000,
    items: 1,
  },
];

export const transfers = [
  {
    id: 1,
    code: "TRF-2604-001",
    fromBranch: "Trụ sở chính",
    toBranch: "CN Quận 1",
    date: "08/04/2026 08:30",
    status: "in_transit" as DocumentStatus,
    total: 12_450_000,
    items: 8,
    createdBy: "Trần Anh Tuấn",
  },
  {
    id: 2,
    code: "TRF-2604-002",
    fromBranch: "Trụ sở chính",
    toBranch: "CN Quận 3",
    date: "07/04/2026 09:15",
    status: "received" as DocumentStatus,
    total: 8_200_000,
    items: 5,
    createdBy: "Trần Anh Tuấn",
  },
  {
    id: 3,
    code: "TRF-2604-003",
    fromBranch: "Trụ sở chính",
    toBranch: "CN Bình Thạnh",
    date: "07/04/2026 10:00",
    status: "draft" as DocumentStatus,
    total: 5_600_000,
    items: 4,
    createdBy: "Minh Trần",
  },
  {
    id: 4,
    code: "TRF-2603-098",
    fromBranch: "CN Quận 1",
    toBranch: "Trụ sở chính",
    date: "28/03/2026 16:45",
    status: "cancelled" as DocumentStatus,
    total: 1_200_000,
    items: 2,
    createdBy: "Hoàng Anh",
  },
  {
    id: 5,
    code: "TRF-2604-005",
    fromBranch: "Trụ sở chính",
    toBranch: "CN Thủ Đức",
    date: "09/04/2026 11:20",
    status: "confirmed" as DocumentStatus,
    total: 9_800_000,
    items: 6,
    createdBy: "Trần Anh Tuấn",
  },
];

export const stocktakeSessions = [
  {
    id: 1,
    code: "KK-2604-001",
    branchName: "CN Quận 1",
    manager: "Hoàng Anh",
    startDate: "08/04/2026 08:30",
    endDate: null,
    status: "in_progress" as DocumentStatus,
    total: 124,
    counted: 87,
    progress: 70,
  },
  {
    id: 2,
    code: "KK-2603-042",
    branchName: "CN Quận 3",
    manager: "Khánh Vy",
    startDate: "20/03/2026 14:00",
    endDate: "20/03/2026 16:45",
    status: "completed" as DocumentStatus,
    total: 118,
    counted: 118,
    progress: 100,
  },
  {
    id: 3,
    code: "KK-2603-041",
    branchName: "CN Quận 1",
    manager: "Hoàng Anh",
    startDate: "18/03/2026 09:15",
    endDate: "18/03/2026 11:30",
    status: "completed" as DocumentStatus,
    total: 94,
    counted: 94,
    progress: 100,
  },
  {
    id: 4,
    code: "KK-2604-002",
    branchName: "CN Bình Thạnh",
    manager: "Lan Phương",
    startDate: "09/04/2026 10:15",
    endDate: null,
    status: "in_progress" as DocumentStatus,
    total: 128,
    counted: 15,
    progress: 12,
  },
];

export const supplierInvoices = [
  {
    id: 1,
    code: "INV-2604-089",
    supplierName: "C.P. Việt Nam",
    poCode: "PO-2604-001",
    grnCode: "GRN-2604-001",
    amount: 42_850_000,
    matchStatus: "discrepancy" as DocumentStatus,
    paymentStatus: "pending" as DocumentStatus,
    variance: 7.2,
    date: "05/04/2026",
  },
  {
    id: 2,
    code: "INV-2604-090",
    supplierName: "Gạo Sạch Mỹ Tho",
    poCode: "PO-2604-002",
    grnCode: null,
    amount: 18_200_000,
    matchStatus: "matched" as DocumentStatus,
    paymentStatus: "pending" as DocumentStatus,
    variance: 0,
    date: "06/04/2026",
  },
  {
    id: 3,
    code: "INV-2604-091",
    supplierName: "Gia vị Cholimex",
    poCode: "PO-2603-048",
    grnCode: "GRN-2603-055",
    amount: 5_400_000,
    matchStatus: "pending" as DocumentStatus,
    paymentStatus: "overdue" as DocumentStatus,
    variance: null,
    date: "01/04/2026",
  },
];

export const expiryAlerts = [
  {
    id: 1,
    ingredientName: "Gạo tấm ST25",
    lot: "LOT-2601-M5",
    expiryDate: "20/03/2026",
    daysLeft: -21,
    grnCode: "GRN-2601-019",
    branchName: "CN Quận 1",
    urgency: "expired" as const,
  },
  {
    id: 2,
    ingredientName: "Dầu ăn Simply 5L",
    lot: "LOT-2603-B14",
    expiryDate: "12/04/2026",
    daysLeft: 2,
    grnCode: "GRN-2603-040",
    branchName: "Trụ sở chính",
    urgency: "critical" as const,
  },
  {
    id: 3,
    ingredientName: "Nước mắm Chinsu",
    lot: "LOT-2602-C09",
    expiryDate: "14/04/2026",
    daysLeft: 4,
    grnCode: "GRN-2602-042",
    branchName: "CN Thủ Đức",
    urgency: "warning" as const,
  },
  {
    id: 4,
    ingredientName: "Bột mì đa dụng",
    lot: "LOT-2601-D65",
    expiryDate: "11/04/2026",
    daysLeft: 1,
    grnCode: "GRN-2601-045",
    branchName: "CN Quận 3",
    urgency: "critical" as const,
  },
  {
    id: 5,
    ingredientName: "Sườn non heo",
    lot: "LOT-2604-A02",
    expiryDate: "15/04/2026",
    daysLeft: 5,
    grnCode: "GRN-2604-001",
    branchName: "Trụ sở chính",
    urgency: "warning" as const,
  },
];

export const recipes = [
  {
    id: 1,
    name: "Cơm tấm sườn bì chả",
    category: "Món chính",
    updatedAt: "2 giờ trước",
    estimatedCost: 24_500,
    items: [
      {
        ingredientName: "Gạo tấm Đặc biệt",
        qty: 250,
        unit: "Gram",
        yieldFactor: 100,
        note: "Gạo tấm 3x đãi tạp 1",
      },
      {
        ingredientName: "Sườn cốt lết tươi",
        qty: 180,
        unit: "Gram",
        yieldFactor: 85,
        note: "Trừ hao hút xương + nướng",
      },
      {
        ingredientName: "Bì heo trộn thính",
        qty: 30,
        unit: "Gram",
        yieldFactor: 100,
        note: null,
      },
      {
        ingredientName: "Chả trứng hấp",
        qty: 0.25,
        unit: "Cái",
        yieldFactor: 100,
        note: "1/4 chả cho 4 phần",
      },
    ],
  },
  {
    id: 2,
    name: "Cơm đùi gà nướng",
    category: "Món chính",
    updatedAt: "1 ngày trước",
    estimatedCost: 28_000,
    items: [
      {
        ingredientName: "Gạo tấm Đặc biệt",
        qty: 250,
        unit: "Gram",
        yieldFactor: 100,
        note: null,
      },
      {
        ingredientName: "Đùi gà góc tư",
        qty: 1,
        unit: "Cái",
        yieldFactor: 90,
        note: "Đùi gà CP size 350-400g",
      },
    ],
  },
  {
    id: 3,
    name: "Cơm tấm sườn nướng",
    category: "Món chính",
    updatedAt: "3 ngày trước",
    estimatedCost: 22_000,
    items: [
      {
        ingredientName: "Gạo tấm Đặc biệt",
        qty: 250,
        unit: "Gram",
        yieldFactor: 100,
        note: null,
      },
      {
        ingredientName: "Sườn cốt lết tươi",
        qty: 200,
        unit: "Gram",
        yieldFactor: 85,
        note: null,
      },
    ],
  },
];

// --- Dashboard aggregates ---
export const dashboardStats = {
  totalStockValue: 650_000_000,
  pendingPO: 6,
  activeTransfers: 4,
  activeStocktakes: 2,
  reorderAlerts: [
    { name: "Sườn non heo", current: 5.0, reorder: 15, unit: "Kg" },
    { name: "Bì heo trộn thính", current: 3.2, reorder: 8, unit: "Kg" },
    { name: "Nước mắm Phan Thiết", current: 15.0, reorder: 10, unit: "Lít" },
  ],
  expiryCount: { expired: 1, critical: 2, warning: 2 },
};

// --- Reports data ---
export const reportData = {
  movementSummary: [
    { month: "Th01", inbound: 85, outbound: 62, transfer: 28 },
    { month: "Th02", inbound: 92, outbound: 78, transfer: 34 },
    { month: "Th03", inbound: 78, outbound: 71, transfer: 31 },
    { month: "Th04", inbound: 45, outbound: 38, transfer: 18 },
  ],
  apAging: [
    { range: "0 – 30 ngày", amount: 452_000_000 },
    { range: "31 – 60 ngày", amount: 120_500_000 },
    { range: "61 – 90 ngày", amount: 32_400_000 },
    { range: "> 90 ngày", amount: 8_600_000 },
  ],
  consumptionVariance: [
    { name: "Gạo ST25", actual: "+4.2%", trend: "up" },
    { name: "Sườn cốt lết", actual: "-1.5%", trend: "down" },
    { name: "Trứng vịt", actual: "+0.8%", trend: "up" },
  ],
  foodCostTrend: [65, 62, 68, 64, 61, 58, 63, 60, 57, 55, 59, 56],
  foodCostTarget: 60,
};

// --- Formatting ---
export function formatVND(n: number): string {
  return n.toLocaleString("vi-VN");
}

export function formatQty(n: number): string {
  return n % 1 === 0
    ? n.toLocaleString("vi-VN")
    : n.toLocaleString("vi-VN", {
        minimumFractionDigits: 1,
        maximumFractionDigits: 1,
      });
}
