-- =============================================================
-- Intentionally empty for fresh DB project.
--
-- Trước đây file này seed 21 dòng recipe cho menu_item "Sườn Cốt Lết".
-- Đã bỏ vì migration 20260508071920_redo_suon_as_production_recipes.sql
-- đã rollback rồi và chuẩn bị DB mới không cần ingredient/recipe seed.
-- =============================================================
