-- Monthly Doanh thu thuần targets per branch + Owner upsert / BM progress read.

CREATE TABLE public.branch_revenue_targets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES public.tenants (id),
  branch_id bigint NOT NULL REFERENCES public.branches (id),
  year_month date NOT NULL,
  target_amount numeric(14, 2) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES auth.users (id),
  CONSTRAINT branch_revenue_targets_year_month_first_day_check
    CHECK (year_month = date_trunc('month', year_month::timestamp)::date),
  CONSTRAINT branch_revenue_targets_amount_positive_check
    CHECK (target_amount > 0),
  CONSTRAINT branch_revenue_targets_branch_month_key
    UNIQUE (branch_id, year_month)
);

CREATE INDEX branch_revenue_targets_tenant_month_idx
  ON public.branch_revenue_targets (tenant_id, year_month);

COMMENT ON TABLE public.branch_revenue_targets IS
  'Owner-set monthly Doanh thu thuần target per branch (year_month = first day of VN calendar month).';

CREATE OR REPLACE FUNCTION private.branch_revenue_targets_enforce_branch_kind()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
  v_kind text;
  v_tenant bigint;
BEGIN
  SELECT b.branch_kind, b.tenant_id
  INTO v_kind, v_tenant
  FROM public.branches b
  WHERE b.id = NEW.branch_id;

  IF v_kind IS NULL THEN
    RAISE EXCEPTION 'branch_not_found' USING ERRCODE = '22023';
  END IF;

  IF v_kind <> 'branch' THEN
    RAISE EXCEPTION 'branch_kind_not_allowed' USING ERRCODE = '22023';
  END IF;

  NEW.tenant_id := v_tenant;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER branch_revenue_targets_enforce_branch_kind
  BEFORE INSERT OR UPDATE OF branch_id, year_month, target_amount
  ON public.branch_revenue_targets
  FOR EACH ROW
  EXECUTE FUNCTION private.branch_revenue_targets_enforce_branch_kind();

ALTER TABLE public.branch_revenue_targets ENABLE ROW LEVEL SECURITY;

CREATE POLICY branch_revenue_targets_select
  ON public.branch_revenue_targets
  FOR SELECT
  TO authenticated
  USING (
    tenant_id = public.auth_tenant_id()
    AND (
      public.has_permission_any('finance:view')
      OR (
        public.auth_role() = 'branch_manager'
        AND public.auth_branch_id() IS NOT NULL
        AND branch_id = public.auth_branch_id()
      )
    )
  );

CREATE POLICY branch_revenue_targets_insert
  ON public.branch_revenue_targets
  FOR INSERT
  TO authenticated
  WITH CHECK (
    tenant_id = public.auth_tenant_id()
    AND public.auth_is_owner(auth.uid())
    AND public.has_permission_any('finance:view')
  );

CREATE POLICY branch_revenue_targets_update
  ON public.branch_revenue_targets
  FOR UPDATE
  TO authenticated
  USING (
    tenant_id = public.auth_tenant_id()
    AND public.auth_is_owner(auth.uid())
    AND public.has_permission_any('finance:view')
  )
  WITH CHECK (
    tenant_id = public.auth_tenant_id()
    AND public.auth_is_owner(auth.uid())
    AND public.has_permission_any('finance:view')
  );

CREATE POLICY branch_revenue_targets_delete
  ON public.branch_revenue_targets
  FOR DELETE
  TO authenticated
  USING (
    tenant_id = public.auth_tenant_id()
    AND public.auth_is_owner(auth.uid())
    AND public.has_permission_any('finance:view')
  );

REVOKE ALL ON TABLE public.branch_revenue_targets FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.branch_revenue_targets TO authenticated;
GRANT ALL ON TABLE public.branch_revenue_targets TO service_role;
REVOKE ALL ON SEQUENCE public.branch_revenue_targets_id_seq FROM PUBLIC, anon;
GRANT USAGE, SELECT ON SEQUENCE public.branch_revenue_targets_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.branch_revenue_targets_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.list_branch_revenue_targets(p_year_month date)
RETURNS TABLE (
  branch_id bigint,
  branch_name text,
  year_month date,
  target_amount numeric,
  prior_month_net_revenue numeric
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_month date;
  v_prior_start date;
  v_prior_end date;
  v_prior_start_utc timestamptz;
  v_prior_end_utc timestamptz;
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  IF NOT public.auth_is_owner(v_uid)
     OR NOT public.has_permission_any('finance:view') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  IF p_year_month IS NULL THEN
    RAISE EXCEPTION 'invalid_year_month' USING ERRCODE = '22023';
  END IF;

  v_month := date_trunc('month', p_year_month::timestamp)::date;
  v_prior_start := (v_month - interval '1 month')::date;
  v_prior_end := (v_month - interval '1 day')::date;
  v_prior_start_utc := v_prior_start::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh';
  v_prior_end_utc := (v_prior_end + 1)::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh';

  RETURN QUERY
  WITH branches AS (
    SELECT b.id, b.name
    FROM public.branches b
    WHERE b.tenant_id = v_tenant
      AND b.branch_kind = 'branch'
      AND b.is_active IS TRUE
  ),
  prior_paid AS (
    SELECT
      payment.branch_id,
      payment.order_id,
      payment.id AS payment_id,
      payment.paid_at,
      orders.subtotal,
      orders.discount_amount
    FROM public.payments payment
    JOIN public.orders orders
      ON orders.id = payment.order_id
     AND orders.tenant_id = payment.tenant_id
     AND orders.branch_id = payment.branch_id
    WHERE payment.tenant_id = v_tenant
      AND payment.status = 'completed'
      AND payment.paid_at >= v_prior_start_utc
      AND payment.paid_at < v_prior_end_utc
      AND payment.branch_id IN (SELECT branches.id FROM branches)
  ),
  prior_facts AS (
    SELECT DISTINCT ON (prior_paid.branch_id, prior_paid.order_id)
      prior_paid.branch_id,
      prior_paid.subtotal,
      prior_paid.discount_amount
    FROM prior_paid
    ORDER BY
      prior_paid.branch_id,
      prior_paid.order_id,
      prior_paid.paid_at,
      prior_paid.payment_id
  ),
  prior_net AS (
    SELECT
      prior_facts.branch_id,
      COALESCE(
        sum(prior_facts.subtotal - prior_facts.discount_amount),
        0
      )::numeric AS net_revenue
    FROM prior_facts
    GROUP BY prior_facts.branch_id
  )
  SELECT
    branches.id AS branch_id,
    branches.name AS branch_name,
    v_month AS year_month,
    targets.target_amount,
    COALESCE(prior_net.net_revenue, 0)::numeric AS prior_month_net_revenue
  FROM branches
  LEFT JOIN public.branch_revenue_targets targets
    ON targets.branch_id = branches.id
   AND targets.year_month = v_month
   AND targets.tenant_id = v_tenant
  LEFT JOIN prior_net
    ON prior_net.branch_id = branches.id
  ORDER BY branches.name;
END;
$$;

COMMENT ON FUNCTION public.list_branch_revenue_targets(date) IS
  'Owner-only list of active branches with monthly Doanh thu thuần target and prior-month net revenue.';

CREATE OR REPLACE FUNCTION public.upsert_branch_revenue_targets(
  p_year_month date,
  p_rows jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_month date;
  v_updated integer := 0;
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  IF NOT public.auth_is_owner(v_uid)
     OR NOT public.has_permission_any('finance:view') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  IF p_year_month IS NULL OR p_rows IS NULL
     OR jsonb_typeof(p_rows) <> 'array'
     OR jsonb_array_length(p_rows) < 1
     OR jsonb_array_length(p_rows) > 200 THEN
    RAISE EXCEPTION 'invalid_payload' USING ERRCODE = '22023';
  END IF;

  v_month := date_trunc('month', p_year_month::timestamp)::date;

  WITH incoming AS (
    SELECT
      (row_data ->> 'branch_id')::bigint AS branch_id,
      (row_data ->> 'target_amount')::numeric AS target_amount
    FROM jsonb_array_elements(p_rows) AS row_data
  ),
  validated AS (
    SELECT
      incoming.branch_id,
      incoming.target_amount
    FROM incoming
    JOIN public.branches b
      ON b.id = incoming.branch_id
     AND b.tenant_id = v_tenant
     AND b.branch_kind = 'branch'
     AND b.is_active IS TRUE
    WHERE incoming.branch_id IS NOT NULL
      AND incoming.target_amount IS NOT NULL
      AND incoming.target_amount > 0
  ),
  upserted AS (
    INSERT INTO public.branch_revenue_targets AS t (
      tenant_id,
      branch_id,
      year_month,
      target_amount,
      updated_by
    )
    SELECT
      v_tenant,
      validated.branch_id,
      v_month,
      round(validated.target_amount, 0),
      v_uid
    FROM validated
    ON CONFLICT (branch_id, year_month)
    DO UPDATE SET
      target_amount = EXCLUDED.target_amount,
      updated_by = EXCLUDED.updated_by,
      updated_at = now()
    RETURNING t.id
  )
  SELECT count(*)::integer INTO v_updated FROM upserted;

  IF v_updated = 0 THEN
    RAISE EXCEPTION 'no_valid_rows' USING ERRCODE = '22023';
  END IF;

  RETURN jsonb_build_object(
    'updated', v_updated,
    'year_month', v_month
  );
END;
$$;

COMMENT ON FUNCTION public.upsert_branch_revenue_targets(date, jsonb) IS
  'Owner-only bulk upsert of monthly Doanh thu thuần targets per branch.';

CREATE OR REPLACE FUNCTION public.get_branch_revenue_target_progress(
  p_branch_id bigint,
  p_year_month date DEFAULT NULL
)
RETURNS TABLE (
  branch_id bigint,
  year_month date,
  net_revenue_mtd numeric,
  target_amount numeric,
  progress_pct numeric,
  gap_amount numeric
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_role text := public.auth_role();
  v_caller_branch bigint := public.auth_branch_id();
  v_month date;
  v_today date;
  v_end date;
  v_start_utc timestamptz;
  v_end_utc timestamptz;
  v_has_tenant_scope boolean;
  v_branch_ids bigint[];
  v_net numeric := 0;
  v_target numeric;
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  IF p_branch_id IS NULL THEN
    RAISE EXCEPTION 'invalid_branch' USING ERRCODE = '22023';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.branches b
    WHERE b.id = p_branch_id
      AND b.tenant_id = v_tenant
      AND b.branch_kind = 'branch'
  ) THEN
    RAISE EXCEPTION 'branch_not_found' USING ERRCODE = '22023';
  END IF;

  IF v_role = 'branch_manager' THEN
    IF v_caller_branch IS NULL OR v_caller_branch <> p_branch_id THEN
      RAISE EXCEPTION 'branch scope mismatch' USING ERRCODE = '42501';
    END IF;
  ELSIF v_role IN ('owner', 'accountant') THEN
    SELECT scope.has_tenant_scope, scope.branch_ids
    INTO v_has_tenant_scope, v_branch_ids
    FROM private.finance_scope(v_uid, 'finance:view') scope;

    IF NOT (
      v_has_tenant_scope
      OR p_branch_id = ANY(COALESCE(v_branch_ids, ARRAY[]::bigint[]))
    ) THEN
      RAISE EXCEPTION 'not_allowed' USING ERRCODE = '42501';
    END IF;
  ELSE
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  v_today := (timezone('Asia/Ho_Chi_Minh', now()))::date;
  v_month := date_trunc(
    'month',
    COALESCE(p_year_month, v_today)::timestamp
  )::date;

  IF date_trunc('month', v_today::timestamp)::date = v_month THEN
    v_end := v_today;
  ELSE
    v_end := (v_month + interval '1 month' - interval '1 day')::date;
  END IF;

  v_start_utc := v_month::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh';
  v_end_utc := (v_end + 1)::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh';

  WITH paid AS (
    SELECT
      payment.order_id,
      payment.id AS payment_id,
      payment.paid_at,
      orders.subtotal,
      orders.discount_amount
    FROM public.payments payment
    JOIN public.orders orders
      ON orders.id = payment.order_id
     AND orders.tenant_id = payment.tenant_id
     AND orders.branch_id = payment.branch_id
    WHERE payment.tenant_id = v_tenant
      AND payment.branch_id = p_branch_id
      AND payment.status = 'completed'
      AND payment.paid_at >= v_start_utc
      AND payment.paid_at < v_end_utc
  ),
  order_facts AS (
    SELECT DISTINCT ON (paid.order_id)
      paid.subtotal,
      paid.discount_amount
    FROM paid
    ORDER BY paid.order_id, paid.paid_at, paid.payment_id
  )
  SELECT COALESCE(sum(order_facts.subtotal - order_facts.discount_amount), 0)
  INTO v_net
  FROM order_facts;

  SELECT targets.target_amount
  INTO v_target
  FROM public.branch_revenue_targets targets
  WHERE targets.tenant_id = v_tenant
    AND targets.branch_id = p_branch_id
    AND targets.year_month = v_month;

  RETURN QUERY
  SELECT
    p_branch_id,
    v_month,
    v_net,
    v_target,
    CASE
      WHEN v_target IS NULL OR v_target <= 0 THEN NULL::numeric
      ELSE round((v_net / v_target) * 100, 1)
    END,
    CASE
      WHEN v_target IS NULL THEN NULL::numeric
      ELSE greatest(v_target - v_net, 0)
    END;
END;
$$;

COMMENT ON FUNCTION public.get_branch_revenue_target_progress(bigint, date) IS
  'Branch-scoped MTD/month Doanh thu thuần vs monthly target. BM same-branch or finance:view.';

CREATE OR REPLACE FUNCTION public.list_branch_revenue_target_progress(
  p_year_month date
)
RETURNS TABLE (
  branch_id bigint,
  branch_name text,
  year_month date,
  net_revenue numeric,
  target_amount numeric,
  progress_pct numeric,
  gap_amount numeric
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_month date;
  v_today date;
  v_end date;
  v_start_utc timestamptz;
  v_end_utc timestamptz;
  v_has_tenant_scope boolean;
  v_branch_ids bigint[];
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT scope.has_tenant_scope, scope.branch_ids
  INTO v_has_tenant_scope, v_branch_ids
  FROM private.finance_scope(v_uid, 'finance:view') scope;

  IF NOT (
    v_has_tenant_scope
    OR COALESCE(cardinality(v_branch_ids), 0) > 0
  ) THEN
    RAISE EXCEPTION 'not_allowed' USING ERRCODE = '42501';
  END IF;

  IF p_year_month IS NULL THEN
    RAISE EXCEPTION 'invalid_year_month' USING ERRCODE = '22023';
  END IF;

  v_today := (timezone('Asia/Ho_Chi_Minh', now()))::date;
  v_month := date_trunc('month', p_year_month::timestamp)::date;

  IF date_trunc('month', v_today::timestamp)::date = v_month THEN
    v_end := v_today;
  ELSE
    v_end := (v_month + interval '1 month' - interval '1 day')::date;
  END IF;

  v_start_utc := v_month::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh';
  v_end_utc := (v_end + 1)::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh';

  RETURN QUERY
  WITH branches AS (
    SELECT b.id, b.name
    FROM public.branches b
    WHERE b.tenant_id = v_tenant
      AND b.branch_kind = 'branch'
      AND b.is_active IS TRUE
      AND (
        v_has_tenant_scope
        OR b.id = ANY(COALESCE(v_branch_ids, ARRAY[]::bigint[]))
      )
  ),
  paid AS (
    SELECT
      payment.branch_id,
      payment.order_id,
      payment.id AS payment_id,
      payment.paid_at,
      orders.subtotal,
      orders.discount_amount
    FROM public.payments payment
    JOIN public.orders orders
      ON orders.id = payment.order_id
     AND orders.tenant_id = payment.tenant_id
     AND orders.branch_id = payment.branch_id
    WHERE payment.tenant_id = v_tenant
      AND payment.status = 'completed'
      AND payment.paid_at >= v_start_utc
      AND payment.paid_at < v_end_utc
      AND payment.branch_id IN (SELECT branches.id FROM branches)
  ),
  order_facts AS (
    SELECT DISTINCT ON (paid.branch_id, paid.order_id)
      paid.branch_id,
      paid.subtotal,
      paid.discount_amount
    FROM paid
    ORDER BY
      paid.branch_id,
      paid.order_id,
      paid.paid_at,
      paid.payment_id
  ),
  net AS (
    SELECT
      order_facts.branch_id,
      COALESCE(
        sum(order_facts.subtotal - order_facts.discount_amount),
        0
      )::numeric AS net_revenue
    FROM order_facts
    GROUP BY order_facts.branch_id
  )
  SELECT
    branches.id AS branch_id,
    branches.name AS branch_name,
    v_month AS year_month,
    COALESCE(net.net_revenue, 0)::numeric AS net_revenue,
    targets.target_amount,
    CASE
      WHEN targets.target_amount IS NULL OR targets.target_amount <= 0
        THEN NULL::numeric
      ELSE round((COALESCE(net.net_revenue, 0) / targets.target_amount) * 100, 1)
    END AS progress_pct,
    CASE
      WHEN targets.target_amount IS NULL THEN NULL::numeric
      ELSE greatest(targets.target_amount - COALESCE(net.net_revenue, 0), 0)
    END AS gap_amount
  FROM branches
  LEFT JOIN net ON net.branch_id = branches.id
  LEFT JOIN public.branch_revenue_targets targets
    ON targets.branch_id = branches.id
   AND targets.year_month = v_month
   AND targets.tenant_id = v_tenant
  ORDER BY
    progress_pct DESC NULLS LAST,
    net_revenue DESC,
    branches.name;
END;
$$;

COMMENT ON FUNCTION public.list_branch_revenue_target_progress(date) IS
  'Finance-scope progress of monthly Doanh thu thuần vs target for all visible branches.';

REVOKE ALL ON FUNCTION public.list_branch_revenue_targets(date) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.upsert_branch_revenue_targets(date, jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_branch_revenue_target_progress(bigint, date) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.list_branch_revenue_target_progress(date) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.list_branch_revenue_targets(date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.upsert_branch_revenue_targets(date, jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_branch_revenue_target_progress(bigint, date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.list_branch_revenue_target_progress(date) TO authenticated, service_role;
