-- =============================================================
-- Intentionally empty for fresh DB project.
--
-- Trước đây file này fix lỗi BOM "Nước cam" → swap ingredient sang 'Cam'
-- (sku DD-046) trong production_recipes của 'Sườn cọng đã ướp' và
-- 'Sườn cốt lết đã ướp'. Sanity check cuối expect 2 Cam refs.
--
-- Đã bỏ vì 4 file seed liên quan đã empty stub:
--   - 20260414105052_seed_production_finished_goods.sql
--   - 20260508070447_seed_suon_cong_recipe.sql
--   - 20260508071109_seed_suon_cot_let_recipe.sql
--   - 20260508071920_redo_suon_as_production_recipes.sql
--
-- DB mới sẽ owner tự seed ingredient/recipe qua UI; không có data để fix.
-- =============================================================
