CREATE TABLE public.finance_fund_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  entry_type text NOT NULL CHECK (entry_type IN ('opening', 'adjustment')),
  cash_delta numeric(15,2) NOT NULL DEFAULT 0,
  bank_delta numeric(15,2) NOT NULL DEFAULT 0,
  effective_at timestamptz NOT NULL,
  reason text NOT NULL CHECK (
    char_length(btrim(reason)) BETWEEN 5 AND 500
  ),
  created_by uuid NOT NULL REFERENCES public.profiles(id),
  idempotency_key uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  CONSTRAINT finance_fund_entries_amount_range CHECK (
    abs(cash_delta) <= 100000000000
    AND abs(bank_delta) <= 100000000000
  ),
  CONSTRAINT finance_fund_entries_entry_amount CHECK (
    (entry_type = 'opening' AND cash_delta >= 0 AND bank_delta >= 0)
    OR
    (entry_type = 'adjustment' AND (cash_delta <> 0 OR bank_delta <> 0))
  ),
  CONSTRAINT finance_fund_entries_effective_at_check CHECK (
    isfinite(effective_at) AND effective_at <= created_at
  ),
  CONSTRAINT finance_fund_entries_tenant_idempotency_key_key
    UNIQUE (tenant_id, idempotency_key)
);

CREATE UNIQUE INDEX finance_fund_entries_one_opening_per_tenant
  ON public.finance_fund_entries (tenant_id)
  WHERE entry_type = 'opening';

CREATE INDEX finance_fund_entries_tenant_effective_at_idx
  ON public.finance_fund_entries (tenant_id, effective_at, id);

COMMENT ON TABLE public.finance_fund_entries IS
  'Immutable tenant-wide book-fund opening and audited adjustments. Operational movements remain in their canonical ledgers.';

ALTER TABLE public.finance_fund_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY finance_fund_entries_owner_select
  ON public.finance_fund_entries
  FOR SELECT
  TO authenticated
  USING (
    tenant_id = (SELECT public.auth_tenant_id())
    AND (SELECT public.auth_role()) = 'owner'
  );

REVOKE ALL ON TABLE public.finance_fund_entries
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.finance_fund_entries TO authenticated;

CREATE OR REPLACE FUNCTION private.reject_finance_fund_entry_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  RAISE EXCEPTION 'finance_fund_entries_append_only'
    USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER finance_fund_entries_reject_update_delete
BEFORE UPDATE OR DELETE ON public.finance_fund_entries
FOR EACH ROW
EXECUTE FUNCTION private.reject_finance_fund_entry_mutation();

CREATE OR REPLACE FUNCTION private.guard_legacy_finance_settings()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
  v_protected_keys constant text[] := ARRAY[
    'cash_opening_balance',
    'bank_opening_balance',
    'cash_opening_date'
  ];
BEGIN
  IF TG_OP = 'INSERT' AND NEW.key = ANY(v_protected_keys) THEN
    RAISE EXCEPTION 'legacy_finance_setting_locked'
      USING ERRCODE = '55000';
  END IF;

  IF TG_OP = 'UPDATE'
    AND (
      OLD.key = ANY(v_protected_keys)
      OR NEW.key = ANY(v_protected_keys)
    )
  THEN
    RAISE EXCEPTION 'legacy_finance_setting_locked'
      USING ERRCODE = '55000';
  END IF;

  IF TG_OP = 'DELETE' AND OLD.key = ANY(v_protected_keys) THEN
    RAISE EXCEPTION 'legacy_finance_setting_locked'
      USING ERRCODE = '55000';
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER system_settings_guard_legacy_finance_opening
BEFORE INSERT OR UPDATE OR DELETE ON public.system_settings
FOR EACH ROW
EXECUTE FUNCTION private.guard_legacy_finance_settings();

DROP FUNCTION IF EXISTS public.set_finance_cash_opening(numeric, numeric, date);

CREATE OR REPLACE FUNCTION public.initialize_finance_funds(
  p_cash_opening numeric,
  p_bank_opening numeric,
  p_effective_at timestamptz,
  p_reason text,
  p_idempotency_key uuid
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_actor uuid := auth.uid();
  v_tenant_id bigint := public.auth_tenant_id();
  v_now timestamptz := statement_timestamp();
  v_effective_at timestamptz := COALESCE(p_effective_at, statement_timestamp());
  v_reason text := btrim(p_reason);
  v_existing public.finance_fund_entries%ROWTYPE;
  v_entry public.finance_fund_entries%ROWTYPE;
BEGIN
  IF v_actor IS NULL
    OR v_tenant_id IS NULL
    OR NOT public.auth_is_owner(v_actor)
  THEN
    RAISE EXCEPTION 'forbidden_owner_only' USING ERRCODE = '42501';
  END IF;

  IF p_cash_opening IS NULL
    OR p_bank_opening IS NULL
    OR p_cash_opening < 0
    OR p_bank_opening < 0
    OR abs(p_cash_opening) > 100000000000
    OR abs(p_bank_opening) > 100000000000
    OR NOT isfinite(v_effective_at)
    OR v_effective_at > v_now
    OR v_reason IS NULL
    OR char_length(v_reason) NOT BETWEEN 5 AND 500
    OR p_idempotency_key IS NULL
  THEN
    RAISE EXCEPTION 'finance_fund_opening_invalid'
      USING ERRCODE = '22023';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('finance_funds:' || v_tenant_id::text, 0)
  );

  SELECT *
  INTO v_existing
  FROM public.finance_fund_entries entry
  WHERE entry.tenant_id = v_tenant_id
    AND entry.idempotency_key = p_idempotency_key;

  IF FOUND THEN
    IF v_existing.entry_type = 'opening'
      AND v_existing.cash_delta = p_cash_opening
      AND v_existing.bank_delta = p_bank_opening
      AND (
        v_existing.effective_at = p_effective_at
        OR (
          p_effective_at IS NULL
          AND v_existing.effective_at = v_existing.created_at
        )
      )
      AND v_existing.reason = v_reason
    THEN
      RETURN to_jsonb(v_existing);
    END IF;

    RAISE EXCEPTION 'finance_fund_idempotency_conflict'
      USING ERRCODE = '23505';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.finance_fund_entries entry
    WHERE entry.tenant_id = v_tenant_id
      AND entry.entry_type = 'opening'
  ) THEN
    RAISE EXCEPTION 'finance_funds_already_initialized'
      USING ERRCODE = '23505';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.system_settings setting
    WHERE setting.tenant_id = v_tenant_id
      AND setting.key IN (
        'cash_opening_balance',
        'bank_opening_balance',
        'cash_opening_date'
      )
  ) THEN
    RAISE EXCEPTION 'finance_fund_legacy_cutover_required'
      USING ERRCODE = '55000';
  END IF;

  INSERT INTO public.finance_fund_entries (
    tenant_id,
    entry_type,
    cash_delta,
    bank_delta,
    effective_at,
    reason,
    created_by,
    idempotency_key,
    created_at
  ) VALUES (
    v_tenant_id,
    'opening',
    p_cash_opening,
    p_bank_opening,
    v_effective_at,
    v_reason,
    v_actor,
    p_idempotency_key,
    v_now
  )
  RETURNING * INTO v_entry;

  PERFORM public.log_audit(
    'finance_fund_opening_created',
    'finance_fund_entry',
    v_entry.id,
    NULL,
    jsonb_build_object(
      'entry_type', v_entry.entry_type,
      'cash_delta', v_entry.cash_delta,
      'bank_delta', v_entry.bank_delta,
      'effective_at', v_entry.effective_at,
      'reason', v_entry.reason,
      'idempotency_key', v_entry.idempotency_key
    )
  );

  RETURN to_jsonb(v_entry);
END;
$$;

CREATE OR REPLACE FUNCTION public.create_finance_fund_adjustment(
  p_cash_delta numeric,
  p_bank_delta numeric,
  p_reason text,
  p_idempotency_key uuid
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_actor uuid := auth.uid();
  v_tenant_id bigint := public.auth_tenant_id();
  v_now timestamptz := statement_timestamp();
  v_reason text := btrim(p_reason);
  v_existing public.finance_fund_entries%ROWTYPE;
  v_entry public.finance_fund_entries%ROWTYPE;
BEGIN
  IF v_actor IS NULL
    OR v_tenant_id IS NULL
    OR NOT public.auth_is_owner(v_actor)
  THEN
    RAISE EXCEPTION 'forbidden_owner_only' USING ERRCODE = '42501';
  END IF;

  IF p_cash_delta IS NULL
    OR p_bank_delta IS NULL
    OR (p_cash_delta = 0 AND p_bank_delta = 0)
    OR abs(p_cash_delta) > 100000000000
    OR abs(p_bank_delta) > 100000000000
    OR v_reason IS NULL
    OR char_length(v_reason) NOT BETWEEN 5 AND 500
    OR p_idempotency_key IS NULL
  THEN
    RAISE EXCEPTION 'finance_fund_adjustment_invalid'
      USING ERRCODE = '22023';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('finance_funds:' || v_tenant_id::text, 0)
  );

  SELECT *
  INTO v_existing
  FROM public.finance_fund_entries entry
  WHERE entry.tenant_id = v_tenant_id
    AND entry.idempotency_key = p_idempotency_key;

  IF FOUND THEN
    IF v_existing.entry_type = 'adjustment'
      AND v_existing.cash_delta = p_cash_delta
      AND v_existing.bank_delta = p_bank_delta
      AND v_existing.reason = v_reason
    THEN
      RETURN to_jsonb(v_existing);
    END IF;

    RAISE EXCEPTION 'finance_fund_idempotency_conflict'
      USING ERRCODE = '23505';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.finance_fund_entries entry
    WHERE entry.tenant_id = v_tenant_id
      AND entry.entry_type = 'opening'
  ) THEN
    RAISE EXCEPTION 'finance_funds_not_initialized'
      USING ERRCODE = '55000';
  END IF;

  INSERT INTO public.finance_fund_entries (
    tenant_id,
    entry_type,
    cash_delta,
    bank_delta,
    effective_at,
    reason,
    created_by,
    idempotency_key,
    created_at
  ) VALUES (
    v_tenant_id,
    'adjustment',
    p_cash_delta,
    p_bank_delta,
    v_now,
    v_reason,
    v_actor,
    p_idempotency_key,
    v_now
  )
  RETURNING * INTO v_entry;

  PERFORM public.log_audit(
    'finance_fund_adjustment_created',
    'finance_fund_entry',
    v_entry.id,
    NULL,
    jsonb_build_object(
      'entry_type', v_entry.entry_type,
      'cash_delta', v_entry.cash_delta,
      'bank_delta', v_entry.bank_delta,
      'effective_at', v_entry.effective_at,
      'reason', v_entry.reason,
      'idempotency_key', v_entry.idempotency_key
    )
  );

  RETURN to_jsonb(v_entry);
END;
$$;

CREATE OR REPLACE FUNCTION public.get_finance_current_funds()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_actor uuid := auth.uid();
  v_tenant_id bigint := public.auth_tenant_id();
  v_opening public.finance_fund_entries%ROWTYPE;
  v_cash_movement jsonb;
  v_bank_movement jsonb;
  v_cash_adjustments numeric;
  v_bank_adjustments numeric;
  v_cash_collections numeric;
  v_cash_refunds numeric;
  v_cash_expenses numeric;
  v_cash_supplier_payments numeric;
  v_cash_variance_adjustments numeric;
  v_bank_in numeric;
  v_bank_out numeric;
  v_legacy_settings_present boolean;
BEGIN
  IF v_actor IS NULL
    OR v_tenant_id IS NULL
    OR NOT public.auth_is_owner(v_actor)
  THEN
    RAISE EXCEPTION 'forbidden_owner_only' USING ERRCODE = '42501';
  END IF;

  SELECT *
  INTO v_opening
  FROM public.finance_fund_entries entry
  WHERE entry.tenant_id = v_tenant_id
    AND entry.entry_type = 'opening';

  SELECT EXISTS (
    SELECT 1
    FROM public.system_settings setting
    WHERE setting.tenant_id = v_tenant_id
      AND setting.key IN (
        'cash_opening_balance',
        'bank_opening_balance',
        'cash_opening_date'
      )
  )
  INTO v_legacy_settings_present;

  IF NOT FOUND OR v_opening.id IS NULL THEN
    RETURN jsonb_build_object(
      'has_opening', false,
      'opening_entry_id', NULL,
      'opening_cash', 0,
      'opening_bank', 0,
      'opening_effective_at', NULL,
      'cash_collections', 0,
      'cash_refunds', 0,
      'cash_expenses', 0,
      'cash_supplier_payments', 0,
      'cash_variance_adjustments', 0,
      'cash_adjustments', 0,
      'cash_current', 0,
      'bank_in', 0,
      'bank_out', 0,
      'bank_adjustments', 0,
      'bank_current', 0,
      'legacy_settings_present', v_legacy_settings_present
    );
  END IF;

  v_cash_movement :=
    public.get_cash_ledger_movement_since(v_opening.effective_at);
  v_bank_movement :=
    public.get_bank_ledger_movement_since(v_opening.effective_at);

  SELECT
    COALESCE(sum(entry.cash_delta), 0),
    COALESCE(sum(entry.bank_delta), 0)
  INTO v_cash_adjustments, v_bank_adjustments
  FROM public.finance_fund_entries entry
  WHERE entry.tenant_id = v_tenant_id
    AND entry.entry_type = 'adjustment'
    AND entry.effective_at >= v_opening.effective_at;

  v_cash_collections := COALESCE((v_cash_movement ->> 'cash_collections')::numeric, 0);
  v_cash_refunds := COALESCE((v_cash_movement ->> 'cash_refunds')::numeric, 0);
  v_cash_expenses := COALESCE((v_cash_movement ->> 'cash_expenses')::numeric, 0);
  v_cash_supplier_payments :=
    COALESCE((v_cash_movement ->> 'cash_supplier_payments')::numeric, 0);
  v_cash_variance_adjustments :=
    COALESCE((v_cash_movement ->> 'cash_variance_adjustments')::numeric, 0);
  v_bank_in := COALESCE((v_bank_movement ->> 'bank_in')::numeric, 0);
  v_bank_out := COALESCE((v_bank_movement ->> 'bank_out')::numeric, 0);

  RETURN jsonb_build_object(
    'has_opening', true,
    'opening_entry_id', v_opening.id,
    'opening_cash', v_opening.cash_delta,
    'opening_bank', v_opening.bank_delta,
    'opening_effective_at', v_opening.effective_at,
    'cash_collections', v_cash_collections,
    'cash_refunds', v_cash_refunds,
    'cash_expenses', v_cash_expenses,
    'cash_supplier_payments', v_cash_supplier_payments,
    'cash_variance_adjustments', v_cash_variance_adjustments,
    'cash_adjustments', v_cash_adjustments,
    'cash_current',
      v_opening.cash_delta
      + v_cash_collections
      - v_cash_refunds
      - v_cash_expenses
      - v_cash_supplier_payments
      + v_cash_variance_adjustments
      + v_cash_adjustments,
    'bank_in', v_bank_in,
    'bank_out', v_bank_out,
    'bank_adjustments', v_bank_adjustments,
    'bank_current',
      v_opening.bank_delta
      + v_bank_in
      - v_bank_out
      + v_bank_adjustments,
    'legacy_settings_present', v_legacy_settings_present
  );
END;
$$;

REVOKE ALL ON FUNCTION public.initialize_finance_funds(
  numeric, numeric, timestamptz, text, uuid
) FROM PUBLIC, anon, service_role;
REVOKE ALL ON FUNCTION public.create_finance_fund_adjustment(
  numeric, numeric, text, uuid
) FROM PUBLIC, anon, service_role;
REVOKE ALL ON FUNCTION public.get_finance_current_funds()
  FROM PUBLIC, anon, service_role;

GRANT EXECUTE ON FUNCTION public.initialize_finance_funds(
  numeric, numeric, timestamptz, text, uuid
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_finance_fund_adjustment(
  numeric, numeric, text, uuid
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_finance_current_funds()
  TO authenticated;

COMMENT ON FUNCTION public.initialize_finance_funds(
  numeric, numeric, timestamptz, text, uuid
) IS
  'Creates the immutable tenant finance opening once. NULL effective_at uses the exact server timestamp; a supplied timestamp is a verified historical boundary.';

COMMENT ON FUNCTION public.create_finance_fund_adjustment(
  numeric, numeric, text, uuid
) IS
  'Appends an audited signed correction at server time. Equal retry keys are idempotent only for equal payloads.';

COMMENT ON FUNCTION public.get_finance_current_funds() IS
  'Returns the tenant book-fund opening, canonical movement groups, audited adjustments, and current balances in one PostgreSQL snapshot.';
