-- Contract step (expand-contract): menu_items.vat_rate is no longer read by any
-- trigger/view/RPC/app path. order_items.vat_rate is derived per line by
-- populate_order_item_vat_rate -> resolve_gtgt_rate(tenant); order-item inserts
-- omit vat_rate (the trigger fills it); the menu module no longer writes it.
-- menu_items_vat_rate_default_zero added DEFAULT 0 so menu inserts could omit
-- the column (expand step); this contracts by dropping it entirely.
--
-- APPLY ORDER: deploy the app build that omits menu_items.vat_rate on insert
-- (createItem + import upsert) BEFORE applying this, or live menu create/import
-- will reference a dropped column.
ALTER TABLE public.menu_items DROP COLUMN vat_rate;
