-- Delivery channel Phase 1: manual POS intake (Grab/ShopeeFood/beFood/Green SM).
-- Merchant-of-record = Chén Sứ; platform prepaid tender = payments.method platform.
-- HĐĐT sales invoice auto-queues on platform like cash/VietQR (khách lẻ / QR buyer).
-- Adapters remain gated by D103; this channel does not lift that gate.

-- ---------------------------------------------------------------------------
-- 1. Schema: orders delivery fields + payment method platform + channel prices
-- ---------------------------------------------------------------------------

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS delivery_platform text,
  ADD COLUMN IF NOT EXISTS external_order_ref text;

ALTER TABLE public.orders
  DROP CONSTRAINT IF EXISTS orders_order_type_check;
ALTER TABLE public.orders
  ADD CONSTRAINT orders_order_type_check
  CHECK (order_type = ANY (ARRAY['dine_in'::text, 'takeaway'::text, 'delivery'::text]));

ALTER TABLE public.orders
  DROP CONSTRAINT IF EXISTS orders_payment_method_check;
ALTER TABLE public.orders
  ADD CONSTRAINT orders_payment_method_check
  CHECK (
    payment_method IS NULL
    OR payment_method = ANY (ARRAY['cash'::text, 'vietqr'::text, 'platform'::text])
  );

ALTER TABLE public.orders
  DROP CONSTRAINT IF EXISTS orders_delivery_platform_check;
ALTER TABLE public.orders
  ADD CONSTRAINT orders_delivery_platform_check
  CHECK (
    delivery_platform IS NULL
    OR delivery_platform = ANY (
      ARRAY['grab'::text, 'shopee'::text, 'be'::text, 'green_sm'::text]
    )
  );

ALTER TABLE public.orders
  DROP CONSTRAINT IF EXISTS orders_delivery_fields_pairing_check;
ALTER TABLE public.orders
  ADD CONSTRAINT orders_delivery_fields_pairing_check
  CHECK (
    (
      order_type = 'delivery'
      AND delivery_platform IS NOT NULL
      AND external_order_ref IS NOT NULL
      AND btrim(external_order_ref) <> ''
      AND table_id IS NULL
    )
    OR (
      order_type <> 'delivery'
      AND delivery_platform IS NULL
      AND external_order_ref IS NULL
    )
  );

CREATE UNIQUE INDEX IF NOT EXISTS orders_branch_delivery_ref_active_uidx
  ON public.orders (branch_id, delivery_platform, lower(btrim(external_order_ref)))
  WHERE order_type = 'delivery'
    AND status <> 'cancelled'
    AND delivery_platform IS NOT NULL
    AND external_order_ref IS NOT NULL
    AND btrim(external_order_ref) <> '';

ALTER TABLE public.payments
  DROP CONSTRAINT IF EXISTS payments_method_check;
ALTER TABLE public.payments
  ADD CONSTRAINT payments_method_check
  CHECK (method = ANY (ARRAY['cash'::text, 'vietqr'::text, 'platform'::text]));

CREATE TABLE IF NOT EXISTS public.menu_item_channel_prices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES public.tenants (id),
  menu_item_id bigint NOT NULL REFERENCES public.menu_items (id) ON DELETE CASCADE,
  delivery_platform text NOT NULL,
  unit_price numeric(15, 2) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT menu_item_channel_prices_platform_check
    CHECK (
      delivery_platform = ANY (
        ARRAY['grab'::text, 'shopee'::text, 'be'::text, 'green_sm'::text]
      )
    ),
  CONSTRAINT menu_item_channel_prices_unit_price_check
    CHECK (unit_price >= 0),
  CONSTRAINT menu_item_channel_prices_unique
    UNIQUE (tenant_id, menu_item_id, delivery_platform)
);

CREATE INDEX IF NOT EXISTS menu_item_channel_prices_item_idx
  ON public.menu_item_channel_prices (menu_item_id);

CREATE INDEX IF NOT EXISTS menu_item_channel_prices_tenant_idx
  ON public.menu_item_channel_prices (tenant_id);

DROP TRIGGER IF EXISTS trg_menu_item_channel_prices_updated_at
  ON public.menu_item_channel_prices;
CREATE TRIGGER trg_menu_item_channel_prices_updated_at
  BEFORE UPDATE ON public.menu_item_channel_prices
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE public.menu_item_channel_prices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_select ON public.menu_item_channel_prices;
CREATE POLICY tenant_select ON public.menu_item_channel_prices
  FOR SELECT TO authenticated
  USING (tenant_id = public.auth_tenant_id());

DROP POLICY IF EXISTS menu_item_channel_prices_insert ON public.menu_item_channel_prices;
CREATE POLICY menu_item_channel_prices_insert ON public.menu_item_channel_prices
  FOR INSERT TO authenticated
  WITH CHECK (
    tenant_id = public.auth_tenant_id()
    AND (SELECT public.has_permission_any('menu:write'::text))
  );

DROP POLICY IF EXISTS menu_item_channel_prices_update ON public.menu_item_channel_prices;
CREATE POLICY menu_item_channel_prices_update ON public.menu_item_channel_prices
  FOR UPDATE TO authenticated
  USING (
    tenant_id = public.auth_tenant_id()
    AND (SELECT public.has_permission_any('menu:write'::text))
  )
  WITH CHECK (
    tenant_id = public.auth_tenant_id()
    AND (SELECT public.has_permission_any('menu:write'::text))
  );

DROP POLICY IF EXISTS menu_item_channel_prices_delete ON public.menu_item_channel_prices;
CREATE POLICY menu_item_channel_prices_delete ON public.menu_item_channel_prices
  FOR DELETE TO authenticated
  USING (
    tenant_id = public.auth_tenant_id()
    AND (SELECT public.has_permission_any('menu:write'::text))
  );

GRANT SELECT, INSERT, UPDATE, DELETE ON public.menu_item_channel_prices TO authenticated;
GRANT ALL ON public.menu_item_channel_prices TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.menu_item_channel_prices_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.menu_item_channel_prices_id_seq TO service_role;

-- ---------------------------------------------------------------------------
-- 2. List-price helper (fail loud for missing delivery channel price)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.pos_resolve_item_list_price(
  p_tenant_id bigint,
  p_menu_item_id bigint,
  p_order_type text,
  p_delivery_platform text DEFAULT NULL
) RETURNS numeric
    LANGUAGE plpgsql
    STABLE
    SET search_path TO ''
AS $$
DECLARE
  v_base numeric(15, 2);
  v_channel numeric(15, 2);
BEGIN
  IF p_order_type = 'delivery' THEN
    IF p_delivery_platform IS NULL
      OR p_delivery_platform NOT IN ('grab', 'shopee', 'be', 'green_sm')
    THEN
      RAISE EXCEPTION 'delivery_platform_required' USING ERRCODE = '22023';
    END IF;

    SELECT cp.unit_price
      INTO v_channel
      FROM public.menu_item_channel_prices cp
     WHERE cp.tenant_id = p_tenant_id
       AND cp.menu_item_id = p_menu_item_id
       AND cp.delivery_platform = p_delivery_platform;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'channel_price_missing: menu_item=% platform=%',
        p_menu_item_id, p_delivery_platform
        USING ERRCODE = 'P0002';
    END IF;

    RETURN v_channel;
  END IF;

  SELECT mi.base_price
    INTO v_base
    FROM public.menu_items mi
   WHERE mi.id = p_menu_item_id
     AND mi.tenant_id = p_tenant_id
     AND mi.is_active = TRUE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Menu item % not found or inactive', p_menu_item_id
      USING ERRCODE = 'P0002';
  END IF;

  RETURN v_base;
END;
$$;

REVOKE ALL ON FUNCTION public.pos_resolve_item_list_price(bigint, bigint, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pos_resolve_item_list_price(bigint, bigint, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pos_resolve_item_list_price(bigint, bigint, text, text) TO service_role;

COMMENT ON FUNCTION public.pos_resolve_item_list_price(bigint, bigint, text, text) IS
  'POS list price: menu_items.base_price for dine_in/takeaway; menu_item_channel_prices.unit_price for delivery (no silent fallback).';

-- ---------------------------------------------------------------------------
-- 3. HĐĐT: allow platform tender (same auto-queue path as cash/VietQR)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION private.sync_tax_invoice_issue_job_for_payment(p_payment_id bigint) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO ''
AS $$
DECLARE
  v_payment public.payments%ROWTYPE;
  v_order public.orders%ROWTYPE;
  v_payload jsonb;
  v_request_payload jsonb;
  v_status text;
BEGIN
  SELECT * INTO v_payment
  FROM public.payments
  WHERE id = p_payment_id
  FOR UPDATE;
  IF NOT FOUND
    OR v_payment.method NOT IN ('vietqr', 'cash', 'platform')
  THEN
    RETURN;
  END IF;

  SELECT * INTO v_order
  FROM public.orders
  WHERE id = v_payment.order_id
    AND tenant_id = v_payment.tenant_id
    AND branch_id = v_payment.branch_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT request.invoice_payload INTO v_request_payload
  FROM public.self_order_payment_requests request
  WHERE request.tenant_id = v_payment.tenant_id
    AND request.branch_id = v_payment.branch_id
    AND request.order_id = v_payment.order_id
    AND request.payment_id = v_payment.id
    AND request.status IN ('cash_call', 'vietqr_pending', 'completed')
  ORDER BY request.id DESC
  LIMIT 1;

  v_payload := COALESCE(
    v_payment.provider_data -> 'invoiceSnapshot',
    v_payment.provider_data -> 'invoicePayload',
    v_request_payload
  );
  IF v_payload IS NULL THEN
    RETURN;
  END IF;

  IF v_payment.status NOT IN ('pending', 'completed')
    OR (
      v_payment.status = 'completed'
      AND (
        v_order.payment_status <> 'paid'
        OR v_order.status <> 'completed'
      )
    ) THEN
    RETURN;
  END IF;

  v_status := CASE
    WHEN v_payment.status = 'completed' THEN 'queued'
    ELSE 'pending_payment'
  END;

  PERFORM private.upsert_tax_invoice_issue_job(
    v_payment.tenant_id,
    v_payment.branch_id,
    v_payment.order_id,
    v_payment.id,
    v_payload,
    v_status
  );
END;
$$;

-- ---------------------------------------------------------------------------
-- 4. Print header: delivery/GH share Mang về lane label; GH sequence parse
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.print_template_order_header(p_payload jsonb) RETURNS text
    LANGUAGE plpgsql IMMUTABLE
    SET search_path TO 'public'
AS $_$
DECLARE
  v_order_number TEXT := btrim(
    COALESCE(
      NULLIF(p_payload->>'source_order_number', ''),
      NULLIF(p_payload->>'order_number', ''),
      ''
    )
  );
  v_clean_order_number TEXT;
  v_order_type TEXT := COALESCE(p_payload->>'order_type', '');
  v_table_number TEXT := NULLIF(btrim(COALESCE(p_payload->>'table_number', '')), '');
  v_platform TEXT := lower(NULLIF(btrim(COALESCE(p_payload->>'delivery_platform', '')), ''));
  v_external_ref TEXT := NULLIF(btrim(COALESCE(p_payload->>'external_order_ref', '')), '');
  v_prefix TEXT;
  v_label TEXT;
  v_match TEXT[];
  v_sequence TEXT;
  v_is_dine_in BOOLEAN;
  v_platform_label TEXT;
  v_header TEXT;
BEGIN
  v_clean_order_number := regexp_replace(v_order_number, '^#+', '');
  v_prefix := upper(split_part(v_clean_order_number, '-', 1));
  v_is_dine_in := v_order_type = 'dine_in'
    OR (v_order_type NOT IN ('takeaway', 'delivery') AND v_prefix = 'TC');

  v_label := CASE
    WHEN v_is_dine_in AND v_table_number IS NOT NULL THEN 'Bàn ' || v_table_number
    WHEN v_is_dine_in THEN 'Tại bàn'
    WHEN v_order_type IN ('takeaway', 'delivery') OR v_prefix IN ('MV', 'GH') THEN 'Mang về'
    ELSE 'Đơn'
  END;

  v_match := regexp_match(
    v_clean_order_number,
    '^(?:TC|MV|GH)-(?:(?:[0-9]{6}|[0-9]{8})-)?([0-9]{1,4})(?:-.+)?$',
    'i'
  );
  IF v_match IS NOT NULL THEN
    v_sequence := v_match[1];
  END IF;

  IF COALESCE(v_sequence, '') <> '' THEN
    v_header := v_label || ' #' || v_sequence;
  ELSIF v_clean_order_number <> '' THEN
    v_header := v_label || ' ' || v_clean_order_number;
  ELSE
    v_header := v_label;
  END IF;

  IF v_order_type = 'delivery' OR v_prefix = 'GH' THEN
    v_platform_label := CASE v_platform
      WHEN 'grab' THEN 'GRAB'
      WHEN 'shopee' THEN 'SHOPEEFOOD'
      WHEN 'be' THEN 'BEFOOD'
      WHEN 'green_sm' THEN 'GREEN SM'
      ELSE upper(COALESCE(v_platform, 'GIAO HANG'))
    END;
    IF v_external_ref IS NOT NULL THEN
      v_header := v_header || E'\n' || v_platform_label || ' ' || v_external_ref;
    ELSE
      v_header := v_header || E'\n' || v_platform_label;
    END IF;
  END IF;

  RETURN v_header;
END;
$_$;

-- ---------------------------------------------------------------------------
-- 5. create_order + hold wrapper (GH- prefix, delivery fields, channel price)
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.create_order_with_daily_limit_hold(
  bigint, bigint, uuid, jsonb, text, bigint, bigint, text, uuid, uuid
);
DROP FUNCTION IF EXISTS public.create_order(
  bigint, bigint, uuid, jsonb, text, bigint, bigint, text, uuid
);

CREATE FUNCTION public.create_order(
  p_tenant_id bigint,
  p_branch_id bigint,
  p_created_by uuid,
  p_items jsonb,
  p_order_type text DEFAULT 'dine_in'::text,
  p_table_id bigint DEFAULT NULL::bigint,
  p_pos_session_id bigint DEFAULT NULL::bigint,
  p_note text DEFAULT NULL::text,
  p_idempotency_key uuid DEFAULT NULL::uuid,
  p_delivery_platform text DEFAULT NULL::text,
  p_external_order_ref text DEFAULT NULL::text
) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
AS $$
DECLARE
  v_created_by       UUID;
  v_order_id         BIGINT;
  v_order_number     TEXT;
  v_date_part        TEXT;
  v_subtotal         NUMERIC(15,2) := 0;
  v_seq              INT;
  v_table_number     INT;
  v_item             JSONB;
  v_base_price       NUMERIC(15,2);
  v_variant_adj      NUMERIC(15,2);
  v_modifier_sum     NUMERIC(15,2);
  v_sides_sum        NUMERIC(15,2);
  v_enriched_sides   JSONB;
  v_unit_price       NUMERIC(15,2);
  v_item_subtotal    NUMERIC(15,2);
  v_menu_item_id     BIGINT;
  v_variant_id       BIGINT;
  v_quantity         INT;
  v_prof_tenant      BIGINT;
  v_prof_branch      BIGINT;
  v_prof_role        TEXT;
  v_branch_code      TEXT;
  v_item_discount    NUMERIC(15,2);
  v_platform         TEXT := NULLIF(lower(btrim(COALESCE(p_delivery_platform, ''))), '');
  v_external_ref     TEXT := NULLIF(btrim(COALESCE(p_external_order_ref, '')), '');
BEGIN
  v_created_by := auth.uid();
  IF v_created_by IS NULL THEN
    RAISE EXCEPTION 'unauthenticated' USING ERRCODE = '28000';
  END IF;

  SELECT p.tenant_id, p.branch_id, COALESCE(private.staff_role_from_position_code(po.code), 'unassigned')
    INTO v_prof_tenant, v_prof_branch, v_prof_role
    FROM public.profiles p
    LEFT JOIN public.positions po ON po.id = p.position_id
   WHERE p.id = v_created_by;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'profile not found' USING ERRCODE = '28000';
  END IF;

  IF v_prof_tenant IS DISTINCT FROM p_tenant_id THEN
    RAISE EXCEPTION 'tenant mismatch' USING ERRCODE = '42501';
  END IF;

  IF v_prof_role IN ('owner') THEN
    SELECT b.code INTO v_branch_code
      FROM public.branches b
     WHERE b.id = p_branch_id AND b.tenant_id = p_tenant_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'invalid branch' USING ERRCODE = 'P0002';
    END IF;
  ELSIF v_prof_branch IS NOT NULL THEN
    IF p_branch_id IS DISTINCT FROM v_prof_branch THEN
      RAISE EXCEPTION 'branch mismatch' USING ERRCODE = '42501';
    END IF;
    SELECT b.code INTO v_branch_code
      FROM public.branches b
     WHERE b.id = p_branch_id AND b.tenant_id = p_tenant_id;
  ELSE
    RAISE EXCEPTION 'branch scope required' USING ERRCODE = '42501';
  END IF;

  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'p_items must be a non-empty JSON array' USING ERRCODE = '22023';
  END IF;

  IF p_order_type NOT IN ('dine_in', 'takeaway', 'delivery') THEN
    RAISE EXCEPTION 'p_order_type must be dine_in, takeaway, or delivery' USING ERRCODE = '22023';
  END IF;

  IF p_order_type = 'delivery' THEN
    IF v_platform IS NULL OR v_platform NOT IN ('grab', 'shopee', 'be', 'green_sm') THEN
      RAISE EXCEPTION 'delivery_platform_required' USING ERRCODE = '22023';
    END IF;
    IF v_external_ref IS NULL THEN
      RAISE EXCEPTION 'external_order_ref_required' USING ERRCODE = '22023';
    END IF;
    IF p_table_id IS NOT NULL THEN
      RAISE EXCEPTION 'delivery_orders_forbid_table' USING ERRCODE = '22023';
    END IF;
  ELSE
    v_platform := NULL;
    v_external_ref := NULL;
  END IF;

  IF p_table_id IS NOT NULL THEN
    SELECT t.number INTO v_table_number
      FROM public.tables t
     WHERE t.id = p_table_id AND t.branch_id = p_branch_id AND t.tenant_id = p_tenant_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Table does not belong to this branch' USING ERRCODE = 'P0002';
    END IF;
  END IF;

  IF p_pos_session_id IS NOT NULL THEN
    PERFORM 1 FROM public.pos_sessions
     WHERE id = p_pos_session_id
       AND branch_id = p_branch_id
       AND tenant_id = p_tenant_id
       AND status = 'open';
    IF NOT FOUND THEN
      RAISE EXCEPTION 'POS session does not belong to this branch or is not open' USING ERRCODE = 'P0002';
    END IF;
  END IF;

  IF p_idempotency_key IS NOT NULL THEN
    SELECT o.id, o.order_number INTO v_order_id, v_order_number
      FROM public.orders o
     WHERE o.tenant_id = p_tenant_id
       AND o.idempotency_key = p_idempotency_key;
    IF FOUND THEN
      RETURN jsonb_build_object('order_id', v_order_id, 'order_number', v_order_number);
    END IF;
  END IF;

  INSERT INTO public.order_daily_counters (
    tenant_id, branch_id, counter_date, last_seq
  )
  VALUES (
    p_tenant_id,
    p_branch_id,
    (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh')::date,
    1
  )
  ON CONFLICT (tenant_id, branch_id, counter_date)
  DO UPDATE SET
    last_seq   = public.order_daily_counters.last_seq + 1,
    updated_at = now()
  RETURNING last_seq INTO v_seq;

  v_date_part := to_char(
    CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh',
    'YYMMDD'
  );

  IF p_order_type = 'dine_in' THEN
    v_order_number := 'TC-' || v_date_part || '-' || lpad(v_seq::TEXT, 3, '0');
  ELSIF p_order_type = 'delivery' THEN
    v_order_number := 'GH-' || v_date_part || '-' || lpad(v_seq::TEXT, 3, '0');
  ELSE
    v_order_number := 'MV-' || v_date_part || '-' || lpad(v_seq::TEXT, 3, '0');
  END IF;

  IF v_branch_code IS NOT NULL THEN
    v_order_number := v_order_number || '-' || v_branch_code;
  END IF;

  BEGIN
    INSERT INTO public.orders (
      tenant_id, branch_id, table_id, order_number, order_type,
      subtotal, total_amount, note, created_by,
      pos_session_id, idempotency_key,
      delivery_platform, external_order_ref
    )
    VALUES (
      p_tenant_id, p_branch_id, p_table_id, v_order_number, p_order_type,
      0, 0, p_note, v_created_by,
      p_pos_session_id, p_idempotency_key,
      v_platform, v_external_ref
    )
    RETURNING id INTO v_order_id;
  EXCEPTION
    WHEN unique_violation THEN
      IF p_idempotency_key IS NOT NULL THEN
        SELECT o.id, o.order_number INTO v_order_id, v_order_number
          FROM public.orders o
         WHERE o.tenant_id = p_tenant_id
           AND o.idempotency_key = p_idempotency_key;
        IF FOUND THEN
          RETURN jsonb_build_object('order_id', v_order_id, 'order_number', v_order_number);
        END IF;
      END IF;
      IF p_order_type = 'delivery' THEN
        RAISE EXCEPTION 'delivery_external_ref_duplicate' USING ERRCODE = '23505';
      END IF;
      RAISE;
  END;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items) AS value
  LOOP
    v_menu_item_id := (v_item ->> 'menu_item_id')::BIGINT;
    v_variant_id   := NULLIF(v_item ->> 'variant_id', '')::BIGINT;
    v_quantity     := (v_item ->> 'quantity')::INT;

    IF v_quantity IS NULL OR v_quantity < 1 THEN
      RAISE EXCEPTION 'invalid quantity' USING ERRCODE = '22023';
    END IF;

    v_base_price := public.pos_resolve_item_list_price(
      p_tenant_id,
      v_menu_item_id,
      p_order_type,
      v_platform
    );

    v_variant_adj := 0;
    IF v_variant_id IS NOT NULL THEN
      SELECT price_adjustment INTO v_variant_adj
        FROM public.menu_item_variants
       WHERE id = v_variant_id AND item_id = v_menu_item_id AND tenant_id = p_tenant_id AND is_active = TRUE;
      IF NOT FOUND THEN
        RAISE EXCEPTION 'Variant % not found or inactive', v_variant_id USING ERRCODE = 'P0002';
      END IF;
    END IF;

    v_modifier_sum := public.pos_order_modifier_sum(
      p_tenant_id,
      v_menu_item_id,
      COALESCE(v_item -> 'modifiers', '[]'::JSONB)
    );

    SELECT sides_sum, enriched_sides
      INTO v_sides_sum, v_enriched_sides
      FROM public.pos_enrich_order_sides(
        p_tenant_id,
        v_menu_item_id,
        COALESCE(v_item -> 'sides', '[]'::JSONB)
      );

    v_unit_price    := v_base_price + v_variant_adj + v_modifier_sum + COALESCE(v_sides_sum, 0);
    v_item_subtotal := v_unit_price * v_quantity;
    v_subtotal      := v_subtotal + v_item_subtotal;

    INSERT INTO public.order_items (
      tenant_id, order_id, menu_item_id, variant_id,
      item_name, variant_name, quantity, unit_price,
      modifiers, sides, subtotal, note,
      discount_type, discount_value, discount_note
    )
    VALUES (
      p_tenant_id, v_order_id, v_menu_item_id, v_variant_id,
      v_item ->> 'item_name', v_item ->> 'variant_name',
      v_quantity, v_unit_price,
      COALESCE(v_item -> 'modifiers', '[]'::JSONB),
      COALESCE(v_enriched_sides, '[]'::JSONB),
      v_item_subtotal, v_item ->> 'note',
      NULLIF(v_item ->> 'discount_type', ''),
      CASE WHEN NULLIF(v_item ->> 'discount_value', '') IS NOT NULL
           THEN (v_item ->> 'discount_value')::NUMERIC
           ELSE NULL END,
      NULLIF(trim(COALESCE(v_item ->> 'discount_note', '')), '')
    );
  END LOOP;

  UPDATE public.orders
     SET subtotal = v_subtotal, total_amount = v_subtotal
   WHERE id = v_order_id;

  INSERT INTO public.order_status_history (
    tenant_id, order_id, from_status, to_status, changed_by
  )
  VALUES (p_tenant_id, v_order_id, NULL, 'new', v_created_by);

  IF p_order_type = 'dine_in' AND p_table_id IS NOT NULL THEN
    UPDATE public.tables
       SET status = 'occupied'
     WHERE id = p_table_id AND branch_id = p_branch_id AND tenant_id = p_tenant_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Failed to update table status' USING ERRCODE = 'P0002';
    END IF;
  END IF;

  PERFORM public.route_order_to_kds(v_order_id);

  SELECT COALESCE(o.item_discount_amount, 0) INTO v_item_discount
    FROM public.orders o WHERE o.id = v_order_id;

  RETURN jsonb_build_object(
    'order_id', v_order_id,
    'order_number', v_order_number,
    'item_discount_amount', v_item_discount
  );
END;
$$;

CREATE FUNCTION public.create_order_with_daily_limit_hold(
  p_tenant_id bigint,
  p_branch_id bigint,
  p_created_by uuid,
  p_items jsonb,
  p_order_type text DEFAULT 'dine_in'::text,
  p_table_id bigint DEFAULT NULL::bigint,
  p_pos_session_id bigint DEFAULT NULL::bigint,
  p_note text DEFAULT NULL::text,
  p_idempotency_key uuid DEFAULT NULL::uuid,
  p_daily_limit_hold_token uuid DEFAULT NULL::uuid,
  p_delivery_platform text DEFAULT NULL::text,
  p_external_order_ref text DEFAULT NULL::text
) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_result jsonb;
  v_order_id bigint;
BEGIN
  IF p_daily_limit_hold_token IS NOT NULL THEN
    PERFORM set_config(
      'comtammatu.daily_limit_hold_token',
      p_daily_limit_hold_token::text,
      true
    );
  END IF;

  v_result := public.create_order(
    p_tenant_id,
    p_branch_id,
    p_created_by,
    p_items,
    p_order_type,
    p_table_id,
    p_pos_session_id,
    p_note,
    p_idempotency_key,
    p_delivery_platform,
    p_external_order_ref
  );

  v_order_id := NULLIF(v_result ->> 'order_id', '')::bigint;

  IF p_daily_limit_hold_token IS NOT NULL AND v_order_id IS NOT NULL THEN
    UPDATE public.branch_menu_item_daily_holds h
    SET committed_at = COALESCE(h.committed_at, now()),
        order_id = COALESCE(h.order_id, v_order_id),
        updated_at = now()
    WHERE h.tenant_id = p_tenant_id
      AND h.branch_id = p_branch_id
      AND h.hold_token = p_daily_limit_hold_token
      AND h.held_by = v_uid
      AND h.committed_at IS NULL
      AND h.released_at IS NULL
      AND h.expires_at > now();
  END IF;

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.create_order(
  bigint, bigint, uuid, jsonb, text, bigint, bigint, text, uuid, text, text
) FROM PUBLIC;
GRANT ALL ON FUNCTION public.create_order(
  bigint, bigint, uuid, jsonb, text, bigint, bigint, text, uuid, text, text
) TO authenticated;
GRANT ALL ON FUNCTION public.create_order(
  bigint, bigint, uuid, jsonb, text, bigint, bigint, text, uuid, text, text
) TO service_role;

REVOKE ALL ON FUNCTION public.create_order_with_daily_limit_hold(
  bigint, bigint, uuid, jsonb, text, bigint, bigint, text, uuid, uuid, text, text
) FROM PUBLIC;
GRANT ALL ON FUNCTION public.create_order_with_daily_limit_hold(
  bigint, bigint, uuid, jsonb, text, bigint, bigint, text, uuid, uuid, text, text
) TO authenticated;
GRANT ALL ON FUNCTION public.create_order_with_daily_limit_hold(
  bigint, bigint, uuid, jsonb, text, bigint, bigint, text, uuid, uuid, text, text
) TO service_role;

-- ---------------------------------------------------------------------------
-- 6. append_order_items uses channel list price for delivery orders
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.append_order_items(
  p_order_id bigint,
  p_items jsonb,
  p_idempotency_key uuid DEFAULT NULL::uuid
) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
AS $$
DECLARE
  v_uid             UUID;
  v_prof_tenant     BIGINT;
  v_prof_branch     BIGINT;
  v_prof_role       TEXT;
  v_order           RECORD;
  v_item            JSONB;
  v_base_price      NUMERIC(15,2);
  v_variant_adj     NUMERIC(15,2);
  v_modifier_sum    NUMERIC(15,2);
  v_sides_sum       NUMERIC(15,2);
  v_enriched_sides  JSONB;
  v_unit_price      NUMERIC(15,2);
  v_item_subtotal   NUMERIC(15,2);
  v_menu_item_id    BIGINT;
  v_variant_id      BIGINT;
  v_quantity        INT;
  v_subtotal        NUMERIC(15,2);
  v_discount_amount NUMERIC(15,2);
  v_total_amount    NUMERIC(15,2);
  v_item_discount   NUMERIC(15,2);
  v_note_parts      TEXT[] := ARRAY[]::TEXT[];
  v_item_name       TEXT;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'unauthenticated' USING ERRCODE = '28000';
  END IF;

  SELECT p.tenant_id, p.branch_id, COALESCE(private.staff_role_from_position_code(po.code), 'unassigned')
  INTO v_prof_tenant, v_prof_branch, v_prof_role
  FROM public.profiles p
  LEFT JOIN public.positions po ON po.id = p.position_id
  WHERE p.id = v_uid;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'profile not found' USING ERRCODE = '28000';
  END IF;

  PERFORM pg_advisory_xact_lock(p_order_id);

  IF p_idempotency_key IS NOT NULL THEN
    IF EXISTS (
      SELECT 1 FROM public.order_items
      WHERE order_id = p_order_id
        AND request_key = p_idempotency_key
      LIMIT 1
    ) THEN
      SELECT o.subtotal, o.total_amount
      INTO v_subtotal, v_total_amount
      FROM public.orders o
      WHERE o.id = p_order_id;

      RETURN jsonb_build_object(
        'success',      TRUE,
        'order_id',     p_order_id,
        'added_count',  0,
        'subtotal',     COALESCE(v_subtotal, 0),
        'total_amount', COALESCE(v_total_amount, 0),
        'idempotent',   TRUE
      );
    END IF;
  END IF;

  SELECT o.id, o.tenant_id, o.branch_id, o.status, o.payment_status, o.service_charge,
         o.discount_type, o.discount_value, o.order_type, o.delivery_platform
  INTO v_order
  FROM public.orders o
  WHERE o.id = p_order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'order not found' USING ERRCODE = 'P0002';
  END IF;

  IF v_order.tenant_id <> v_prof_tenant THEN
    RAISE EXCEPTION 'tenant mismatch' USING ERRCODE = '42501';
  END IF;

  IF v_prof_role IN ('owner') THEN
    PERFORM 1 FROM public.branches b
    WHERE b.id = v_order.branch_id AND b.tenant_id = v_prof_tenant;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'invalid branch' USING ERRCODE = 'P0002';
    END IF;
  ELSIF v_prof_branch IS NOT NULL THEN
    IF v_order.branch_id IS DISTINCT FROM v_prof_branch THEN
      RAISE EXCEPTION 'branch mismatch' USING ERRCODE = '42501';
    END IF;
  ELSE
    RAISE EXCEPTION 'branch scope required' USING ERRCODE = '42501';
  END IF;

  IF v_order.status NOT IN ('new', 'confirmed', 'preparing', 'ready', 'served') THEN
    RAISE EXCEPTION 'order not appendable' USING ERRCODE = '22023';
  END IF;

  IF COALESCE(v_order.payment_status, 'unpaid') = 'paid' THEN
    RAISE EXCEPTION 'order not appendable' USING ERRCODE = '22023';
  END IF;

  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'p_items must be a non-empty JSON array' USING ERRCODE = '22023';
  END IF;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items) AS value
  LOOP
    v_menu_item_id := (v_item ->> 'menu_item_id')::BIGINT;
    v_variant_id := NULLIF(v_item ->> 'variant_id', '')::BIGINT;
    v_quantity := (v_item ->> 'quantity')::INT;

    IF v_quantity IS NULL OR v_quantity < 1 THEN
      RAISE EXCEPTION 'invalid quantity' USING ERRCODE = '22023';
    END IF;

    v_base_price := public.pos_resolve_item_list_price(
      v_order.tenant_id,
      v_menu_item_id,
      v_order.order_type,
      v_order.delivery_platform
    );

    v_variant_adj := 0;
    IF v_variant_id IS NOT NULL THEN
      SELECT price_adjustment INTO v_variant_adj
      FROM public.menu_item_variants
      WHERE id = v_variant_id AND item_id = v_menu_item_id AND tenant_id = v_order.tenant_id AND is_active = TRUE;
      IF NOT FOUND THEN
        RAISE EXCEPTION 'Variant % not found or inactive', v_variant_id USING ERRCODE = 'P0002';
      END IF;
    END IF;

    v_modifier_sum := public.pos_order_modifier_sum(
      v_order.tenant_id,
      v_menu_item_id,
      COALESCE(v_item -> 'modifiers', '[]'::JSONB)
    );

    SELECT sides_sum, enriched_sides
    INTO v_sides_sum, v_enriched_sides
    FROM public.pos_enrich_order_sides(
      v_order.tenant_id,
      v_menu_item_id,
      COALESCE(v_item -> 'sides', '[]'::JSONB)
    );

    v_unit_price := v_base_price + v_variant_adj + v_modifier_sum + COALESCE(v_sides_sum, 0);
    v_item_subtotal := v_unit_price * v_quantity;

    v_item_name := v_item ->> 'item_name';
    IF v_item_name IS NOT NULL AND length(trim(v_item_name)) > 0 THEN
      v_note_parts := array_append(v_note_parts, v_item_name);
    END IF;

    INSERT INTO public.order_items (
      tenant_id, order_id, menu_item_id, variant_id,
      item_name, variant_name, quantity, unit_price,
      modifiers, sides, subtotal, note, status, request_key,
      discount_type, discount_value, discount_note
    )
    VALUES (
      v_order.tenant_id, p_order_id, v_menu_item_id, v_variant_id,
      COALESCE(v_item ->> 'item_name', 'Mon'),
      v_item ->> 'variant_name',
      v_quantity, v_unit_price,
      COALESCE(v_item -> 'modifiers', '[]'::JSONB),
      COALESCE(v_enriched_sides, '[]'::JSONB),
      v_item_subtotal, v_item ->> 'note', 'pending',
      p_idempotency_key,
      NULLIF(v_item ->> 'discount_type', ''),
      CASE WHEN NULLIF(v_item ->> 'discount_value', '') IS NOT NULL
           THEN (v_item ->> 'discount_value')::NUMERIC
           ELSE NULL END,
      NULLIF(trim(COALESCE(v_item ->> 'discount_note', '')), '')
    );
  END LOOP;

  SELECT COALESCE(SUM(subtotal), 0) INTO v_subtotal
  FROM public.order_items
  WHERE order_id = p_order_id AND status <> 'cancelled';

  v_discount_amount := public.compute_discount_amount(
    v_order.discount_type, v_order.discount_value, v_subtotal
  );

  v_total_amount := v_subtotal
                  + COALESCE(v_order.service_charge, 0)
                  - v_discount_amount;

  UPDATE public.orders o
  SET
    subtotal        = v_subtotal,
    tax_amount      = 0,
    discount_amount = v_discount_amount,
    total_amount    = v_total_amount,
    updated_at      = now()
  WHERE o.id = p_order_id;

  INSERT INTO public.order_status_history (
    tenant_id, order_id, from_status, to_status, changed_by, note
  )
  VALUES (
    v_order.tenant_id,
    p_order_id,
    v_order.status,
    v_order.status,
    v_uid,
    'items_added: ' || COALESCE(array_to_string(v_note_parts, ', '), 'items')
  );

  PERFORM public.route_order_to_kds(p_order_id);

  SELECT o.subtotal, o.total_amount, COALESCE(o.item_discount_amount, 0)
  INTO v_subtotal, v_total_amount, v_item_discount
  FROM public.orders o
  WHERE o.id = p_order_id;

  RETURN jsonb_build_object(
    'success',              TRUE,
    'order_id',             p_order_id,
    'added_count',          jsonb_array_length(p_items),
    'subtotal',             v_subtotal,
    'total_amount',         v_total_amount,
    'item_discount_amount', v_item_discount
  );
END;
$$;

-- ---------------------------------------------------------------------------
-- 7. confirm_platform_payment (+ invoice binding twin for HĐĐT khách lẻ)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.confirm_platform_payment(p_order_id bigint) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO ''
AS $$
DECLARE
  v_uid uuid;
  v_order public.orders%ROWTYPE;
  v_existing_id bigint;
  v_existing_st text;
  v_existing_method text;
  v_existing_provider_ref text;
  v_payment_id bigint;
  v_provider_ref text;
  v_complete_res record;
  v_receipt_res jsonb;
  v_print_warning text;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'unauthenticated' USING ERRCODE = '28000';
  END IF;

  PERFORM pg_advisory_xact_lock(p_order_id);

  SELECT * INTO v_order
  FROM public.orders
  WHERE id = p_order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'order not found' USING ERRCODE = 'P0002';
  END IF;

  IF v_order.tenant_id IS DISTINCT FROM public.auth_tenant_id() THEN
    RAISE EXCEPTION 'tenant mismatch' USING ERRCODE = '42501';
  END IF;

  IF NOT public.has_permission(v_order.branch_id, 'pos:confirm_payment') THEN
    RAISE EXCEPTION 'permission denied: pos:confirm_payment' USING ERRCODE = '42501';
  END IF;

  IF v_order.order_type IS DISTINCT FROM 'delivery' THEN
    RAISE EXCEPTION 'platform_payment_requires_delivery' USING ERRCODE = '22023';
  END IF;

  IF v_order.payment_status = 'paid' THEN
    SELECT id INTO v_payment_id
    FROM public.payments
    WHERE order_id = p_order_id
      AND tenant_id = v_order.tenant_id
      AND status = 'completed'
    ORDER BY id DESC
    LIMIT 1;

    RETURN jsonb_build_object(
      'status',       'already_completed',
      'order_id',     p_order_id,
      'payment_id',   v_payment_id,
      'print_job_id', NULL,
      'idempotent',   true
    );
  END IF;

  v_provider_ref := upper(v_order.payment_code);

  SELECT id, status, method, provider_ref
  INTO v_existing_id, v_existing_st, v_existing_method, v_existing_provider_ref
  FROM public.payments
  WHERE order_id = p_order_id
    AND tenant_id = v_order.tenant_id
    AND status <> 'failed'
  ORDER BY id DESC
  LIMIT 1
  FOR UPDATE;

  IF v_existing_st = 'completed' THEN
    RETURN jsonb_build_object(
      'status',       'already_completed',
      'order_id',     p_order_id,
      'payment_id',   v_existing_id,
      'print_job_id', NULL,
      'idempotent',   true
    );
  END IF;

  IF v_existing_st = 'pending' AND v_existing_method = 'momo' THEN
    RAISE EXCEPTION 'pending_momo_payment_requires_provider_resolution'
      USING ERRCODE = '55P03';
  END IF;

  IF v_existing_id IS NOT NULL THEN
    UPDATE public.payments
       SET method        = 'platform',
           amount        = v_order.total_amount,
           status        = 'pending',
           provider_ref  = COALESCE(v_provider_ref, v_existing_provider_ref),
           provider_data = COALESCE(provider_data, '{}'::jsonb)
                           || jsonb_build_object(
                             'description', COALESCE(v_provider_ref, v_existing_provider_ref),
                             'delivery_platform', v_order.delivery_platform,
                             'external_order_ref', v_order.external_order_ref
                           ),
           updated_at    = now()
     WHERE id = v_existing_id;
    v_payment_id := v_existing_id;
  ELSE
    INSERT INTO public.payments (
      tenant_id, branch_id, order_id, method, amount, status, provider_ref, provider_data, created_by
    ) VALUES (
      v_order.tenant_id, v_order.branch_id, p_order_id, 'platform',
      v_order.total_amount, 'pending', v_provider_ref,
      jsonb_build_object(
        'description', v_provider_ref,
        'delivery_platform', v_order.delivery_platform,
        'external_order_ref', v_order.external_order_ref
      ),
      v_uid
    )
    RETURNING id INTO v_payment_id;
  END IF;

  UPDATE public.orders
     SET payment_method = 'platform',
         updated_at     = now()
   WHERE id = p_order_id;

  SELECT * INTO v_complete_res
  FROM public.complete_payment_and_consume_stock(
    v_payment_id,
    v_order.total_amount,
    '{}'::jsonb,
    v_uid
  );

  IF v_complete_res.status = 'stock_failed' THEN
    RETURN jsonb_build_object(
      'status',      'stock_failed',
      'order_id',    p_order_id,
      'payment_id',  v_payment_id,
      'error_code',  'stock_consumption_failed',
      'detail',      v_complete_res.detail
    );
  END IF;

  IF v_complete_res.status = 'amount_mismatch_recomputed' THEN
    RETURN jsonb_build_object(
      'status',      'amount_mismatch_recomputed',
      'order_id',    p_order_id,
      'payment_id',  v_payment_id,
      'error_code',  'amount_mismatch_recomputed',
      'detail',      v_complete_res.detail
    );
  END IF;

  IF v_complete_res.status NOT IN ('completed', 'already_completed') THEN
    RAISE EXCEPTION 'payment completion failed: % (detail: %)',
      v_complete_res.status, v_complete_res.detail
      USING ERRCODE = 'P0001';
  END IF;

  BEGIN
    v_receipt_res := public.enqueue_receipt_print(p_order_id, NULL, NULL);
  EXCEPTION WHEN OTHERS THEN
    v_print_warning := 'receipt_enqueue_failed';
    v_receipt_res := '{}'::jsonb;
    RAISE LOG '[confirm_platform_payment] receipt enqueue skipped for order %: %',
      p_order_id, SQLERRM;
  END;

  RETURN jsonb_build_object(
    'status',        'completed',
    'order_id',      p_order_id,
    'payment_id',    v_payment_id,
    'print_job_id',  v_receipt_res->>'job_id',
    'print_warning', v_print_warning
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.confirm_platform_payment_with_invoice_binding(
  p_order_id bigint,
  p_invoice_payload jsonb
) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO ''
AS $$
DECLARE
  v_result jsonb;
  v_payment_id bigint;
  v_order public.orders%ROWTYPE;
  v_payload jsonb;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  v_payload := public.self_order_normalize_invoice_payload(p_invoice_payload);
  v_result := public.confirm_platform_payment(p_order_id);
  v_payment_id := NULLIF(v_result ->> 'payment_id', '')::bigint;

  IF v_result ->> 'status' NOT IN ('completed', 'already_completed')
    OR v_payment_id IS NULL THEN
    RETURN v_result;
  END IF;

  SELECT * INTO v_order
  FROM public.orders
  WHERE id = p_order_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'tax_invoice_issue_order_not_found' USING ERRCODE = 'P0002';
  END IF;

  UPDATE public.payments
     SET provider_data = COALESCE(provider_data, '{}'::jsonb)
                         || jsonb_build_object('invoiceSnapshot', v_payload),
         updated_at = now()
   WHERE id = v_payment_id
     AND tenant_id = v_order.tenant_id;

  PERFORM private.upsert_tax_invoice_issue_job(
    v_order.tenant_id,
    v_order.branch_id,
    v_order.id,
    v_payment_id,
    v_payload,
    'queued'
  );

  RETURN v_result || jsonb_build_object('tax_invoice_job_status', 'queued');
END;
$$;

REVOKE ALL ON FUNCTION public.confirm_platform_payment(bigint) FROM PUBLIC;
GRANT ALL ON FUNCTION public.confirm_platform_payment(bigint) TO authenticated;
GRANT ALL ON FUNCTION public.confirm_platform_payment(bigint) TO service_role;

REVOKE ALL ON FUNCTION public.confirm_platform_payment_with_invoice_binding(bigint, jsonb) FROM PUBLIC;
GRANT ALL ON FUNCTION public.confirm_platform_payment_with_invoice_binding(bigint, jsonb) TO authenticated;
GRANT ALL ON FUNCTION public.confirm_platform_payment_with_invoice_binding(bigint, jsonb) TO service_role;

COMMENT ON FUNCTION public.confirm_platform_payment(bigint) IS
  'Completes delivery platform prepaid tender (Công Cụ Quản Lý). Sales GROSS; not cash drawer.';

COMMENT ON FUNCTION public.confirm_platform_payment_with_invoice_binding(bigint, jsonb) IS
  'Platform prepaid confirm plus HĐĐT snapshot/queue (khách lẻ), same auto-queue path as cash.';

-- ---------------------------------------------------------------------------
-- 8. Revenue KPIs / rollup: delivery_revenue + platform_revenue (GROSS)
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.get_revenue_kpis(bigint, date, date);
DROP FUNCTION IF EXISTS public.get_revenue_rollup(bigint, date, date, text);

CREATE FUNCTION public.get_revenue_kpis(
  p_branch_id bigint,
  p_start_date date,
  p_end_date date
) RETURNS TABLE(
  net_revenue numeric,
  subtotal_revenue numeric,
  discount_amount numeric,
  total_tax numeric,
  vat_by_rate jsonb,
  vat_total numeric,
  order_count bigint,
  total_covers bigint,
  cash_revenue numeric,
  vietqr_revenue numeric,
  platform_revenue numeric,
  dine_in_revenue numeric,
  takeaway_revenue numeric,
  delivery_revenue numeric,
  voided_amount numeric,
  voided_count bigint,
  refreshed_at timestamp with time zone
)
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_start_utc timestamptz;
  v_end_utc timestamptz;
  v_has_tenant_scope boolean;
  v_branch_ids bigint[];
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  IF p_start_date IS NULL
    OR p_end_date IS NULL
    OR p_start_date > p_end_date
  THEN
    RAISE EXCEPTION 'invalid_date_range' USING ERRCODE = '22023';
  END IF;

  SELECT scope.has_tenant_scope, scope.branch_ids
  INTO v_has_tenant_scope, v_branch_ids
  FROM private.finance_scope(v_uid, 'finance:view') scope;

  IF p_branch_id IS NULL THEN
    IF NOT (
      v_has_tenant_scope
      OR COALESCE(cardinality(v_branch_ids), 0) > 0
    ) THEN
      RAISE EXCEPTION 'not_allowed' USING ERRCODE = '42501';
    END IF;
  ELSIF NOT (
    v_has_tenant_scope
    OR p_branch_id = ANY(COALESCE(v_branch_ids, ARRAY[]::bigint[]))
  ) THEN
    RAISE EXCEPTION 'not_allowed' USING ERRCODE = '42501';
  END IF;

  v_start_utc :=
    p_start_date::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh';
  v_end_utc :=
    (p_end_date + 1)::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh';

  RETURN QUERY
  WITH paid AS MATERIALIZED (
    SELECT
      payment.id AS payment_id,
      payment.order_id,
      payment.branch_id,
      payment.tenant_id,
      payment.method,
      payment.amount AS payment_amount,
      payment.paid_at,
      orders.total_amount,
      orders.subtotal,
      orders.discount_amount,
      orders.tax_amount,
      orders.order_type
    FROM public.payments payment
    JOIN public.orders orders
      ON orders.id = payment.order_id
     AND orders.tenant_id = payment.tenant_id
     AND orders.branch_id = payment.branch_id
    WHERE payment.tenant_id = v_tenant
      AND payment.status = 'completed'
      AND payment.paid_at >= v_start_utc
      AND payment.paid_at < v_end_utc
      AND (
        (p_branch_id IS NOT NULL AND payment.branch_id = p_branch_id)
        OR (
          p_branch_id IS NULL
          AND (
            v_has_tenant_scope
            OR payment.branch_id = ANY(
              COALESCE(v_branch_ids, ARRAY[]::bigint[])
            )
          )
        )
      )
  ),
  order_facts AS MATERIALIZED (
    SELECT DISTINCT ON (paid.tenant_id, paid.branch_id, paid.order_id)
      paid.order_id AS id,
      paid.tenant_id,
      paid.branch_id,
      paid.total_amount,
      paid.subtotal,
      paid.discount_amount,
      paid.tax_amount,
      paid.order_type
    FROM paid
    ORDER BY
      paid.tenant_id,
      paid.branch_id,
      paid.order_id,
      paid.paid_at,
      paid.payment_id
  ),
  payment_sales AS (
    SELECT
      COALESCE(sum(paid.payment_amount), 0)::numeric AS net_revenue,
      COALESCE(sum(paid.payment_amount) FILTER (
        WHERE paid.method = 'cash'
      ), 0)::numeric AS cash_revenue,
      COALESCE(sum(paid.payment_amount) FILTER (
        WHERE paid.method = 'vietqr'
      ), 0)::numeric AS vietqr_revenue,
      COALESCE(sum(paid.payment_amount) FILTER (
        WHERE paid.method = 'platform'
      ), 0)::numeric AS platform_revenue,
      COALESCE(sum(paid.payment_amount) FILTER (
        WHERE paid.order_type = 'dine_in'
      ), 0)::numeric AS dine_in_revenue,
      COALESCE(sum(paid.payment_amount) FILTER (
        WHERE paid.order_type = 'takeaway'
      ), 0)::numeric AS takeaway_revenue,
      COALESCE(sum(paid.payment_amount) FILTER (
        WHERE paid.order_type = 'delivery'
      ), 0)::numeric AS delivery_revenue
    FROM paid
  ),
  order_sales AS (
    SELECT
      COALESCE(sum(fact.subtotal), 0)::numeric AS subtotal_revenue,
      COALESCE(sum(fact.discount_amount), 0)::numeric AS discount_amount,
      COALESCE(sum(fact.tax_amount), 0)::numeric AS total_tax,
      count(*)::bigint AS order_count
    FROM order_facts fact
  ),
  vat_lines AS (
    SELECT
      round(item.vat_rate::numeric, 2) AS rate,
      sum(
        (item.subtotal * scale.scale)
          - (
            (item.subtotal * scale.scale)
              / (1 + item.vat_rate / 100)
          )
      ) AS vat
    FROM (
      SELECT
        fact.id AS order_id,
        fact.tenant_id,
        CASE
          WHEN sum(item.subtotal) > 0
            THEN fact.total_amount / sum(item.subtotal)
          ELSE 1
        END AS scale
      FROM order_facts fact
      JOIN public.order_items item
        ON item.tenant_id = fact.tenant_id
       AND item.order_id = fact.id
       AND item.status <> 'cancelled'
      GROUP BY fact.id, fact.tenant_id, fact.total_amount
    ) scale
    JOIN public.order_items item
      ON item.tenant_id = scale.tenant_id
     AND item.order_id = scale.order_id
     AND item.status <> 'cancelled'
    GROUP BY round(item.vat_rate::numeric, 2)
  ),
  vat_split AS (
    SELECT
      COALESCE(
        jsonb_object_agg(vat_lines.rate::text, vat_lines.vat),
        '{}'::jsonb
      ) AS vat_by_rate,
      COALESCE(sum(vat_lines.vat), 0)::numeric AS vat_total
    FROM vat_lines
  ),
  refunds AS (
    SELECT
      COALESCE(sum(payment.amount), 0)::numeric AS voided_amount,
      count(DISTINCT payment.order_id)::bigint AS voided_count
    FROM public.payments payment
    WHERE payment.tenant_id = v_tenant
      AND payment.status = 'refunded'
      AND payment.paid_at >= v_start_utc
      AND payment.paid_at < v_end_utc
      AND (
        (p_branch_id IS NOT NULL AND payment.branch_id = p_branch_id)
        OR (
          p_branch_id IS NULL
          AND (
            v_has_tenant_scope
            OR payment.branch_id = ANY(
              COALESCE(v_branch_ids, ARRAY[]::bigint[])
            )
          )
        )
      )
  )
  SELECT
    payment_sales.net_revenue,
    order_sales.subtotal_revenue,
    order_sales.discount_amount,
    order_sales.total_tax,
    vat_split.vat_by_rate,
    vat_split.vat_total,
    order_sales.order_count,
    order_sales.order_count,
    payment_sales.cash_revenue,
    payment_sales.vietqr_revenue,
    payment_sales.platform_revenue,
    payment_sales.dine_in_revenue,
    payment_sales.takeaway_revenue,
    payment_sales.delivery_revenue,
    refunds.voided_amount,
    refunds.voided_count,
    now()
  FROM payment_sales
  CROSS JOIN order_sales
  CROSS JOIN vat_split
  CROSS JOIN refunds;
END;
$$;

CREATE FUNCTION public.get_revenue_rollup(
  p_branch_id bigint,
  p_start_date date,
  p_end_date date,
  p_granularity text
) RETURNS TABLE(
  period_start date,
  period_end date,
  period_label text,
  branch_id bigint,
  order_count bigint,
  total_revenue numeric,
  total_tax numeric,
  subtotal_revenue numeric,
  discount_amount numeric,
  cash_revenue numeric,
  vietqr_revenue numeric,
  platform_revenue numeric,
  dine_in_revenue numeric,
  takeaway_revenue numeric,
  delivery_revenue numeric,
  total_covers bigint
)
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_start_utc timestamptz;
  v_end_utc timestamptz;
  v_has_tenant_scope boolean;
  v_branch_ids bigint[];
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  IF p_granularity NOT IN ('day', 'week', 'month')
    OR p_start_date IS NULL
    OR p_end_date IS NULL
    OR p_start_date > p_end_date
  THEN
    RAISE EXCEPTION 'invalid_revenue_scope' USING ERRCODE = '22023';
  END IF;

  SELECT scope.has_tenant_scope, scope.branch_ids
  INTO v_has_tenant_scope, v_branch_ids
  FROM private.finance_scope(v_uid, 'finance:view') scope;

  IF p_branch_id IS NULL THEN
    IF NOT (
      v_has_tenant_scope
      OR COALESCE(cardinality(v_branch_ids), 0) > 0
    ) THEN
      RAISE EXCEPTION 'not_allowed' USING ERRCODE = '42501';
    END IF;
  ELSIF NOT (
    v_has_tenant_scope
    OR p_branch_id = ANY(COALESCE(v_branch_ids, ARRAY[]::bigint[]))
  ) THEN
    RAISE EXCEPTION 'not_allowed' USING ERRCODE = '42501';
  END IF;

  v_start_utc :=
    p_start_date::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh';
  v_end_utc :=
    (p_end_date + 1)::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh';

  RETURN QUERY
  WITH paid AS MATERIALIZED (
    SELECT
      CASE p_granularity
        WHEN 'day' THEN (
          payment.paid_at AT TIME ZONE 'Asia/Ho_Chi_Minh'
        )::date
        WHEN 'week' THEN date_trunc(
          'week',
          payment.paid_at AT TIME ZONE 'Asia/Ho_Chi_Minh'
        )::date
        WHEN 'month' THEN date_trunc(
          'month',
          payment.paid_at AT TIME ZONE 'Asia/Ho_Chi_Minh'
        )::date
      END AS bucket_start,
      payment.id AS payment_id,
      payment.order_id,
      payment.branch_id,
      payment.tenant_id,
      payment.method,
      payment.amount,
      payment.paid_at,
      orders.total_amount,
      orders.tax_amount,
      orders.subtotal,
      orders.discount_amount,
      orders.order_type
    FROM public.payments payment
    JOIN public.orders orders
      ON orders.id = payment.order_id
     AND orders.tenant_id = payment.tenant_id
     AND orders.branch_id = payment.branch_id
    WHERE payment.tenant_id = v_tenant
      AND payment.status = 'completed'
      AND payment.paid_at >= v_start_utc
      AND payment.paid_at < v_end_utc
      AND (
        (p_branch_id IS NOT NULL AND payment.branch_id = p_branch_id)
        OR (
          p_branch_id IS NULL
          AND (
            v_has_tenant_scope
            OR payment.branch_id = ANY(
              COALESCE(v_branch_ids, ARRAY[]::bigint[])
            )
          )
        )
      )
  ),
  payment_buckets AS (
    SELECT
      paid.bucket_start,
      paid.branch_id,
      COALESCE(sum(paid.amount), 0)::numeric AS total_revenue,
      COALESCE(sum(paid.amount) FILTER (
        WHERE paid.method = 'cash'
      ), 0)::numeric AS cash_revenue,
      COALESCE(sum(paid.amount) FILTER (
        WHERE paid.method = 'vietqr'
      ), 0)::numeric AS vietqr_revenue,
      COALESCE(sum(paid.amount) FILTER (
        WHERE paid.method = 'platform'
      ), 0)::numeric AS platform_revenue,
      COALESCE(sum(paid.amount) FILTER (
        WHERE paid.order_type = 'dine_in'
      ), 0)::numeric AS dine_in_revenue,
      COALESCE(sum(paid.amount) FILTER (
        WHERE paid.order_type = 'takeaway'
      ), 0)::numeric AS takeaway_revenue,
      COALESCE(sum(paid.amount) FILTER (
        WHERE paid.order_type = 'delivery'
      ), 0)::numeric AS delivery_revenue
    FROM paid
    GROUP BY paid.bucket_start, paid.branch_id
  ),
  order_facts AS (
    SELECT DISTINCT ON (
      paid.bucket_start,
      paid.branch_id,
      paid.tenant_id,
      paid.order_id
    )
      paid.bucket_start,
      paid.branch_id,
      paid.tenant_id,
      paid.order_id,
      paid.tax_amount,
      paid.subtotal,
      paid.discount_amount
    FROM paid
    ORDER BY
      paid.bucket_start,
      paid.branch_id,
      paid.tenant_id,
      paid.order_id,
      paid.paid_at,
      paid.payment_id
  ),
  order_buckets AS (
    SELECT
      fact.bucket_start,
      fact.branch_id,
      count(*)::bigint AS order_count,
      COALESCE(sum(fact.tax_amount), 0)::numeric AS total_tax,
      COALESCE(sum(fact.subtotal), 0)::numeric AS subtotal_revenue,
      COALESCE(sum(fact.discount_amount), 0)::numeric AS discount_amount
    FROM order_facts fact
    GROUP BY fact.bucket_start, fact.branch_id
  )
  SELECT
    payment.bucket_start,
    CASE p_granularity
      WHEN 'day' THEN payment.bucket_start
      WHEN 'week' THEN payment.bucket_start + 6
      WHEN 'month' THEN (
        payment.bucket_start + INTERVAL '1 month - 1 day'
      )::date
    END,
    CASE p_granularity
      WHEN 'day' THEN to_char(payment.bucket_start, 'DD/MM/YYYY')
      WHEN 'week' THEN
        'Tuần ' || to_char(payment.bucket_start, 'IW') || ' ('
          || to_char(payment.bucket_start, 'DD/MM') || '-'
          || to_char(payment.bucket_start + 6, 'DD/MM/YYYY') || ')'
      WHEN 'month' THEN
        'Tháng ' || to_char(payment.bucket_start, 'MM/YYYY')
    END,
    payment.branch_id,
    orders.order_count,
    payment.total_revenue,
    orders.total_tax,
    orders.subtotal_revenue,
    orders.discount_amount,
    payment.cash_revenue,
    payment.vietqr_revenue,
    payment.platform_revenue,
    payment.dine_in_revenue,
    payment.takeaway_revenue,
    payment.delivery_revenue,
    orders.order_count
  FROM payment_buckets payment
  JOIN order_buckets orders
    ON orders.bucket_start = payment.bucket_start
   AND orders.branch_id = payment.branch_id
  ORDER BY payment.bucket_start, payment.branch_id;
END;
$$;

REVOKE ALL ON FUNCTION public.get_revenue_kpis(bigint, date, date) FROM PUBLIC;
GRANT ALL ON FUNCTION public.get_revenue_kpis(bigint, date, date) TO authenticated;
GRANT ALL ON FUNCTION public.get_revenue_kpis(bigint, date, date) TO service_role;

REVOKE ALL ON FUNCTION public.get_revenue_rollup(bigint, date, date, text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.get_revenue_rollup(bigint, date, date, text) TO authenticated;
GRANT ALL ON FUNCTION public.get_revenue_rollup(bigint, date, date, text) TO service_role;

COMMENT ON FUNCTION public.get_revenue_kpis(bigint, date, date) IS
  'Finance KPIs from completed payments. Includes platform_revenue and delivery_revenue GROSS.';

COMMENT ON FUNCTION public.get_revenue_rollup(bigint, date, date, text) IS
  'Revenue rollup from completed payments; includes platform and delivery GROSS splits.';

-- ---------------------------------------------------------------------------
-- 9. split_order: delivery unsupported in Phase 1
-- ---------------------------------------------------------------------------

DO $patch_split$
DECLARE
  v_def text;
  v_updated text;
  v_needle text := $n$IF COALESCE(v_source.payment_status, 'unpaid') = 'paid' THEN
    RAISE EXCEPTION 'split_source_paid' USING ERRCODE = '22023';
  END IF;$n$;
  v_insert text := $n$IF COALESCE(v_source.payment_status, 'unpaid') = 'paid' THEN
    RAISE EXCEPTION 'split_source_paid' USING ERRCODE = '22023';
  END IF;

  IF v_source.order_type = 'delivery' THEN
    RAISE EXCEPTION 'split_delivery_unsupported' USING ERRCODE = '22023';
  END IF;$n$;
BEGIN
  SELECT pg_catalog.pg_get_functiondef(p.oid)
  INTO v_def
  FROM pg_catalog.pg_proc AS p
  JOIN pg_catalog.pg_namespace AS n
    ON n.oid = p.pronamespace
  WHERE n.nspname = 'public'
    AND p.proname = 'split_order'
    AND pg_catalog.pg_get_function_identity_arguments(p.oid)
      = 'p_source_order_id bigint, p_item_partials jsonb, p_idempotency_key uuid';

  IF v_def IS NULL THEN
    RAISE EXCEPTION 'split_order missing';
  END IF;

  v_def := replace(replace(v_def, E'\r\n', E'\n'), E'\r', E'\n');
  v_def := regexp_replace(
    v_def,
    '^CREATE (OR REPLACE )?FUNCTION',
    'CREATE OR REPLACE FUNCTION'
  );

  IF position(v_needle in v_def) = 0 THEN
    RAISE EXCEPTION 'split_order paid guard needle missing';
  END IF;

  IF position('split_delivery_unsupported' in v_def) = 0 THEN
    v_updated := replace(v_def, v_needle, v_insert);
    IF v_updated = v_def THEN
      RAISE EXCEPTION 'split_order delivery guard patch failed';
    END IF;
    EXECUTE v_updated;
  END IF;
END;
$patch_split$;

-- ---------------------------------------------------------------------------
-- 10. Kitchen print payload: copy delivery_platform + external_order_ref
-- ---------------------------------------------------------------------------

DO $patch_route$
DECLARE
  v_def text;
  v_updated text;
  v_needle text := $n$'order_type', v_order.order_type,
        'table_number', v_table_no,$n$;
  v_insert text := $n$'order_type', v_order.order_type,
        'delivery_platform', v_order.delivery_platform,
        'external_order_ref', v_order.external_order_ref,
        'table_number', v_table_no,$n$;
BEGIN
  SELECT pg_catalog.pg_get_functiondef(p.oid)
  INTO v_def
  FROM pg_catalog.pg_proc AS p
  JOIN pg_catalog.pg_namespace AS n
    ON n.oid = p.pronamespace
  WHERE n.nspname = 'public'
    AND p.proname = 'route_order_to_kds'
    AND pg_catalog.pg_get_function_identity_arguments(p.oid) = 'p_order_id bigint';

  IF v_def IS NULL THEN
    RAISE EXCEPTION 'route_order_to_kds missing';
  END IF;

  v_def := replace(replace(v_def, E'\r\n', E'\n'), E'\r', E'\n');
  v_def := regexp_replace(
    v_def,
    '^CREATE (OR REPLACE )?FUNCTION',
    'CREATE OR REPLACE FUNCTION'
  );

  IF position('delivery_platform'', v_order.delivery_platform' in v_def) > 0 THEN
    RETURN;
  END IF;

  IF position(v_needle in v_def) = 0 THEN
    RAISE EXCEPTION 'route_order_to_kds order_type payload needle missing';
  END IF;

  v_updated := replace(v_def, v_needle, v_insert);
  IF v_updated = v_def THEN
    RAISE EXCEPTION 'route_order_to_kds delivery payload patch failed';
  END IF;

  EXECUTE v_updated;
END;
$patch_route$;

DO $patch_kds_complete$
DECLARE
  v_def text;
  v_updated text;
  v_payload_needle text := $n$'order_type', v_route.order_type,
      'table_number', v_route.table_number,$n$;
  v_payload_insert text := $n$'order_type', v_route.order_type,
      'delivery_platform', v_route.delivery_platform,
      'external_order_ref', v_route.external_order_ref,
      'table_number', v_route.table_number,$n$;
  v_routed_needle text := $n$orders.order_type,
        orders.note AS order_note,
        dining_table.number AS table_number,$n$;
  v_routed_insert text := $n$orders.order_type,
        orders.delivery_platform,
        orders.external_order_ref,
        orders.note AS order_note,
        dining_table.number AS table_number,$n$;
  v_group_needle text := $n$order_number,
        order_type,
        table_number,$n$;
  v_group_insert text := $n$order_number,
        order_type,
        delivery_platform,
        external_order_ref,
        table_number,$n$;
BEGIN
  SELECT pg_catalog.pg_get_functiondef(p.oid)
  INTO v_def
  FROM pg_catalog.pg_proc AS p
  JOIN pg_catalog.pg_namespace AS n
    ON n.oid = p.pronamespace
  WHERE n.nspname = 'private'
    AND p.proname = 'enqueue_kitchen_completion_print_internal'
    AND pg_catalog.pg_get_function_identity_arguments(p.oid)
      = 'p_branch_id bigint, p_ticket_ids bigint[], p_actor uuid';

  IF v_def IS NULL THEN
    RAISE NOTICE 'enqueue_kitchen_completion_print_internal missing; skip';
    RETURN;
  END IF;

  v_def := replace(replace(v_def, E'\r\n', E'\n'), E'\r', E'\n');
  v_def := regexp_replace(
    v_def,
    '^CREATE (OR REPLACE )?FUNCTION',
    'CREATE OR REPLACE FUNCTION'
  );

  IF position('delivery_platform'', v_route.delivery_platform' in v_def) > 0 THEN
    RETURN;
  END IF;

  IF position(v_payload_needle in v_def) = 0
    OR position(v_routed_needle in v_def) = 0
    OR position(v_group_needle in v_def) = 0
  THEN
    RAISE NOTICE 'kitchen completion print delivery needles missing; skip';
    RETURN;
  END IF;

  v_updated := replace(v_def, v_payload_needle, v_payload_insert);
  v_updated := replace(v_updated, v_routed_needle, v_routed_insert);
  -- SELECT list and GROUP BY share the same fragment; replace both.
  v_updated := replace(v_updated, v_group_needle, v_group_insert);

  EXECUTE v_updated;
END;
$patch_kds_complete$;

-- ---------------------------------------------------------------------------
-- 11. Seed / upsert channel markup (Shopee default 25% from contract)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.seed_menu_item_channel_prices(
  p_delivery_platform text,
  p_markup_percent numeric DEFAULT NULL,
  p_menu_item_ids bigint[] DEFAULT NULL
) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_platform text := lower(btrim(COALESCE(p_delivery_platform, '')));
  v_markup numeric(8, 4);
  v_upserted integer := 0;
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  IF NOT public.has_permission_any('menu:write') THEN
    RAISE EXCEPTION 'permission denied: menu:write' USING ERRCODE = '42501';
  END IF;

  IF v_platform NOT IN ('grab', 'shopee', 'be', 'green_sm') THEN
    RAISE EXCEPTION 'invalid_delivery_platform' USING ERRCODE = '22023';
  END IF;

  v_markup := COALESCE(
    p_markup_percent,
    CASE WHEN v_platform = 'shopee' THEN 25 ELSE NULL END
  );

  IF v_markup IS NULL OR v_markup < 0 OR v_markup > 500 THEN
    RAISE EXCEPTION 'markup_percent_required' USING ERRCODE = '22023';
  END IF;

  WITH targets AS (
    SELECT mi.id, mi.base_price
    FROM public.menu_items mi
    WHERE mi.tenant_id = v_tenant
      AND mi.is_active = TRUE
      AND (
        p_menu_item_ids IS NULL
        OR mi.id = ANY (p_menu_item_ids)
      )
  ),
  upserted AS (
    INSERT INTO public.menu_item_channel_prices (
      tenant_id, menu_item_id, delivery_platform, unit_price
    )
    SELECT
      v_tenant,
      targets.id,
      v_platform,
      round(targets.base_price * (1 + v_markup / 100.0), 0)
    FROM targets
    ON CONFLICT (tenant_id, menu_item_id, delivery_platform)
    DO UPDATE SET
      unit_price = EXCLUDED.unit_price,
      updated_at = now()
    RETURNING 1
  )
  SELECT count(*)::integer INTO v_upserted FROM upserted;

  RETURN jsonb_build_object(
    'success', true,
    'delivery_platform', v_platform,
    'markup_percent', v_markup,
    'upserted', v_upserted
  );
END;
$$;

REVOKE ALL ON FUNCTION public.seed_menu_item_channel_prices(text, numeric, bigint[]) FROM PUBLIC;
GRANT ALL ON FUNCTION public.seed_menu_item_channel_prices(text, numeric, bigint[]) TO authenticated;
GRANT ALL ON FUNCTION public.seed_menu_item_channel_prices(text, numeric, bigint[]) TO service_role;

COMMENT ON FUNCTION public.seed_menu_item_channel_prices(text, numeric, bigint[]) IS
  'Upsert channel list prices from base_price * (1+markup%). Shopee default markup 25% (SHOPEEFOOD_VN_0392303 Điều 3.1).';
