-- =============================================================
-- Intentionally empty for fresh DB project.
--
-- Trước đây file này:
--   1. Rollback recipes "Sườn cọng" + "Sườn Cốt Lết" (do prev seed sai)
--   2. Tạo 2 finished_good "Sườn cọng đã ướp" + "Sườn cốt lết đã ướp"
--   3. Insert 42 dòng production_recipes
--
-- Đã bỏ vì 2 file recipe seed (20260508070447, 20260508071109) cũng đã
-- empty stub, không có gì để rollback. DB mới sẽ owner tự seed qua UI.
-- =============================================================
