-- =============================================================
-- Intentionally empty for fresh DB project.
--
-- Trước đây file này seed menu_item "Sườn cọng" + 21 dòng recipe.
-- Đã bỏ vì migration 20260508071920_redo_suon_as_production_recipes.sql
-- đã rollback rồi và chuẩn bị DB mới không cần ingredient/recipe seed.
-- =============================================================
