CREATE TABLE public.holiday_surcharge_policies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL
    REFERENCES public.tenants(id) ON DELETE CASCADE,
  branch_id bigint
    REFERENCES public.branches(id) ON DELETE CASCADE,
  name text NOT NULL,
  calculation_type text NOT NULL,
  value numeric(15,2) NOT NULL,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid NOT NULL
    REFERENCES public.profiles(id) ON DELETE RESTRICT,
  updated_by uuid NOT NULL
    REFERENCES public.profiles(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT holiday_surcharge_policies_name_check
    CHECK (length(btrim(name)) BETWEEN 3 AND 120),
  CONSTRAINT holiday_surcharge_policies_calculation_type_check
    CHECK (calculation_type IN ('percentage', 'fixed')),
  CONSTRAINT holiday_surcharge_policies_value_check
    CHECK (
      (
        calculation_type = 'percentage'
        AND value > 0
        AND value <= 100
      )
      OR (
        calculation_type = 'fixed'
        AND value > 0
        AND value <= 50000000
        AND value = trunc(value)
      )
    ),
  CONSTRAINT holiday_surcharge_policies_time_check
    CHECK (ends_at > starts_at)
);

COMMENT ON TABLE public.holiday_surcharge_policies IS
  'Owner-configured holiday surcharge schedules. Branch-specific policies override tenant-wide policies.';
COMMENT ON COLUMN public.holiday_surcharge_policies.value IS
  'Percentage points when calculation_type=percentage, otherwise a fixed VND amount.';
COMMENT ON COLUMN public.holiday_surcharge_policies.ends_at IS
  'Exclusive policy end timestamp.';

CREATE INDEX idx_holiday_surcharge_policies_lookup
  ON public.holiday_surcharge_policies (
    tenant_id,
    branch_id,
    is_active,
    starts_at,
    ends_at
  );

ALTER TABLE public.holiday_surcharge_policies ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.holiday_surcharge_policies
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.holiday_surcharge_policies TO service_role;

REVOKE ALL ON SEQUENCE public.holiday_surcharge_policies_id_seq
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON SEQUENCE public.holiday_surcharge_policies_id_seq TO service_role;

CREATE OR REPLACE FUNCTION private.validate_holiday_surcharge_policy()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_branch_tenant bigint;
  v_has_overlap boolean;
BEGIN
  NEW.name := btrim(NEW.name);
  NEW.updated_at := now();

  IF NEW.branch_id IS NOT NULL THEN
    SELECT b.tenant_id
    INTO v_branch_tenant
    FROM public.branches b
    WHERE b.id = NEW.branch_id;

    IF v_branch_tenant IS NULL OR v_branch_tenant <> NEW.tenant_id THEN
      RAISE EXCEPTION 'holiday_surcharge_branch_invalid'
        USING ERRCODE = '22023';
    END IF;
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtextextended(
      'holiday_surcharge_policy:'
        || NEW.tenant_id::text
        || ':'
        || COALESCE(NEW.branch_id::text, 'tenant'),
      0
    )
  );

  IF NEW.is_active THEN
    SELECT EXISTS (
      SELECT 1
      FROM public.holiday_surcharge_policies p
      WHERE p.tenant_id = NEW.tenant_id
        AND p.branch_id IS NOT DISTINCT FROM NEW.branch_id
        AND p.is_active
        AND p.id IS DISTINCT FROM NEW.id
        AND tstzrange(p.starts_at, p.ends_at, '[)')
          && tstzrange(NEW.starts_at, NEW.ends_at, '[)')
    )
    INTO v_has_overlap;

    IF v_has_overlap THEN
      RAISE EXCEPTION 'holiday_surcharge_policy_overlap'
        USING ERRCODE = '23P01';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_holiday_surcharge_policy
  BEFORE INSERT OR UPDATE OF
    tenant_id,
    branch_id,
    name,
    calculation_type,
    value,
    starts_at,
    ends_at,
    is_active,
    updated_by
  ON public.holiday_surcharge_policies
  FOR EACH ROW
  EXECUTE FUNCTION private.validate_holiday_surcharge_policy();

REVOKE ALL ON FUNCTION private.validate_holiday_surcharge_policy()
  FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_holiday_surcharge_policies()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_result jsonb;
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  IF NOT public.auth_is_owner(v_uid)
     OR NOT public.has_permission_any('settings:tenant') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', p.id,
        'branch_id', p.branch_id,
        'branch_name', b.name,
        'name', p.name,
        'calculation_type', p.calculation_type,
        'value', p.value,
        'starts_at', p.starts_at,
        'ends_at', p.ends_at,
        'is_active', p.is_active,
        'created_at', p.created_at,
        'updated_at', p.updated_at
      )
      ORDER BY p.is_active DESC, p.starts_at DESC, p.id DESC
    ),
    '[]'::jsonb
  )
  INTO v_result
  FROM public.holiday_surcharge_policies p
  LEFT JOIN public.branches b
    ON b.id = p.branch_id
   AND b.tenant_id = p.tenant_id
  WHERE p.tenant_id = v_tenant;

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.upsert_holiday_surcharge_policy(
  p_policy_id bigint,
  p_name text,
  p_branch_id bigint,
  p_calculation_type text,
  p_value numeric,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_is_active boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_policy public.holiday_surcharge_policies%ROWTYPE;
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  IF NOT public.auth_is_owner(v_uid)
     OR NOT public.has_permission_any('settings:tenant') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  IF p_name IS NULL
     OR p_calculation_type IS NULL
     OR p_value IS NULL
     OR p_starts_at IS NULL
     OR p_ends_at IS NULL
     OR p_is_active IS NULL THEN
    RAISE EXCEPTION 'holiday_surcharge_policy_invalid'
      USING ERRCODE = '22023';
  END IF;

  IF p_branch_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.branches b
    WHERE b.id = p_branch_id
      AND b.tenant_id = v_tenant
      AND b.is_active IS TRUE
      AND b.branch_kind = 'branch'
  ) THEN
    RAISE EXCEPTION 'holiday_surcharge_branch_invalid'
      USING ERRCODE = '22023';
  END IF;

  IF p_policy_id IS NULL THEN
    INSERT INTO public.holiday_surcharge_policies (
      tenant_id,
      branch_id,
      name,
      calculation_type,
      value,
      starts_at,
      ends_at,
      is_active,
      created_by,
      updated_by
    ) VALUES (
      v_tenant,
      p_branch_id,
      p_name,
      p_calculation_type,
      p_value,
      p_starts_at,
      p_ends_at,
      p_is_active,
      v_uid,
      v_uid
    )
    RETURNING * INTO v_policy;
  ELSE
    UPDATE public.holiday_surcharge_policies p
    SET branch_id = p_branch_id,
        name = p_name,
        calculation_type = p_calculation_type,
        value = p_value,
        starts_at = p_starts_at,
        ends_at = p_ends_at,
        is_active = p_is_active,
        updated_by = v_uid
    WHERE p.id = p_policy_id
      AND p.tenant_id = v_tenant
    RETURNING p.* INTO v_policy;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'holiday_surcharge_policy_not_found'
        USING ERRCODE = 'P0002';
    END IF;
  END IF;

  RETURN jsonb_build_object(
    'id', v_policy.id,
    'is_active', v_policy.is_active,
    'updated_at', v_policy.updated_at
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.set_holiday_surcharge_policy_active(
  p_policy_id bigint,
  p_is_active boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_tenant bigint := public.auth_tenant_id();
  v_policy public.holiday_surcharge_policies%ROWTYPE;
BEGIN
  IF v_uid IS NULL OR v_tenant IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  IF NOT public.auth_is_owner(v_uid)
     OR NOT public.has_permission_any('settings:tenant') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  IF p_policy_id IS NULL OR p_is_active IS NULL THEN
    RAISE EXCEPTION 'holiday_surcharge_policy_invalid'
      USING ERRCODE = '22023';
  END IF;

  UPDATE public.holiday_surcharge_policies p
  SET is_active = p_is_active,
      updated_by = v_uid
  WHERE p.id = p_policy_id
    AND p.tenant_id = v_tenant
  RETURNING p.* INTO v_policy;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'holiday_surcharge_policy_not_found'
      USING ERRCODE = 'P0002';
  END IF;

  RETURN jsonb_build_object(
    'id', v_policy.id,
    'is_active', v_policy.is_active,
    'updated_at', v_policy.updated_at
  );
END;
$$;

COMMENT ON FUNCTION public.get_holiday_surcharge_policies() IS
  'Owner-only holiday surcharge policy list for the authenticated tenant.';
COMMENT ON FUNCTION public.upsert_holiday_surcharge_policy(
  bigint,
  text,
  bigint,
  text,
  numeric,
  timestamptz,
  timestamptz,
  boolean
) IS
  'Owner-only create or update for a holiday surcharge policy. Same-scope active periods cannot overlap.';
COMMENT ON FUNCTION public.set_holiday_surcharge_policy_active(bigint, boolean) IS
  'Owner-only activation control for a holiday surcharge policy.';

REVOKE ALL ON FUNCTION public.get_holiday_surcharge_policies()
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.upsert_holiday_surcharge_policy(
  bigint,
  text,
  bigint,
  text,
  numeric,
  timestamptz,
  timestamptz,
  boolean
) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.set_holiday_surcharge_policy_active(bigint, boolean)
  FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.get_holiday_surcharge_policies()
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.upsert_holiday_surcharge_policy(
  bigint,
  text,
  bigint,
  text,
  numeric,
  timestamptz,
  timestamptz,
  boolean
) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.set_holiday_surcharge_policy_active(bigint, boolean)
  TO authenticated, service_role;

ALTER TABLE public.orders
  ADD COLUMN holiday_surcharge_policy_id bigint
    REFERENCES public.holiday_surcharge_policies(id) ON DELETE SET NULL,
  ADD COLUMN holiday_surcharge_source text NOT NULL DEFAULT 'none',
  ADD COLUMN holiday_surcharge_calculation_type text,
  ADD COLUMN holiday_surcharge_value numeric(15,2),
  ADD COLUMN holiday_surcharge_policy_name text;

UPDATE public.orders
SET holiday_surcharge_source = CASE
  WHEN service_charge > 0 THEN 'manual'
  ELSE 'none'
END;

ALTER TABLE public.orders
  ADD CONSTRAINT orders_service_charge_nonnegative_check
    CHECK (service_charge >= 0),
  ADD CONSTRAINT orders_holiday_surcharge_source_check
    CHECK (
      holiday_surcharge_source IN ('none', 'automatic', 'manual', 'waived')
    ),
  ADD CONSTRAINT orders_holiday_surcharge_calculation_type_check
    CHECK (
      holiday_surcharge_calculation_type IS NULL
      OR holiday_surcharge_calculation_type IN ('percentage', 'fixed')
    ),
  ADD CONSTRAINT orders_holiday_surcharge_value_check
    CHECK (
      holiday_surcharge_value IS NULL
      OR holiday_surcharge_value > 0
    ),
  ADD CONSTRAINT orders_holiday_surcharge_source_amount_check
    CHECK (
      (holiday_surcharge_source = 'none' AND service_charge = 0)
      OR (
        holiday_surcharge_source = 'automatic'
        AND holiday_surcharge_calculation_type IS NOT NULL
        AND holiday_surcharge_value IS NOT NULL
        AND holiday_surcharge_policy_name IS NOT NULL
      )
      OR (holiday_surcharge_source = 'manual' AND service_charge > 0)
      OR (holiday_surcharge_source = 'waived' AND service_charge = 0)
    );

COMMENT ON COLUMN public.orders.holiday_surcharge_policy_id IS
  'Source policy when an automatic holiday surcharge snapshot was attached to the order.';
COMMENT ON COLUMN public.orders.holiday_surcharge_source IS
  'Current surcharge source: none, automatic, manual, or waived.';
COMMENT ON COLUMN public.orders.holiday_surcharge_calculation_type IS
  'Order-time policy snapshot used to recalculate an automatic surcharge.';
COMMENT ON COLUMN public.orders.holiday_surcharge_value IS
  'Order-time percentage points or fixed VND policy value.';
COMMENT ON COLUMN public.orders.holiday_surcharge_policy_name IS
  'Order-time policy name snapshot retained when the policy changes later.';

CREATE OR REPLACE FUNCTION public.pos_normalize_order_discount_totals()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_item_discount numeric(15,2) := 0;
  v_order_discount numeric(15,2) := 0;
  v_discount_base numeric(15,2) := 0;
  v_surcharge_base numeric(15,2) := 0;
  v_policy record;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_item_discount := COALESCE(NEW.item_discount_amount, 0);

    IF NEW.holiday_surcharge_source = 'none'
       AND NEW.holiday_surcharge_policy_id IS NULL THEN
      SELECT
        p.id,
        p.name,
        p.calculation_type,
        p.value
      INTO v_policy
      FROM public.holiday_surcharge_policies p
      WHERE p.tenant_id = NEW.tenant_id
        AND (p.branch_id IS NULL OR p.branch_id = NEW.branch_id)
        AND p.is_active
        AND p.starts_at <= COALESCE(NEW.created_at, now())
        AND p.ends_at > COALESCE(NEW.created_at, now())
      ORDER BY (p.branch_id IS NOT NULL) DESC, p.starts_at DESC, p.id DESC
      LIMIT 1;

      IF FOUND THEN
        NEW.holiday_surcharge_policy_id := v_policy.id;
        NEW.holiday_surcharge_source := 'automatic';
        NEW.holiday_surcharge_calculation_type := v_policy.calculation_type;
        NEW.holiday_surcharge_value := v_policy.value;
        NEW.holiday_surcharge_policy_name := v_policy.name;
      END IF;
    END IF;
  ELSE
    SELECT COALESCE(
      SUM(
        LEAST(
          COALESCE(oi.discount_amount, 0),
          COALESCE(oi.subtotal, 0)
        )
      ),
      0
    )
    INTO v_item_discount
    FROM public.order_items oi
    WHERE oi.order_id = NEW.id
      AND oi.tenant_id = NEW.tenant_id
      AND oi.status <> 'cancelled';

    IF NEW.service_charge IS DISTINCT FROM OLD.service_charge
       AND NEW.holiday_surcharge_source
         IS NOT DISTINCT FROM OLD.holiday_surcharge_source
       AND NEW.holiday_surcharge_source <> 'automatic' THEN
      NEW.holiday_surcharge_source := CASE
        WHEN COALESCE(NEW.service_charge, 0) > 0 THEN 'manual'
        ELSE 'waived'
      END;
    END IF;
  END IF;

  IF NEW.status = 'cancelled' THEN
    NEW.item_discount_amount := 0;
    NEW.order_discount_amount := 0;
    NEW.discount_amount := 0;
    NEW.discount_type := NULL;
    NEW.discount_value := NULL;
    NEW.discount_note := NULL;
    NEW.total_amount := GREATEST(0, COALESCE(NEW.service_charge, 0));
    RETURN NEW;
  END IF;

  v_item_discount := LEAST(
    GREATEST(v_item_discount, 0),
    COALESCE(NEW.subtotal, 0)
  );
  v_discount_base := GREATEST(
    COALESCE(NEW.subtotal, 0) - v_item_discount,
    0
  );

  IF NEW.discount_type IS NOT NULL AND NEW.discount_value IS NOT NULL THEN
    IF NEW.discount_type = 'pct' THEN
      NEW.discount_value := LEAST(
        GREATEST(COALESCE(NEW.discount_value, 0), 0),
        100
      );
    ELSIF NEW.discount_type = 'vnd' THEN
      NEW.discount_value := LEAST(
        GREATEST(COALESCE(NEW.discount_value, 0), 0),
        v_discount_base
      );
    END IF;

    v_order_discount := public.compute_discount_amount(
      NEW.discount_type,
      NEW.discount_value,
      v_discount_base
    );
  END IF;

  IF v_order_discount <= 0 THEN
    NEW.order_discount_amount := 0;
    NEW.discount_type := NULL;
    NEW.discount_value := NULL;
    NEW.discount_note := NULL;
  ELSE
    NEW.order_discount_amount := v_order_discount;
    NEW.discount_note := NULLIF(btrim(COALESCE(NEW.discount_note, '')), '');
  END IF;

  NEW.item_discount_amount := v_item_discount;
  NEW.discount_amount := COALESCE(NEW.order_discount_amount, 0)
    + v_item_discount;
  v_surcharge_base := GREATEST(
    0,
    COALESCE(NEW.subtotal, 0) - COALESCE(NEW.discount_amount, 0)
  );

  IF NEW.holiday_surcharge_source = 'automatic' THEN
    IF NEW.holiday_surcharge_calculation_type = 'percentage' THEN
      NEW.service_charge := ROUND(
        v_surcharge_base * NEW.holiday_surcharge_value / 100,
        0
      );
    ELSE
      NEW.service_charge := ROUND(NEW.holiday_surcharge_value, 0);
    END IF;
  ELSIF NEW.holiday_surcharge_source IN ('none', 'waived') THEN
    NEW.service_charge := 0;
  ELSE
    NEW.service_charge := ROUND(COALESCE(NEW.service_charge, 0), 2);
  END IF;

  NEW.total_amount := GREATEST(
    0,
    v_surcharge_base + COALESCE(NEW.service_charge, 0)
  );

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.pos_normalize_order_discount_totals()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER trg_orders_normalize_discount_totals ON public.orders;
CREATE TRIGGER trg_orders_normalize_discount_totals
  BEFORE INSERT OR UPDATE OF
    subtotal,
    service_charge,
    discount_type,
    discount_value,
    discount_note,
    order_discount_amount,
    item_discount_amount,
    discount_amount,
    status,
    holiday_surcharge_policy_id,
    holiday_surcharge_source,
    holiday_surcharge_calculation_type,
    holiday_surcharge_value,
    holiday_surcharge_policy_name,
    updated_at
  ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.pos_normalize_order_discount_totals();

CREATE OR REPLACE FUNCTION public.prevent_order_amount_mutation_after_payment_code_exposed()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_money_changed boolean;
  v_cancelled_unpaid boolean;
BEGIN
  IF TG_OP <> 'UPDATE' THEN
    RETURN NEW;
  END IF;

  IF COALESCE(OLD.payment_status, 'unpaid') = 'paid' THEN
    RETURN NEW;
  END IF;

  v_money_changed :=
    NEW.subtotal IS DISTINCT FROM OLD.subtotal
    OR NEW.tax_amount IS DISTINCT FROM OLD.tax_amount
    OR NEW.service_charge IS DISTINCT FROM OLD.service_charge
    OR NEW.discount_type IS DISTINCT FROM OLD.discount_type
    OR NEW.discount_value IS DISTINCT FROM OLD.discount_value
    OR NEW.discount_note IS DISTINCT FROM OLD.discount_note
    OR NEW.order_discount_amount IS DISTINCT FROM OLD.order_discount_amount
    OR NEW.item_discount_amount IS DISTINCT FROM OLD.item_discount_amount
    OR NEW.discount_amount IS DISTINCT FROM OLD.discount_amount
    OR NEW.total_amount IS DISTINCT FROM OLD.total_amount
    OR NEW.holiday_surcharge_policy_id
      IS DISTINCT FROM OLD.holiday_surcharge_policy_id
    OR NEW.holiday_surcharge_source
      IS DISTINCT FROM OLD.holiday_surcharge_source
    OR NEW.holiday_surcharge_calculation_type
      IS DISTINCT FROM OLD.holiday_surcharge_calculation_type
    OR NEW.holiday_surcharge_value
      IS DISTINCT FROM OLD.holiday_surcharge_value
    OR NEW.holiday_surcharge_policy_name
      IS DISTINCT FROM OLD.holiday_surcharge_policy_name;

  v_cancelled_unpaid :=
    NEW.status = 'cancelled'
    AND OLD.status IS DISTINCT FROM NEW.status
    AND COALESCE(OLD.payment_status, 'unpaid') <> 'paid';

  IF (v_money_changed OR v_cancelled_unpaid)
     AND public.order_payment_code_is_exposed(
       OLD.id,
       OLD.tenant_id,
       OLD.branch_id,
       OLD.payment_code
     )
  THEN
    RAISE EXCEPTION 'payment_code_locked' USING ERRCODE = '22023';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER trg_orders_zz_payment_code_lock ON public.orders;
CREATE TRIGGER trg_orders_zz_payment_code_lock
  BEFORE UPDATE OF
    status,
    subtotal,
    tax_amount,
    service_charge,
    discount_type,
    discount_value,
    discount_note,
    order_discount_amount,
    item_discount_amount,
    discount_amount,
    total_amount,
    holiday_surcharge_policy_id,
    holiday_surcharge_source,
    holiday_surcharge_calculation_type,
    holiday_surcharge_value,
    holiday_surcharge_policy_name,
    updated_at
  ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.prevent_order_amount_mutation_after_payment_code_exposed();

CREATE OR REPLACE FUNCTION public.set_order_service_charge(
  p_order_id bigint,
  p_amount numeric,
  p_note text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_uid uuid;
  v_prof_tenant bigint;
  v_prof_branch bigint;
  v_prof_role text;
  v_order record;
  v_note_trim text;
  v_amount numeric(15,2);
  v_total_amount numeric(15,2);
  v_has_pending boolean;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'unauthenticated' USING ERRCODE = '28000';
  END IF;

  SELECT
    p.tenant_id,
    p.branch_id,
    COALESCE(private.staff_role_from_position_code(po.code), 'unassigned')
  INTO v_prof_tenant, v_prof_branch, v_prof_role
  FROM public.profiles p
  LEFT JOIN public.positions po ON po.id = p.position_id
  WHERE p.id = v_uid;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'profile not found' USING ERRCODE = '28000';
  END IF;

  IF v_prof_role IS NULL OR v_prof_role NOT IN
     ('owner', 'branch_manager', 'cashier') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  IF p_amount IS NULL OR p_amount < 0 THEN
    RAISE EXCEPTION 'service_charge_invalid_amount' USING ERRCODE = '22023';
  END IF;

  IF p_amount > 50000000 THEN
    RAISE EXCEPTION 'service_charge_amount_too_large' USING ERRCODE = '22023';
  END IF;

  v_note_trim := COALESCE(btrim(p_note), '');
  IF length(v_note_trim) < 3 THEN
    RAISE EXCEPTION 'service_charge_note_required' USING ERRCODE = '22023';
  END IF;

  PERFORM pg_advisory_xact_lock(p_order_id);

  SELECT
    o.id,
    o.tenant_id,
    o.branch_id,
    o.status,
    o.payment_status
  INTO v_order
  FROM public.orders o
  WHERE o.id = p_order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'order not found' USING ERRCODE = 'P0002';
  END IF;

  IF v_order.tenant_id <> v_prof_tenant THEN
    RAISE EXCEPTION 'tenant mismatch' USING ERRCODE = '42501';
  END IF;

  IF v_prof_role = 'owner' THEN
    PERFORM 1
    FROM public.branches b
    WHERE b.id = v_order.branch_id
      AND b.tenant_id = v_prof_tenant;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'invalid branch' USING ERRCODE = 'P0002';
    END IF;
  ELSIF v_prof_branch IS NULL
        OR v_order.branch_id IS DISTINCT FROM v_prof_branch THEN
    RAISE EXCEPTION 'branch mismatch' USING ERRCODE = '42501';
  END IF;

  IF v_order.status IN ('completed', 'cancelled') THEN
    RAISE EXCEPTION 'order terminal' USING ERRCODE = '22023';
  END IF;

  IF COALESCE(v_order.payment_status, 'unpaid') = 'paid' THEN
    RAISE EXCEPTION 'order already paid' USING ERRCODE = '22023';
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM public.payments p
    WHERE p.order_id = p_order_id
      AND p.tenant_id = v_order.tenant_id
      AND p.branch_id = v_order.branch_id
      AND p.status = 'pending'
  )
  INTO v_has_pending;

  IF COALESCE(v_order.payment_status, 'unpaid') = 'pending'
     OR v_has_pending THEN
    RAISE EXCEPTION 'service_charge_payment_pending'
      USING ERRCODE = '22023';
  END IF;

  v_amount := ROUND(p_amount::numeric, 2);

  UPDATE public.orders
  SET service_charge = v_amount,
      holiday_surcharge_source = CASE
        WHEN v_amount = 0 THEN 'waived'
        ELSE 'manual'
      END,
      updated_at = now()
  WHERE id = p_order_id
  RETURNING total_amount INTO v_total_amount;

  INSERT INTO public.order_status_history (
    tenant_id,
    order_id,
    from_status,
    to_status,
    changed_by,
    note
  ) VALUES (
    v_order.tenant_id,
    p_order_id,
    v_order.status,
    v_order.status,
    v_uid,
    CASE
      WHEN v_amount = 0 THEN 'holiday_surcharge_waived'
      ELSE 'holiday_surcharge_manual: ' || v_amount::text || 'đ'
    END || ' :: ' || v_note_trim
  );

  RETURN jsonb_build_object(
    'order_id', p_order_id,
    'service_charge', v_amount,
    'total_amount', v_total_amount
  );
END;
$$;

COMMENT ON FUNCTION public.set_order_service_charge(bigint, numeric, text) IS
  'Manually override or waive the holiday surcharge before payment while preserving the original automatic policy snapshot.';
