-- =============================================================
-- Intentionally empty for fresh DB project.
--
-- Trước đây file này seed 3 finished_good (Nước mắm pha sẵn, Sốt mật ong,
-- Trà lài nấu sẵn) + production_recipes. Đã bỏ vì:
--   1. Phụ thuộc raw ingredients chưa được seed bởi migration nào.
--   2. Chuẩn bị DB mới: data ingredient/recipe sẽ do owner nhập qua UI.
-- =============================================================
